import {up} from './rounding.mjs';
export const fuelReference='Traveller Core Rulebook Update 2022, p. 157: jump fuel is 10% of ship hull tonnage per parsec (minimum Jump-1). Fuel prices: p. 154. Power-plant fuel is outside this tool. Final fuel tonnage rounds up to whole tons [R].';
export function validateFuel(ship){const f=ship.fuel;if(f==null)return;for(const k of ['displacementTons','capacityTons','aboardTons'])if(!Number.isSafeInteger(f[k])||f[k]<0)throw Error('Ship size and fuel quantities must be nonnegative whole tons.');if(f.bladderJumps!==undefined){if(!Number.isSafeInteger(f.bladderJumps)||f.bladderJumps<0||!Number.isSafeInteger(f.baseCapacityTons)||f.baseCapacityTons<1||!Number.isSafeInteger(f.bladderTons)||f.bladderTons<0||f.capacityTons!==f.baseCapacityTons+f.bladderTons||f.bladderTons!==f.bladderJumps*Math.ceil(f.displacementTons*ship.jump/10))throw Error('Invalid fuel bladder capacity.');}if(!f.displacementTons||!f.capacityTons||f.capacityTons>f.displacementTons||f.aboardTons>f.capacityTons)throw Error('Enter a positive ship size and tank capacity, with fuel aboard no greater than the tank and tank capacity no greater than ship size.');}
export function configureFuel(displacementTons,baseCapacityTons,aboardTons,bladderJumps,jump){
 if(!Number.isSafeInteger(bladderJumps)||bladderJumps<0)throw Error('Bladder jumps must be a nonnegative whole number.');
 if(!Number.isInteger(jump)||jump<1||jump>6)throw Error('Jump rating must be 1 to 6.');
 const bladderTons=bladderJumps*Math.ceil(displacementTons*jump/10);
 const fuel={displacementTons,baseCapacityTons,aboardTons,bladderJumps,bladderTons,capacityTons:baseCapacityTons+bladderTons};validateFuel({fuel,jump});return fuel;
}
export function bladderSpace(ship){return ship.fuel?.bladderTons||0;}
export function jumpFuel(ship,parsecs){validateFuel(ship);if(!ship.fuel)return null;if(!Number.isSafeInteger(parsecs)||parsecs<0||parsecs>ship.jump)throw Error('Jump distance exceeds the configured jump rating.');const distance=Math.max(1,parsecs),f=ship.fuel,tons=Number((BigInt(f.displacementTons)*BigInt(distance)+9n)/10n);return {distance,displacementTons:f.displacementTons,tons,before:f.aboardTons,after:Math.max(0,f.aboardTons-tons),consumed:Math.min(f.aboardTons,tons),shortfall:Math.max(0,tons-f.aboardTons),capacity:f.capacityTons};}
export function fuelPurchase(ship,value){validateFuel(ship);if(!ship.fuel)return null;const tons=Number(up(value)),f=ship.fuel;if(!Number.isSafeInteger(tons)||tons<=0)throw Error('Enter a positive whole fuel quantity.');if(tons>f.capacityTons-f.aboardTons)throw Error('Fuel purchase exceeds available tank capacity.');return {tons,before:f.aboardTons,after:f.aboardTons+tons,capacity:f.capacityTons,displacementTons:f.displacementTons};}
export function consumeJumpFuel(ship,parsecs){const q=jumpFuel(ship,parsecs);if(!q)return null;ship.fuel.aboardTons=q.after;return q;}
