import {parseUWP} from './rules.mjs';
const API='https://travellermap.com/api/';
async function get(path,params){const url=new URL(path,API);Object.entries(params).forEach(([k,v])=>url.searchParams.set(k,v));const response=await fetch(url,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error('Traveller Map returned '+response.status);return response.json();}
export function normalize(w){if(!Number.isInteger(w.WorldX)||!Number.isInteger(w.WorldY)||!w.Sector||!/^\d{4}$/.test(w.Hex))throw Error('Traveller Map world is missing coordinates');return {id:w.WorldX+','+w.WorldY,name:w.Name||w.Hex,sector:w.Sector,hex:w.Hex,x:w.WorldX,y:w.WorldY,uwp:w.UWP,zone:w.Zone==='A'?'Amber':w.Zone==='R'?'Red':'Safe',gasGiants:w.PBG&&w.PBG[2]!=='?'?parseInt(w.PBG[2],16):null,raw:structuredClone(w)};}
export async function loadWorld(sector,hex){if(!sector.trim()||!/^\d{4}$/.test(hex))throw Error('Enter a sector and four-digit hex');const data=await get('jumpworlds',{sector,hex,jump:0});if(!Array.isArray(data.Worlds)||!data.Worlds.length)throw Error('No world at that location');return normalize(data.Worlds[0]);}
export async function nearby(world,radius=6){const data=await get('jumpworlds',{x:world.x,y:world.y,jump:radius});if(!Array.isArray(data.Worlds))throw Error('Invalid world-list response');return data.Worlds.map(normalize);}
export function distance(a,b){const az=a.y-Math.floor(a.x/2),bz=b.y-Math.floor(b.x/2),dx=a.x-b.x,dz=az-bz;return Math.max(Math.abs(dx),Math.abs(dz),Math.abs(dx+dz));}
export function fuel(world,ship,data){if(world.fuelOverride===true)return true;if(world.fuelOverride===false)return false;try{const u=parseUWP(world.overrideUWP||world.uwp,data);if(['A','B','C','D'].includes(u.starport))return true;return !!ship.scoops&&(world.gasGiants>0||world.accessibleWater===true);}catch{return false;}}
export function plan(worlds,stops,ship,data){if(stops.length<2)throw Error('Choose an origin and destination');const all=Object.values(worlds).sort((a,b)=>a.id.localeCompare(b.id));if(all.length>1600)throw Error('Route search exceeds 1,600 loaded worlds. Plan shorter segments.');const result=[];for(let leg=1;leg<stops.length;leg++){const from=worlds[stops[leg-1]],to=worlds[stops[leg]];if(!from||!to)throw Error('Load every mandatory stop first');if(!fuel(from,ship,data)||!fuel(to,ship,data))throw Error('Fuel availability is unconfirmed at '+(!fuel(from,ship,data)?from.name:to.name));if(from.id===to.id){if(!result.length)result.push(from.id);continue;}const best=new Map([[from.id,{jumps:0,length:0,path:[from.id]}]]),queue=[from.id],visited=new Set();const compare=(a,b)=>a.jumps-b.jumps||a.length-b.length||a.path.join('|').localeCompare(b.path.join('|'));while(queue.length){queue.sort((a,b)=>compare(best.get(a),best.get(b)));const id=queue.shift();if(visited.has(id))continue;visited.add(id);if(id===to.id)break;const at=best.get(id);for(const w of all){const d=distance(worlds[id],w);if(!d||d>ship.jump||!fuel(w,ship,data)||visited.has(w.id))continue;const option={jumps:at.jumps+1,length:at.length+d,path:[...at.path,w.id]};if(!best.has(w.id)||compare(option,best.get(w.id))<0){best.set(w.id,option);queue.push(w.id);}}}if(!best.has(to.id))throw Error('No valid connection from '+from.name+' to '+to.name+' within the loaded search area (12 parsecs around each requested stop).');const path=best.get(to.id).path;result.push(...(result.length?path.slice(1):path));}return result;}
