import {ruleInfo} from './rule-references.mjs?v=campaign-writes-20261010-34';
import {escapeHtml,formatCreditsText} from './display.mjs?v=campaign-writes-20261010-34';
import * as A from './amounts.mjs';
import {manualLuggage} from './accommodation.mjs?v=campaign-writes-20261010-34';
import * as P from './passengers.mjs?v=campaign-writes-20261010-34';
import {passengerOffers,passageLabel,PASSAGE_CLASSES} from './passenger-rules.mjs?v=campaign-writes-20261010-34';
import {supportStock,monthlySupport,supportDisplay} from './life-support.mjs?v=campaign-writes-20261010-34';
import {displayDate} from './calendar.mjs';
const esc=escapeHtml;
const money=formatCreditsText,signed=x=>x>0?'+'+x:String(x);
const facts=rows=>'<dl class="passenger-facts">'+rows.map(([k,v])=>'<dt>'+esc(k)+'</dt><dd>'+esc(v)+'</dd>').join('')+'</dl>';
const button=(label,action,arg='',mutate=false,disabled=false)=>'<button data-action="'+action+'" data-arg="'+esc(arg)+'" '+(mutate?'data-mutate ':'')+(disabled?'data-unavailable disabled ':'')+'>'+esc(label)+'</button>';
const field=(name,label,value='',extra='')=>'<label class="field">'+esc(label)+'<input name="'+name+'" value="'+esc(value)+'" '+extra+'></label>';
const select=(name,label,options,value)=>'<label class="field">'+esc(label)+'<select name="'+name+'">'+options.map(([v,l])=>'<option value="'+v+'" '+(v===value?'selected':'')+'>'+esc(l)+'</option>').join('')+'</select></label>';
const check=(name,label)=>'<label class="check"><input type="checkbox" name="'+name+'">'+esc(label)+'</label>';
const roll=r=>r?.dice?.length?r.dice.join(' + ')+' = '+r.total:r?.total===0?'0 (no dice)':r?.total!=null?'Manual total '+r.total:'Not recorded';
const modeLabel=mode=>({private:'Private cabin',shared:'Shared, two per cabin',cargo:'Fitted spare space, 2 t/person',low:'Installed Low berth'}[mode]||mode);
export function createPassengerUI({getState,getCore,getWorld,getWorlds,getView,modal,act,render,message,S,R,M}){
 let drafts=[],searchId=null;
 const state=()=>getState(),world=id=>getWorld(id),date=h=>h==null?'Not recorded':displayDate(state().dateLabel,h);
 function clear(){drafts=[];searchId=null;}
 function activeDrafts(){const s=state();return searchId===s.latestPassengerSearchId&&drafts[0]?.origin===s.actual?drafts:[];}
 function details(c){
  const a=c.audit||{},dm=a.dm||{},s=state(),source=c.status?c.status==='accepted'?'Aboard; unpaid':'Delivered and paid':'Available search result';
  let html=facts([['Passage',passageLabel(c.passageClass)],['People',c.count],['Status',source],['Origin',world(c.origin)?.name||c.origin],['Destination',world(c.destination)?.name||c.destination],['Fare per person',money(c.fare)],['Agreed total',money(c.payment)],['Accommodation',c.cabinMode?modeLabel(c.cabinMode):'Choose on boarding'],['Baggage allowance per person',P.bookingLuggage[c.passageClass]+' t before the whole-ship override / aggregate rounding'],['Accepted',date(c.acceptedHours)],['Delivered',date(c.deliveredHours)]]);
  if(c.status==='delivered')html+=facts([['Payment received',money(c.payout)]]);
  html+='<h3>Passenger availability calculation '+ruleInfo('passengers')+'</h3>'+facts([['Search 2D',roll(a.searchDice)],['Search skill',a.searchSkill??'Not recorded'],['Characteristic DM',a.searchCharacteristic??'Not recorded'],['Search Effect',dm.effect],['Highest Steward skill',dm.steward],['Origin DM',signed(dm.origin??0)],['Destination DM',signed(dm.destination??0)],['Distance DM',signed(dm.distance??0)],['Referee DM',signed(dm.refereeDM??0)],['Class DM',signed(a.classDM??0)],['Traffic 2D',roll(a.traffic)],['Modified traffic result',a.total],['Count dice',a.countDice+'D'],['Available people roll',roll(a.count)],['Direct jump distance',a.distance+' parsecs'],['Recorded origin population',a.originPopulation??'Unknown; exact cap requires referee review']]);
  for(const key of ['origin','destination']){const w=a.worldInputs?.[key],d=dm.components?.[key];if(w&&d)html+='<h4>'+esc(key==='origin'?'Origin at search':'Destination at search')+'</h4>'+facts([['World',w.name],['Population code',w.population],['Starport',w.starport],['Travel zone',w.zone],['Population DM',signed(d.population)],['Starport DM',signed(d.starport)],['Zone DM',signed(d.zone)]]);}
  if(c.populationException)html+=facts([['Exceptional population circumstances',c.populationException]]);
  if(c.status)html+=facts([['Steward service confirmed',c.serviceConfirmed?'Yes':'Not required for this class'],['Fitted spare space confirmed',c.spaceConfirmed?'Yes':'Not used'],['Payment rounding',c.roundingStep===100?'Up to Cr100':'Up to whole Credits']]);
  return html+'<p class="help">Accommodation '+ruleInfo('accommodation')+' · Booking and delivery '+ruleInfo('booking')+'</p><p class="help">'+esc(P.passengerReference)+'</p><p class="help">Campaign: High luggage 1 t/person; Middle 0. High sharing is an explicit allocation. Shared groups of the same class use two places per cabin. Existing cabin/person costs and whole-ship luggage overrides remain in force. Low revival is resolved in play.</p>';
 }
 function panel(){
  const s=state(),q=P.passengerCapacity(s),available=activeDrafts(),bookings=P.passengerBookings(s),stock=supportStock(P.passengerShip(s));
  const summary=q.configured?`${q.freeCabins} cabins and ${q.freeLowBerths} Low berths free · ${q.counts.total} booked people aboard`:'Review crew/cabin allocation and installed Low berths before boarding';
  let html='<section class="panel passenger-panel" aria-label="Passengers"><div class="panel-head"><h2>Passengers</h2><div class="row">'+button('Find passengers','passenger-search','',true)+button(q.configured?'Review passenger capacity':'Set passenger capacity','passenger-setup','',true)+'</div></div><div class="panel-body"><p class="passenger-summary">'+esc(summary)+'</p><p class="help">Fares cover one jump. Select how many people to board. Payment is recorded only when you complete passage at the destination. Existing crew and other people are counted separately.</p>';
  if(q.configured)html+='<details><summary>Accommodation &amp; supplies '+ruleInfo('accommodation')+'</summary>'+facts([['Installed cabins',q.installedCabins],['Reserved for crew / other existing people',q.reservedCabins],['Cabins used by passenger bookings',q.bookedCabins],['Installed / occupied Low berths',q.installedLowBerths+' / '+q.occupiedLowBerths],['Awake people, including booked passengers',stock.awakePeople],['Frozen people, including booked Low',stock.occupiedLowBerths],['Consumption',stock.dailyUnits+' LSS/day'],['Whole-ship luggage reservation',q.luggage+' t'],['Basic fitted-space reservation',q.cargoSpace+' t']])+'<p class="help">Booked people are automatic. Do not enter them again in Settings. Crew cabin sharing is your allocation. High double occupancy remains available; two High people in one standard-cost High cabin cost Cr7,000/month.</p></details>';
  if(manualLuggage(s.ship))html+='<p class="notice">A manual whole-ship luggage total is active. Boarding and delivery keep that fixed total until you edit it in Settings.</p>';
  if(available.length)html+='<div class="passenger-offers">'+available.map(o=>{const n=P.passengerOfferRemaining(s,o);return '<article class="passenger-offer"><h3>'+passageLabel(o.passageClass)+'</h3><strong>'+n+' available</strong><p>'+money(o.fare)+' / person · '+esc(world(o.destination)?.name||o.destination)+'</p><p class="help">Traffic '+o.audit.total+' → '+o.audit.countDice+'D · rolled '+o.count+' people</p><div class="row">'+button('Board passengers','passenger-board',o.offerId,true,n<1||!q.configured)+button('Audit','passenger-offer-audit',o.offerId)+'</div></article>';}).join('')+'</div>';
  else html+='<p class="help">Search results are active only in this session. Earlier calculations remain in History.</p>';
  if(bookings.length)html+='<div class="scroll"><table><thead><tr><th>Passage / people</th><th>Destination</th><th>Accommodation</th><th>Revenue</th><th>Status</th><th>Actions</th></tr></thead><tbody>'+bookings.map(c=>'<tr><td>'+passageLabel(c.passageClass)+' · '+c.count+'</td><td>'+esc(world(c.destination)?.name||c.destination)+'</td><td>'+esc(modeLabel(c.cabinMode))+'</td><td>'+money(c.payment)+'</td><td>'+esc(c.status==='accepted'?'Aboard · unpaid':'Delivered · paid')+'</td><td class="table-actions">'+(c.status==='accepted'?button('Complete passage','passenger-deliver',c.id,true,s.actual!==c.destination):'')+button('Audit','contract-audit',c.id)+'</td></tr>').join('')+'</tbody></table></div>';
  return html+'</div></section>';
 }
 function setup(){
  const s=state(),q=P.passengerCapacity(s),a=s.ship.accommodation;if(!a)throw Error('Set up the existing people and cabins in Settings first.');
  modal('Review passenger capacity','<p class="help">Accommodation '+ruleInfo('accommodation')+'</p><p>Existing installed cabins: <strong>'+q.installedCabins+'</strong>. Allocate the cabins already used by crew and other non-booked people. Sharing is referee-managed; four crew might use two cabins.</p><p class="help">Low-service cabins are not Low berths. Enter the number of physical Low berths installed. Existing frozen occupants: '+(a.occupiedLowBerths||0)+'. This review does not change people, bank or supplies.</p><div class="split">'+field('reservedCabins','Cabins reserved for crew / other non-booked people',q.reservedCabins??'','type="number" min="0" max="'+q.installedCabins+'" step="1" required')+field('installedLowBerths','Installed Low berths',q.installedLowBerths??'','type="number" min="0" step="1" required')+'</div>'+check('reviewed','I reviewed existing people and cabin sharing; future booked passengers will be counted automatically.'),f=>{
   if(!f.has('reviewed')||f.get('reservedCabins')===''||f.get('installedLowBerths')==='')throw Error('Review both capacities and confirm the existing allocation.');
   act('Passenger capacity settings',n=>S.configurePassengerCapacity(n,{reservedCabins:Number(f.get('reservedCabins')),installedLowBerths:Number(f.get('installedLowBerths'))}));
  },'Save passenger capacity');
 }
 function search(){
  const s=state();if(getView()?.id!==s.actual||world(s.actual)?.emptySpace)throw Error('Find passengers at the ship’s actual world.');
  const destinations=Object.values(getWorlds()).filter(w=>w.id!==s.actual&&!w.emptySpace&&M.distance(world(s.actual),w)<=s.ship.jump).sort((a,b)=>a.name.localeCompare(b.name));if(!destinations.length)throw Error('Load nearby worlds within the ship’s jump rating first.');
  const generated=R.roll(2);
  modal('Find passengers','<p class="help">Passenger traffic and fares '+ruleInfo('passengers')+'</p>'+select('destination','Single-jump destination',destinations.map(w=>[w.id,w.name+' · '+w.hex]),destinations.some(w=>w.id===s.route[s.routeIndex+1])?s.route[s.routeIndex+1]:destinations[0].id)+'<div class="split">'+field('dice','Search 2D total',generated.total,'type="number" min="2" max="12" step="1" required')+field('skill','Broker / Carouse / Streetwise skill',Math.max(s.trader.broker,s.trader.streetwise),'type="number" step="1" required')+field('characteristic','Search characteristic DM',s.trader.characteristic,'type="number" step="1" required')+field('steward','Highest Steward skill aboard',0,'type="number" min="0" step="1" required')+'</div><p class="help">Search Effect = 2D + skill + characteristic − 8. Traffic is rolled separately for each class. No Credits, time or supplies are spent by this check.</p><details><summary>Manual traffic/count dice (optional)</summary>'+field('sequence','Dice in roll order, comma-separated','','type="text"')+'<p class="help">Order: Low, Basic, Middle, High; each uses two traffic dice followed by its count dice. Unspecified dice roll normally. A typed sequence is retained in the audit.</p></details>',f=>{
   const current=state(),to=world(f.get('destination')),dice=Number(f.get('dice')),skill=Number(f.get('skill')),characteristic=Number(f.get('characteristic')),steward=Number(f.get('steward'));
   if(!Number.isInteger(dice)||dice<2||dice>12||![skill,characteristic,steward].every(Number.isSafeInteger))throw Error('Enter valid search dice and whole-number skill/DM values.');
   if(!to||to.emptySpace||M.distance(world(current.actual),to)>current.ship.jump)throw Error('Choose a destination within one jump.');
   const raw=String(f.get('sequence')||'').trim(),sequence=raw?raw.split(',').map(x=>Number(x.trim())):[];if(sequence.some(x=>!Number.isInteger(x)||x<1||x>6))throw Error('Manual dice must be values 1–6.');
   let at=0;const rng=()=>at<sequence.length?sequence[at++]:R.die(),id=S.uid(),searchDice=dice===generated.total?generated:{dice:null,total:dice,manual:true};
   const offers=passengerOffers(R.context(world(current.actual),getCore()),R.context(to,getCore()),M.distance(world(current.actual),to),{effect:dice+skill+characteristic-8,steward},getCore(),rng).map(o=>({...o,offerId:S.uid(),origin:current.actual,destination:to.id,audit:{...o.audit,searchDice,searchSkill:skill,searchCharacteristic:characteristic,manualDice:sequence}}));
   act('Passenger search',n=>S.recordPassengerSearch(n,{id,label:'Passenger search audit',world:current.actual,destination:to.id,hours:current.hours,offers,manualDice:sequence,manualDiceConsumed:at}));
   drafts=offers;searchId=id;render();message('Passenger availability recorded. Choose how many people to board.');
  },'Find passengers');
 }
 function board(offerId){
  const c=activeDrafts().find(o=>o.offerId===offerId);if(!c)throw Error('This passenger offer is no longer active. Search again.');const remaining=P.passengerOfferRemaining(state(),c),kind=c.passageClass,modes=kind==='low'?[['low','Installed Low berth']]:kind==='basic'?[['shared','Shared cabins · two people per cabin'],['cargo','Fitted spare space · 2 t per person']]:[['private','Private cabins · one per person'],['shared','Shared cabins · two per cabin (referee allocation)']];
  modal('Board '+passageLabel(kind)+' passengers','<p class="help">Accommodation '+ruleInfo('accommodation')+'</p><p>'+remaining+' available to '+esc(world(c.destination).name)+' at '+money(c.fare)+' per person. Boarding reserves accommodation; payment is due on explicit delivery.</p>'+field('count','People to board',1,'type="number" min="1" max="'+remaining+'" step="1" required')+select('cabinMode','Accommodation',modes,modes[0][0])+(kind==='high'||kind==='middle'?'<p class="help">'+(kind==='high'?'High requires a Steward skill level per ten passengers.':'Middle requires a Steward skill level per hundred; Steward 0 can serve ten.')+' Include people already aboard when checking service.</p>'+check('serviceConfirmed','Steward service is available for these passengers.'):'')+(kind==='basic'?check('spaceConfirmed','For spare-space accommodation: the selected space is fitted for passengers.'):'')+(kind==='low'?'<p class="notice">Low revival checks and their consequences are resolved in play. Completing passage records the agreed payment; no automated death or penalty is applied.</p>':'')+field('populationException','Exceptional population circumstances (only if required)','','type="text"'),f=>{
   if(!activeDrafts().some(o=>o.offerId===offerId))throw Error('This passenger offer is no longer active.');
   const args={count:Number(f.get('count')),cabinMode:f.get('cabinMode'),serviceConfirmed:f.has('serviceConfirmed'),spaceConfirmed:f.has('spaceConfirmed'),populationException:f.get('populationException')},before=state(),preview=S.transition(before,'Preview passenger boarding',n=>S.acceptPassengers(n,offerId,args)),q=P.passengerCapacity(preview),stock=supportStock(P.passengerShip(preview)),c=preview.contracts.at(-1);
   modal('Confirm passenger booking','<p class="help">Booking '+ruleInfo('booking')+' · Accommodation '+ruleInfo('accommodation')+'</p>'+facts([['Passage',passageLabel(kind)],['People boarding',args.count],['Destination',world(c.destination).name],['Payment on delivery',money(c.payment)],['Cabins / Low berths free after',q.freeCabins+' / '+q.freeLowBerths],['Total luggage after',q.luggage+' t'],['Basic fitted space after',q.cargoSpace+' t'],['Cargo space free after',supportDisplay(A.sub(preview.ship.capacity,S.used(preview)))+' t'],['Total consumption after',stock.dailyUnits+' LSS/day'],['Monthly cabin/person bundle after',money(monthlySupport(P.passengerShip(preview)))],['Supplies','Existing LSS stock is preserved']])+'<p class="help">Booked people are added automatically. Do not enter them again in Settings. Cabin sharing changes accommodation use, not the number of people receiving service.</p>',()=>{
    if(!activeDrafts().some(o=>o.offerId===offerId))throw Error('This passenger offer is no longer active.');act('Accepted passenger booking',n=>S.acceptPassengers(n,offerId,args));render();
   },'Board passengers');return false;
  },'Preview boarding');
 }
 function deliver(id){const c=state().contracts.find(c=>c.id===id&&c.kind==='passenger');if(!c||c.status!=='accepted')throw Error('Passenger booking is not awaiting delivery.');S.assertWorld(state(),c.destination);const preview={...state(),contracts:state().contracts.map(x=>x.id===c.id?{...x,status:'delivered'}:x)},capacity=P.passengerCapacity(preview);modal('Complete passenger passage','<p class="help">Booking and delivery '+ruleInfo('booking')+'</p>'+facts([['Class / people',passageLabel(c.passageClass)+' / '+c.count],['Destination',world(c.destination).name],['Payment',money(c.payment)],['Whole-ship luggage after',capacity.luggage+' t'],['Cabins / Low berths free after',capacity.freeCabins+' / '+capacity.freeLowBerths]])+(manualLuggage(state().ship)?'<p class="notice">Your manual whole-ship luggage total remains fixed after delivery. Edit it in Settings if the actual total changes.</p>':'')+'<p class="help">This releases the booking and records its payment once. Used life support is not restored. Payment on delivery is the app convention, with no automatic lateness penalty.</p>',()=>act('Delivered passenger booking',s=>S.deliverPassengers(s,id)),'Complete passage & payout');}
 function auditOffer(id){const c=activeDrafts().find(o=>o.offerId===id);if(!c)throw Error('Offer is no longer active. Find its read-only result in History.');modal('Passenger availability audit',details(c),null);}
 return {panel,details,setup,search,board,deliver,auditOffer,clear};
}
