import {initial,validate} from './state.mjs?v=bladder-stock-1';
export const KEY='traveller-trade-route-calculator:v1';
const LOCK=KEY+':writer';
export class Store{
 constructor(onChange,onRole){this.onChange=onChange;this.onRole=onRole;this.editable=false;this.release=null;this.id=crypto.randomUUID();this.channel=typeof BroadcastChannel==='function'?new BroadcastChannel(KEY):null;this.channel?.addEventListener('message',e=>{if(e.data.type==='takeover'&&e.data.id!==this.id)this.yield();});window.addEventListener('storage',e=>{if(e.key===KEY){this.onChange(this.read());}if(e.key===KEY+':takeover'&&e.newValue!==this.id)this.yield();});}
 read(){const raw=localStorage.getItem(KEY);if(!raw)return initial();let s;try{s=JSON.parse(raw);}catch{throw Error('Saved data could not be read. Export the raw backup before resetting.');}return validate(s);}
 async acquire(takeover=false){if(this.editable)return;if(!navigator.locks){this.onRole(false,'This browser lacks safe editing locks. Use a current browser.');return;}if(takeover){this.channel?.postMessage({type:'takeover',id:this.id});localStorage.setItem(KEY+':takeover',this.id);}navigator.locks.request(LOCK,takeover?{}:{ifAvailable:true},async lock=>{if(!lock){this.onRole(false,'Read-only: campaign open in another tab.');return;}this.editable=true;try{this.onChange(this.read());this.recovery=false;}catch(error){this.recovery=true;this.recoveryMessage=error.message;this.onChange(initial());}this.onRole(true,this.recovery?'Recovery mode: restore saved data':'Editing in this tab');await new Promise(resolve=>{this.release=resolve;});this.release=null;}).catch(e=>this.onRole(false,e.message));}
 yield(){this.editable=false;this.onRole(false,'Read-only: editing transferred to another tab.');this.release?.();}
 save(next,expected){if(this.recovery)throw Error('Restore or reset the saved campaign before editing.');if(!this.editable)throw Error('This tab is read-only. Take over editing first.');const current=this.read();if(current.revision!==expected)throw Error('This preview is stale. Reload it before committing.');validate(next);localStorage.setItem(KEY,JSON.stringify(next));this.onChange(next);}
 backup(){const raw=localStorage.getItem(KEY)||JSON.stringify(initial());const url=URL.createObjectURL(new Blob([raw],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='traveller-campaign-'+new Date().toISOString().slice(0,10)+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
 replace(next,expected){next=structuredClone(validate(next));next.revision=expected+1;if(this.recovery){if(!this.editable)throw Error('Take over editing before restoring');localStorage.setItem(KEY,JSON.stringify(next));this.recovery=false;this.onChange(next);this.onRole(true,'Editing in this tab');}else this.save(next,expected);}
}
