import * as A from './amounts.mjs';
import {bladderSpace,fuelPurchase} from './fuel.mjs?v=mfd-services-1';
import {expenseQuote,fuelAvailability,starport} from './expenses.mjs?v=expenses-20261009-21';
import {refillQuote,supportStock,supportCargo,supportAmount,anchorSupport} from './life-support.mjs?v=mfd-services-1';
import {used,validate,shipExpense,refillLifeSupport,uid} from './state.mjs?v=expenses-20261009-21';
import {creditStep} from './rounding.mjs';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=x=>'Cr '+String(x).replace(/\B(?=(\d{3})+(?!\d))/g,','),num=x=>x==null?'Unknown':String(Number(Number(x).toFixed(3)));
const field=(name,label,value,type='number',extra='')=>`<label class="field">${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const facts=rows=>'<dl class="service-facts">'+rows.map(([l,v])=>'<dt>'+esc(l)+'</dt><dd>'+esc(v)+'</dd>').join('')+'</dl>';
const progress=(value,max,label)=>`<progress max="${Math.max(1,Number(max))}" value="${Math.max(0,Number(value))}" aria-label="${esc(label)}"></progress>`;
export function maxFuelAddition(s){s=structuredClone(s);anchorSupport(s.ship);const f=s.ship.fuel;if(!f)return 0;const free=Math.max(0,Number(A.floor(A.sub(s.ship.capacity,used(s))))),base=f.baseCapacityTons??f.capacityTons,freeBase=Math.max(0,base-f.aboardTons);return Math.max(0,Math.min(f.capacityTons-f.aboardTons,freeBase+Math.floor(free)));}
export function fuelCorrection(s,value,reason=''){
 const before=s.ship.fuel?.aboardTons,after=Number(value);
 if(String(value).trim()===''||!Number.isSafeInteger(after)||after<0||after>before)throw Error('Enter actual fuel remaining from zero to the current amount aboard.');
 if(after===before)throw Error('Enter a lower actual fuel level to record a correction.');
 const detail={before,after,removed:before-after,reason:String(reason).trim(),bankChange:'0',world:s.actual};
 s.ship.fuel.aboardTons=after;s.events.push({id:uid(),label:'Fuel aboard correction audit',hours:s.hours,world:s.actual,fuelCorrection:detail});return detail;
}
export function createServicePanels({document,getState,isEditable,commit,render,showOverview,message,nextJumpFuel}){
 let session=null,generation=0;
 const active=()=>!!session,token=()=>session?.token??'';
 const button=(text,action,arg='',primary=false)=>`<button type="button" data-action="${action}" data-arg="${esc(arg)}" data-service-token="${session.token}" class="${primary?'primary':''}">${esc(text)}</button>`;
 function open(kind){
  if(session?.busy)throw Error('Wait for the current service to finish saving.');
  if(!['fuel','support'].includes(kind))throw Error('Unknown ship service.');
  const base=structuredClone(getState()),w=base.worlds[base.actual];
  if(!isEditable())throw Error('This tab is read-only. Take over editing first.');
  if(!base.initialized||!w)throw Error('Set up a campaign first.');
  if(w.emptySpace&&kind==='support')throw Error('No local supplies in empty space. Continue to a world first.');
  session={token:'stock-'+(++generation),kind,mode:'summary',revision:base.revision,base,world:w,draft:kind==='fuel'?{fuelType:['A','B'].includes(starport(w))?'refined':'unrefined',fuelTons:String(maxFuelAddition(base)),otherSupplier:false,expenseNotes:'',fuelRemaining:String(base.ship.fuel.aboardTons),fuelReason:''}:{extraDays:'0',comfortCredits:'0',comfortNote:''},correction:false,busy:false};
  showOverview();render();if(document.defaultView?.matchMedia('(max-width:1099px)').matches)document.getElementById('service-panel')?.scrollIntoView({block:'start',behavior:'instant'});
 }
 function stale(){return !session||session.invalidated||!isEditable()||session.revision!==getState().revision||session.base.actual!==getState().actual;}
 function status(){if(!session)return '';return stale()?'Campaign or editing ownership changed. Cancel this draft and reopen the service to use current values.':'';}
 function quote(){
  const {base,draft:d,world:w,kind,correction}=session;
  if(kind==='support'){const q=refillQuote(base,{extraDays:d.extraDays,comfortCost:d.comfortCredits,comfortNote:d.comfortNote});if(A.credit(q.amount)>A.credit(base.bank))throw Error('Insufficient funds for this refill.');if(A.cmp(A.add(A.sub(used(base),supportCargo(base.ship)),supportAmount(q.afterCargoExact)),base.ship.capacity)>0)throw Error('Life support overflow would exceed available cargo space.');if(A.cmp(supportAmount(q.purchasedStockUnits),0)===0&&A.credit(q.comfortAmount)===0n)throw Error('Stock already covers this target. Adjust extra days or comfort provisions if needed.');return q;}
  const f=base.ship.fuel;
  if(correction){const copy=structuredClone(base);anchorSupport(copy.ship);const q=fuelCorrection(copy,d.fuelRemaining,d.fuelReason);validate(copy);return {...q,amount:'0',tons:0,correcting:true};}
  const tons=Number(d.fuelTons);
  if(d.fuelTons.trim()===''||!Number.isSafeInteger(tons)||tons<0)throw Error('Enter a whole number of fuel tons.');
  if(tons===0)throw Error('No fuel to acquire. Adjust the quantity before confirming.');
  if(tons>maxFuelAddition(base))throw Error('This fuel would exceed available tank or cargo space.');
  const input={kind:'fuel',fuelType:d.fuelType,tons:String(tons),otherSupplier:d.otherSupplier,notes:d.expenseNotes,creditStep:creditStep(base),fuelShip:base.ship};
  const q=expenseQuote(w,input),tank=fuelPurchase(base.ship,tons);
  if(A.credit(q.amount)>A.credit(base.bank))throw Error('Insufficient funds for this refuel.');
  return {...q,...tank,input};
 }
 function waterWarning(){const {world:w,draft:d}=session;if(d.fuelType!=='water')return '';return fuelAvailability(w,'water').standard?'Water collection is always selectable. Access, equipment, time and fuel quality are resolved in play.':'Water availability is not established by the hydrographics or planet information at '+w.name+'. This is an advisory only: collection remains available. Access, equipment, time and fuel quality are resolved in play.';}
 function total(q,formula=''){return `<div class="service-total"><span>Total cost</span><strong>${money(q.amount)}</strong>${formula?'<small>'+esc(formula)+'</small>':''}</div>`+facts([['Credits before',money(session.base.bank)],['Credits after',money(String(A.credit(session.base.bank)-A.credit(q.amount)))]]);}
 function fuelForecast(q){const f=session.base.ship.fuel;return `<div class="service-comparison"><div><span>Current</span><strong>${q.before} t</strong><small>${f.capacityTons} t total capacity</small>${progress(q.before,f.capacityTons,'Current fuel aboard')}</div><span aria-hidden="true">→</span><div><span>${q.correcting?'Actual remaining':'After refuelling'}</span><strong>${q.after} t</strong><small>${f.capacityTons} t total capacity</small>${progress(q.after,f.capacityTons,'Fuel after confirmation')}</div></div>`+facts(q.correcting?[['Fuel removed',q.removed+' t'],['Reason',q.reason||'Not entered'],['Bank change','Cr 0 · no refund']]:[['Source',session.draft.fuelType==='water'?'Free water collection':session.draft.fuelType==='refined'?'Purchased refined':'Purchased unrefined'],['Fuel grade',session.draft.fuelType==='refined'?'Refined':'Unrefined'],['Quantity to add',q.tons+' t'],['Unit price',money(session.draft.fuelType==='water'?'0':session.draft.fuelType==='refined'?'500':'100')+' / t'],['Cargo occupied by fuel after',bladderSpace({fuel:{...f,aboardTons:q.after}})+' t']])+total(q)+(q.correcting?'<p class="help">This records actual fuel remaining, with Audit and Undo. No payment or refund is made.</p>':'<p class="help">'+esc(waterWarning())+'</p>');}
 function supportForecast(q){return `<div class="service-comparison"><div><span>Current</span><strong>${num(q.beforeDays)} days</strong><small>${num(q.beforeUnits)} LSS aboard</small></div><span aria-hidden="true">→</span><div><span>After refill + reserve</span><strong>${num(q.afterDays)} days</strong><small>${num(q.afterUnits)} LSS aboard</small></div></div>`+facts([['Standard top-up','+'+num(q.standardDays)+' days · '+money(q.standardAmount)],['Extra reserve',num(q.extraUnits)+' LSS · '+money(q.extraAmount)],['Comfort provisions',money(q.comfortAmount)],['Internal stores',num(q.afterInternalUnits)+' / '+num(q.internalCapacityUnits)+' LSS'],['Cargo overflow',num(q.afterCargoTons)+' t']])+total(q,[q.standardAmount,q.extraAmount,q.comfortAmount].map(money).join(' + '))+'<p class="help">Only supplies beyond internal capacity use cargo space. Comfort provisions add no days or LSS.</p><details class="service-audit"><summary>Audit · Home rule</summary>'+facts([['Extra supply rate','Cr 1,000 / person-equivalent / 28 days'],['Pricing headcount',num(q.dailyUnits)+' (awake + 0.1 × occupied low berths)'],['Extra duration purchased',num(q.extraPurchasedDays??q.extraDays)+' days'],['Rounding','Combined extra charge rounded up once to Cr100'],['Comfort note',session.draft.comfortNote||'Not entered']])+'</details><p class="help rule-footnote">Consumption / capacity / storage: Cluster Truck, p. 14. One LSS per awake person/day; occupied low berths use one-tenth. Internal capacity is four LSS per hull ton; overflow uses 0.01 t/LSS.</p>';}
 function forecast(){try{const q=quote();return {html:session.kind==='fuel'?fuelForecast(q):supportForecast(q),valid:true};}catch(error){const stock=session.kind==='support'?supportStock(session.base.ship):null,current=session.kind==='fuel'?session.base.ship.fuel.aboardTons+' / '+session.base.ship.fuel.capacityTons+' t':num(stock.remainingDays)+' days · '+num(stock.remainingUnits)+' LSS';return {html:'<p class="help">Current stock: '+esc(current)+'</p><p class="notice" role="alert">'+esc(error.message)+'</p>',valid:false};}}
 function fuelEditor(){const {draft:d,base,correction}=session,f=base.ship.fuel,max=maxFuelAddition(base);if(correction)return '<p class="help">Record a lower actual fuel level. This is an inventory correction with no bank change.</p>'+field('fuelRemaining','Actual fuel remaining · tons',d.fuelRemaining,'number',`min="0" max="${f.aboardTons}" step="1" required`)+field('fuelReason','Reason (optional)',d.fuelReason,'text');
 return `<div class="service-current"><span>Current fuel</span><strong>${f.aboardTons} / ${f.capacityTons} t</strong>${button('Adjust fuel aboard','service-fuel-correct')}${progress(f.aboardTons,f.capacityTons,'Current fuel aboard')}</div><label class="field">Fuel source / grade<select name="fuelType">${[['water','Collect water · unrefined · Cr 0 / t'],['unrefined','Purchased unrefined · Cr 100 / t'],['refined','Refined · Cr 500 / t']].map(([v,l])=>`<option value="${v}" ${d.fuelType===v?'selected':''}>${l}</option>`).join('')}</select></label><p id="fuel-availability" class="help">${esc(waterWarning())}</p><label class="check"><input type="checkbox" name="otherSupplier" ${d.otherSupplier?'checked':''}>Other supplier / referee confirms purchase availability</label><p class="help">Purchased fuel only. A source note is required outside standard starport availability.</p><div class="service-quantity">${button('−10 t','service-fuel-step','-10')}${field('fuelTons','Fuel to add · tons',d.fuelTons,'number',`min="0" max="${max}" step="1" required`)}${button('+10 t','service-fuel-step','10')}</div><div class="service-shortcuts">${button('Top off · '+(f.capacityTons-f.aboardTons)+' t','service-fuel-topoff')}${button('Fuel for next jump','service-fuel-next')}</div>${max<f.capacityTons-f.aboardTons?'<p class="notice">Cargo space limits this refill to '+max+' t. Top off uses all currently available tank and cargo space.</p>':''}${field('expenseNotes','Notes / fuel source (optional)',d.expenseNotes,'text')}`;
 }
 function supportEditor(){const {draft:d,base}=session,s=supportStock(base.ship);return `<div class="service-current"><span>Current supplies</span><strong>${num(s.remainingDays)} days</strong><small>${num(s.remainingUnits)} LSS aboard</small></div><p class="help">Standard refill target: ${num(s.targetDays)} days. Stock already aboard is credited before any purchase.</p>${field('extraDays','Extra days beyond standard refill',d.extraDays,'number','min="0" step="1" required')}<p class="help">1-day steps, or type an exact whole number.</p><details class="service-comfort" ${Number(d.comfortCredits)?'open':''}><summary>Extra provisions · comfort spending</summary>${field('comfortCredits','Comfort provisions · Cr',d.comfortCredits,'number','min="0" step="1000" required')}${field('comfortNote','Comfort provisions note (required when spending)',d.comfortNote,'text')}<p class="help">Cost only. No additional days, LSS or capacity.</p></details><p class="help">Confirm supplies are available at ${esc(session.world.name)}.</p>`;}
 function panel(){if(!session)return '';const f=forecast(),s=session.kind==='support'?supportStock(session.base.ship):null,title=session.kind==='fuel'?(session.correction?'Adjust fuel aboard':'Refuel'):'Life support',editing=session.mode==='adjust';return `<aside id="service-panel" class="panel world-screen service-panel" aria-label="Ship service"><div class="screen-topline"><span>● Ship service</span><span>${editing?'Edit details':'Summary'}</span></div>${button('← Back to world data','service-back')}<h2>${title}${editing?'':' · Summary'}</h2><h3>${esc(session.base.ship.name)} · at ${esc(session.world.name)}</h3><p class="help">Actual ship location · ${session.kind==='fuel'?'Starport '+esc(starport(session.world)):num(session.base.ship.fuel?.displacementTons)+' t ship · '+s.awakePeople+' awake people · '+s.occupiedLowBerths+' occupied low berths'}</p><p class="help service-session-note">Jump and campaign changes are paused while this draft is open. The map remains available.</p><p id="service-status" class="notice" role="alert" ${status()?'':'hidden'}>${esc(status())}</p>${editing?'<form id="service-form" data-service-token="'+session.token+'">'+(session.kind==='fuel'?fuelEditor():supportEditor())+'</form>':''}<div id="service-quote" aria-live="polite">${f.html}</div><div class="service-actions">${editing?button('Cancel','service-cancel')+button('Review changes','service-review','',true):button('Adjust','service-adjust')+button(session.correction?'Confirm fuel correction':session.kind==='fuel'?'Confirm refuel':'Confirm refill','service-confirm','',true)}</div><p class="help">${editing?'Review and confirm before supplies or Credits change.':'Only final confirmation changes supplies or Credits. Cancel discards this draft.'}</p></aside>`;}
 function sync(){if(!session)return;const form=document.getElementById('service-form');if(form?.dataset?.serviceToken===session.token){for(const el of form.elements){if(!el.name)continue;session.draft[el.name]=el.type==='checkbox'?el.checked:el.value;}const box=document.getElementById('service-quote'),f=forecast();if(box)box.innerHTML=f.html;const warning=document.getElementById('fuel-availability');if(warning&&session.kind==='fuel')warning.textContent=waterWarning();}syncControls();}
 function syncControls(){if(!session)return;if(!isEditable()||session.revision!==getState().revision||session.base.actual!==getState().actual)session.invalidated=true;const invalid=stale()||!forecast().valid;document.querySelectorAll('#service-panel [data-action="service-confirm"],#service-panel [data-action="service-review"]').forEach(b=>b.disabled=invalid||session.busy);document.querySelectorAll('#service-panel input,#service-panel select').forEach(el=>el.disabled=stale());}
 function close({render:shouldRender=true}={}){if(session?.busy)return false;session=null;if(shouldRender)render();return true;}
 async function action(name,arg,actionToken){if(!name.startsWith('service-'))return false;
  // Every DOM action carries the generation it was rendered for. Detached
  // buttons and forms must never change or confirm a replacement draft.
  if(!session||actionToken!==session.token||session.busy)return true;
  if(name==='service-back'||name==='service-cancel'){close();return true;}
  if(stale())throw Error(status());sync();
  if(name==='service-adjust'){session.mode='adjust';render();}
  else if(name==='service-fuel-correct'){session.correction=true;session.mode='adjust';render();}
  else if(name==='service-review'){quote();session.mode='summary';render();}
  else if(name==='service-fuel-step'||name==='service-fuel-topoff'||name==='service-fuel-next'){
   let value=name==='service-fuel-topoff'?maxFuelAddition(session.base):name==='service-fuel-step'?(Number(session.draft.fuelTons)||0)+Number(arg):nextJumpFuel(session.base);
   if(value===null)throw Error('Plan the next jump first.');session.draft.fuelTons=String(Math.max(0,Math.min(maxFuelAddition(session.base),value)));const input=document.querySelector('#service-form [name="fuelTons"]');if(input)input.value=session.draft.fuelTons;sync();
  }else if(name==='service-confirm'){
   if(session.busy||session.mode!=='summary')return true;const q=quote(),current=session;session.busy=true;syncControls();
   try{commit(session.kind==='fuel'?(session.correction?'Adjusted fuel aboard':'Refuelled'):'Refilled life support',s=>{if(current.kind==='fuel'){if(current.correction)fuelCorrection(s,current.draft.fuelRemaining,current.draft.fuelReason);else shipExpense(s,q.input);}else refillLifeSupport(s,{extraDays:current.draft.extraDays,comfortCost:current.draft.comfortCredits,comfortNote:current.draft.comfortNote});},current.revision);session=null;render();}finally{if(session===current){session.busy=false;syncControls();}}
  }
  return true;
 }
 return {active,token,open,panel,sync,syncControls,action,close,committing:()=>!!session?.busy};
}
