const assert=require('node:assert/strict');require('./dist/data.js');const F=require('./dist/engine.js');
const base={...structuredClone(F.defaults),features:[],crew:1,passengers:0,cargo:0};
const run=x=>F.calculate({...base,...x}),budget=(name,q,s,e)=>F.optionBudget(F.options.find(o=>o.Name===name),q,{...base,...s},e);
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}
test('Multiple stations add cost but do not stack Agility',()=>{const a=run({control:'Control System (improved)'}),b=run({control:'Control System (improved)',controlQuantity:3});assert.equal(b.total-a.total,10000);assert.equal(b.agility,a.agility);assert.ok(!run({controlQuantity:0}).valid);});
test('Early prototype and prototype radio reserve volume and use basic price',()=>{const normal=budget('Transceiver, 500 km',1,{tl:6});const early=budget('Transceiver, 500 km (early prototype)',1,{tl:4});const proto=budget('Transceiver, 500 km (prototype)',1,{tl:5});assert.equal(early.spaces,2);assert.equal(proto.spaces,1);assert.equal(early.cost,normal.cost*11);assert.equal(proto.cost,normal.cost*6);});
test('Custom robot arms retain STR/DEX and squared upgrade costs',()=>{const v=budget('Robot Manipulator Arm',3,{tl:14},{armSize:6,strIncrease:1,dexIncrease:4});assert.equal(v.str,12);assert.equal(v.dex,12);assert.equal(v.cost,61200);assert.equal(v.spaces,1);});
test('Robot arm volume pools across different configurations',()=>{const r=run({equipment:[{name:'Robot Manipulator Arm',quantity:2,armSize:5},{name:'Robot Manipulator Arm',quantity:2,armSize:6}]});assert.equal(r.used,2);const free=run({spaces:1,crew:0,drone:true,equipment:[{name:'Robot Manipulator Arm',quantity:1,armSize:5},{name:'Robot Manipulator Arm',quantity:1,armSize:4}]});assert.equal(free.used,0);});
test('Manipulator upgrades reject impossible values',()=>{assert.ok(run({equipment:[{name:'Robot Manipulator Arm',quantity:1,armSize:5,strIncrease:10}]}).issues.some(i=>i.code==='ARM_CHARACTERISTICS'));assert.ok(run({equipment:[{name:'Heavy Manipulator Arm (basic)',quantity:1,strIncrease:3,dexIncrease:3}]}).issues.some(i=>i.code==='ARM_UPGRADE'));});
test('Vehicle arm increases cost but not volume',()=>{const name='Heavy Manipulator Arm (basic)',a=budget(name,1,{},{}),b=budget(name,1,{},{strIncrease:2,dexIncrease:1});assert.equal(b.cost,a.cost*8);assert.equal(b.spaces,a.spaces);});
test('Empty hardpoint reserves capacity without weapon mass or internal volume',()=>{const r=run({weapons:[{weapon:'No weapon installed',mount:'Hardpoint',quantity:1,ratedSpaces:4}]});assert.equal(r.weaponMass,0);assert.equal(r.weaponResults[0].spaces,0);assert.equal(r.weaponResults[0].cost,8000);assert.ok(r.valid);});
test('Empty turret includes reserved crew and quarter weapon volume',()=>{const r=run({crew:2,weapons:[{weapon:'No weapon installed',mount:'Turret',quantity:1,ratedSpaces:5,reservedCrew:2}]});assert.equal(r.weaponResults[0].spaces,4);assert.equal(r.weaponResults[0].cost,80000);assert.equal(r.used,4);});
test('Personal gunport budgets hatch only and rejects wrong mount',()=>{let w={weapon:'Personal weapon (gunport)',mount:'Gunport',quantity:1};let r=run({weapons:[w]});assert.equal(r.weaponResults[0].spaces,0);assert.equal(r.weaponResults[0].cost,250);assert.ok(run({weapons:[{...w,mount:'Hardpoint'}]}).issues.some(i=>i.code==='PERSONAL_GUNPORT'));});
test('Unmodelled components prevent a falsely valid import',()=>{const r=run({unmodelledComponents:['Unresolved Explorer Pod Brain specification']});assert.equal(r.valid,false);assert.ok(r.issues.some(i=>i.code==='UNMODELLED'&&i.message.includes('Explorer')));});
test('Brain interface alone cannot replace a driver',()=>{assert.ok(run({crew:0,equipment:[{name:'Vehicle Brain Interface',quantity:1}]}).issues.some(i=>i.code==='OPERATOR'));});
console.log(`${count} additional mechanical regression checks passed.`);
