const assert=require('node:assert/strict');
require('./dist/data.js');const F=require('./dist/engine.js');
let passed=0;const tests=[];
const build=x=>F.calculate({...structuredClone(F.defaults),features:[],crew:1,passengers:0,cargo:0,...x});
const has=(r,c)=>r.issues.some(i=>i.code===c);
function test(name,run){try{run();passed++;tests.push({name,status:'passed'});}catch(e){tests.push({name,status:'failed',error:e.message});console.error('FAIL',name,e.message);process.exitCode=1;}}
test('TL9 ground chassis: 12 Spaces, Cr9000, Hull24, speed High, 800km (p30)',()=>{let r=build({});assert.equal(r.total,9000);assert.equal(r.hull,24);assert.equal(r.speed,5);assert.equal(r.range,800)});
test('Default rover cost and space budget',()=>{let r=F.calculate(F.defaults);assert.equal(r.total,10350);assert.equal(r.remaining,4);assert.equal(r.valid,true)});
test('Heavy size threshold at 20, speed and agility -1 (p26)',()=>{let a=build({spaces:19}),b=build({spaces:20});assert.equal(a.speed-b.speed,1);assert.equal(a.agility-b.agility,1)});
test('Huge threshold retains one speed penalty (p26)',()=>assert.equal(build({spaces:200}).speed,build({spaces:20}).speed));
test('Aeroplane size does not reduce speed (p26)',()=>assert.equal(build({type:'Aeroplane',spaces:200}).speed,build({type:'Aeroplane',spaces:12}).speed));
test('Submersible TL9 Slow and safe depth TL6 300m (p33 correction)',()=>{assert.equal(build({type:'Submersible'}).speed,3);assert.equal(build({type:'Submersible',tl:6}).depth,300)});
test('Airship TL5 base range corrected to 6000 (p29)',()=>assert.equal(F.baseType('Airship',5).range,6000));
test('Feature costs are additive (p35)',()=>assert.equal(build({features:['Agile','Fast','Streamlined']}).baseCost,9000*5));
test('AFV + Tracks has one speed penalty (p43)',()=>assert.equal(build({spaces:20,features:['AFV','Tracks']}).speed,build({spaces:20,features:['AFV']}).speed));
test('AFV needs 20 Spaces',()=>assert.ok(has(build({features:['AFV']}),'FEATURE')));
test('Fast and Slow conflict',()=>assert.ok(has(build({features:['Fast','Slow']}),'FEATURE')));
test('Rail Rider and Tracks conflict symmetrically',()=>assert.ok(has(build({features:['Rail Rider','Tracks']}),'FEATURE')));
test('Supersonic requires jet engines',()=>assert.ok(has(build({type:'Aeroplane',features:['Supersonic']}),'FEATURE')));
test('Supersonic speed fixed at 9, supercruise allowed',()=>{const r=build({type:'Aeroplane',spaces:50,features:['Jet Engines','Supersonic'],speedMod:1});assert.equal(r.speed,9);assert.equal(r.cruise,9)});
test('Supersonic cannot take Slower (p49)',()=>assert.ok(has(build({type:'Aeroplane',features:['Jet Engines','Supersonic'],speedMod:-1}),'SLOWER_SONIC')));
test('Aeroplane stall check (p28)',()=>assert.ok(has(build({type:'Aeroplane',tl:4,features:['Floats','Slow']}),'STALL')));
test('Faster steps round independently: 12 Spaces loses 6 (p49)',()=>assert.equal(build({speedMod:2}).remaining,5));
test('Slower steps round independently: 9 Spaces gains none (p49)',()=>assert.equal(build({spaces:9,speedMod:-2}).capacity,9));
test('TL4 cannot take two Faster steps',()=>assert.ok(has(build({tl:4,speedMod:2}),'SPEED_TL')));
test('Fuel and efficiency add (p50)',()=>assert.equal(build({efficiency:1,fuel:1}).range,1400));
test('Fuel reductions capped at two',()=>assert.ok(has(build({fuel:-3}),'FUEL_LIMIT')));
test('Nonpositive range rejected',()=>assert.ok(has(build({efficiency:-3,fuel:-2}),'RANGE_ZERO')));
test('Unpowered cannot add secondary power',()=>assert.ok(has(build({power:'Unpowered',secondary:'Powered'}),'UNPOWERED_SECONDARY')));
test('Structure doubles space, free grid at TL3 (p32,45)',()=>{let r=build({type:'Structure',tl:3,spaces:100,power:'Grid Power',crew:0});assert.equal(r.capacity,200);assert.equal(r.total,5000);assert.equal(r.remaining,200)});
test('Structure p45 default power uses 30% and doubles cost',()=>{let r=build({type:'Structure',spaces:100,crew:0});assert.equal(r.remaining,170);assert.equal(r.total,10000)});
test('Structure alternative p32 ruling uses 25%',()=>assert.equal(build({type:'Structure',spaces:100,crew:0,ruling:'prose'}).remaining,175));
test('Structure can have secondary reactor (p45)',()=>assert.ok(!has(build({type:'Structure',power:'Unpowered',secondary:'Fusion (basic)'}),'UNPOWERED_SECONDARY')));
test('Muscle power -70% correction and minimum 1 Space gain',()=>{let r=build({power:'Muscle',tl:1,spaces:1});assert.equal(r.baseCost,225);assert.equal(r.capacity,2)});
test('Wind +20% correction (p46)',()=>assert.equal(build({power:'Wind',spaces:10}).capacity,12));
test('Primary fusion minimum is 10 Spaces',()=>assert.equal(build({power:'Fusion (basic)',spaces:12}).primary.spaces,10));
test('Primary fusion fractions round up',()=>assert.equal(build({power:'Fusion (basic)',spaces:43}).primary.spaces,11));
test('Secondary fusion retains minimum',()=>assert.equal(build({secondary:'Fusion (basic)',spaces:12}).secondary.spaces,10));
test('Fission requires shielding',()=>assert.ok(has(build({power:'Fission (basic)'}),'FISSION_SHIELD')));
test('Fusion+ minimum, power, range ×5 (p48)',()=>{let r=build({tl:10,power:'Fusion+ (basic)',spaces:8});assert.equal(r.primary.spaces,1);assert.equal(r.pp,1);assert.equal(r.range,4000)});
test('Armour p56 example: TL10, 30 Spaces, +10 consumes 2 Spaces',()=>{let r=build({tl:10,spaces:30,armour:10});assert.equal(r.armourSpaces,2);assert.deepEqual(r.protection,[15,15,15,15,10,10]);assert.equal(r.ledger.find(l=>l.name==='Added armour').cost,75000)});
test('Small vehicle armour volume x4',()=>assert.equal(build({tl:10,spaces:3,armour:10}).armourSpaces,1));
test('Armour includes base in maximum',()=>assert.ok(has(build({tl:7,armour:28}),'ARMOUR_LIMIT')));
test('AFV triples total armour limit',()=>assert.ok(!has(build({tl:7,spaces:20,features:['AFV'],armour:87}),'ARMOUR_LIMIT')));
test('Face allocation must conserve points',()=>assert.ok(has(build({armourShift:[1,0,0,0,0,0]}),'ARMOUR_POOL')));
test('Face cannot fall below base armour',()=>assert.ok(has(build({armourShift:[-1,1,0,0,0,0]}),'ARMOUR_BASE')));
test('Open top has zero dorsal protection',()=>assert.equal(build({features:['Open-Topped'],armour:10}).protection[4],0));
test('One-Space hull modifications rejected',()=>assert.ok(has(build({spaces:1,hull:'Reinforced'}),'ONE_HULL')));
test('Hull minimum never below one',()=>assert.equal(build({type:'Airship',spaces:1,hull:'Light'}).hull,1));
test('Space overspending is invalid',()=>assert.ok(has(build({cargo:100}),'SPACE_BUDGET')));
test('Equipment TL enforced',()=>assert.ok(has(build({equipment:[{name:'Control System (superior)',quantity:1}]}),'OPTION_TL')));
test('Powered systems unavailable on muscle-only vehicle',()=>assert.ok(has(build({power:'Muscle',equipment:[{name:'Autopilot (basic)',quantity:1}]}),'OPTION_POWER')));
test('Life support rounds per 20 people (p81)',()=>{const r=build({spaces:100,crew:21,equipment:[{name:'Hostile Environment Protection',quantity:1},{name:'Life Support (short term)',quantity:21}]});assert.equal(r.ledger.find(x=>x.name.startsWith('Life Support')).spaces,2);assert.equal(r.ledger.find(x=>x.name.startsWith('Life Support')).cost,20000)});
test('Life support needs a sealed hull',()=>assert.ok(has(build({equipment:[{name:'Life Support (short term)',quantity:1}]}),'LIFE_SEAL')));
test('Life support over capacity flagged',()=>assert.ok(has(build({crew:3,equipment:[{name:'Life Support Seat',quantity:1}]}),'LIFE_CAPACITY')));
test('Grav plating needs grav drive or lifters',()=>assert.ok(has(build({tl:12,equipment:[{name:'Grav Plating',quantity:1}]}),'GRAV_PREREQ')));
test('Satellite uplink requires 500km radio',()=>assert.ok(has(build({equipment:[{name:'Satellite Uplink',quantity:1},{name:'Transceiver, 5 km',quantity:1}]}),'UPLINK_RANGE')));
test('Satellite uplink takes zero Spaces from TL8',()=>assert.equal(F.optionBudget(F.options.find(x=>x.Name==='Satellite Uplink'),1,{...F.defaults,tl:8}).spaces,0));
test('Software p93–95 corrections enforced',()=>assert.ok(has(build({tl:12,equipment:[{name:'Computer/1',quantity:1},{name:'Salvo Solution/1',quantity:1}]}),'BANDWIDTH')));
test('Ship computer bandwidth works',()=>{let r=build({tl:12,spaces:100,equipment:[{name:'Ship Computer/5',quantity:1},{name:'Salvo Solution/1',quantity:1}]});assert.equal(r.bandwidth,5);assert.ok(!has(r,'BANDWIDTH'))});
test('Reflec and camouflage conflict',()=>assert.ok(has(build({tl:12,equipment:[{name:'Reflec',quantity:1},{name:'Camouflage (basic)',quantity:1}]}),'REFLEC_CAMOUFLAGE')));
test('Electrostatic and reactive armour conflict',()=>assert.ok(has(build({equipment:[{name:'Electrostatic Armour',quantity:1},{name:'Reactive Armour (basic)',quantity:1}]}),'ARMOUR_CONFLICT')));
test('Nuclear screen demand uses explicit PP (p76)',()=>assert.equal(build({tl:13,spaces:100,power:'Fusion (improved)',equipment:[{name:'Meson Screen',quantity:1}]}).powerDemand,9));
const heavy={weapon:'Autocannon (heavy)',quantity:1,mount:'Turret',facing:'Dorsal',remote:true,fireControl:'Basic',ammo:0};
test('Remote turret includes one loader Space under explicit p103 rule',()=>{let r=build({tl:7,spaces:20,crew:3,weapons:[heavy]});assert.equal(r.weaponResults[0].spaces,2);assert.equal(r.weaponResults[0].cost,95000)});
test('Remote gunner requires Basic FCS',()=>assert.ok(has(build({weapons:[{...heavy,fireControl:'Scope'}]}),'REMOTE_FCS')));
test('Pintle limited to 500kg',()=>assert.ok(has(build({weapons:[{...heavy,mount:'Pintle Mount'}]}),'PINTLE_MASS')));
test('External weapons count toward hard mass limit',()=>assert.ok(has(build({spaces:1,weapons:[{...heavy,mount:'Hardpoint'}]}),'WEAPON_MASS')));
test('External weapons above 100kg per Space reduce speed',()=>{let r=build({spaces:8,weapons:[{...heavy,mount:'Hardpoint'}]});assert.equal(r.speed,4)});
test('Gunport only supports one weapon',()=>assert.ok(has(build({weapons:[{...heavy,mount:'Gunport',quantity:2}]}),'GUNPORT')));
test('Turret crew not charged twice in accommodation',()=>{let r=build({spaces:100,crew:10,weapons:[{...heavy,remote:false}]});let crew=r.ledger.find(x=>x.name==='Crew accommodation').spaces;assert.equal(crew+Number(F.weapons.find(x=>x.Weapon===heavy.weapon).Crew)+Number(F.weapons.find(x=>x.Weapon===heavy.weapon).Loader),10)});
test('Malformed number and negative values rejected',()=>{assert.ok(has(build({spaces:2.5}),'INPUT'));assert.ok(has(build({cargo:-1}),'NEGATIVE'))});
test('Every exposed item retains a worksheet or book reference',()=>{for(const x of [...F.types,...F.features,...F.options,...F.weapons])assert.ok(x._source)});
test('Finite results for 10 chassis across TL0–20 and five size boundaries',()=>{for(const t of F.types)for(let tl=0;tl<=20;tl++)for(const spaces of [1,3,20,200,2000]){const r=build({type:t.Type,tl,spaces});for(const key of ['total','hull','speed','remaining','agility','shipping'])assert.ok(Number.isFinite(r[key]),`${t.Type} TL${tl} ${key}`)}});
const U=require('./dist/ui-model.js');
const option=n=>F.options.find(o=>o.Name===n);
test('Tow cable search finds both handbook towing fittings',()=>{const g=U.groups(F.options).filter(x=>U.searchText(x).includes('tow cable'));assert.deepEqual(g.map(x=>x.name),['Tow Hitch','Winch'])});
test('Tow hitch quantity means rated powered towing Spaces (p65)',()=>assert.equal(F.optionBudget(option('Tow Hitch'),20,F.defaults).cost,400));
test('Winch price uses host vehicle size (p66)',()=>assert.equal(F.optionBudget(option('Winch'),1,F.defaults).cost,600));
test('Winches cannot exceed six distinct faces',()=>assert.ok(has(build({equipment:[{name:'Winch',quantity:7}]}),'WINCH_LIMIT')));
test('All three life-support grades and seats remain exposed',()=>{for(const name of ['Life Support (short term)','Life Support (long term)','Life Support (closed cycle)','Life Support Seat'])assert.ok(option(name))});
test('Long-term and closed-cycle life support round by five people',()=>{assert.deepEqual(F.optionBudget(option('Life Support (long term)'),6,F.defaults),{spaces:2,cost:100000});assert.deepEqual(F.optionBudget(option('Life Support (closed cycle)'),6,F.defaults),{spaces:2,cost:200000})});
test('Radio encryption and tightbeam prices do not decay with TL (p59)',()=>{for(const tl of [6,10,20])assert.equal(F.optionBudget(option('Transceiver Encryption'),1,{...F.defaults,tl}).cost,4000);assert.equal(F.optionBudget(option('Transceiver Tightbeam'),1,{...F.defaults,tl:20}).cost,2000)});
test('Radio accessories require a radio rather than only a meson communicator',()=>assert.ok(has(build({tl:15,equipment:[{name:'Meson Communicator, 5000 km',quantity:1},{name:'Transceiver Encryption',quantity:1}]}),'RADIO_PREREQ')));
test('Basic sensor price follows p60 rather than worksheet discrepancy',()=>assert.equal(F.optionBudget(option('Sensor System (basic)'),1,F.defaults).cost,2000));
test('Sensor upgrades compound and add correct Spaces',()=>{const b=F.optionBudget(option('Sensor System (basic)'),2,F.defaults,{highFidelity:true,hardened:true,mast:true,rangeBoost:2});assert.deepEqual(b,{spaces:4,cost:128000,range:100})});
test('Underwater sensors retain their halved range and doubled cost',()=>assert.deepEqual(F.optionBudget(option('Sensor System (basic, underwater)'),1,F.defaults,{rangeBoost:1}),{spaces:0,cost:8000,range:5}));
test('Sensor high-fidelity and hardening TL prerequisites are enforced',()=>{const r=build({tl:5,equipment:[{name:'Sensor System (basic)',quantity:1,highFidelity:true,hardened:true}]});assert.ok(has(r,'SENSOR_FIDELITY'));assert.ok(has(r,'SENSOR_HARDENED'))});
test('Fibre optics charge Cr100 for free computer or +50% otherwise',()=>{assert.equal(F.optionBudget(option('Computer/0/fib'),1,{...F.defaults,tl:8}).cost,100);assert.equal(F.optionBudget(option('Computer/1/fib'),1,{...F.defaults,tl:8}).cost,750)});
test('Fibre-optic computer still contributes bandwidth',()=>assert.equal(build({equipment:[{name:'Computer/1/fib',quantity:1}]}).bandwidth,1));
test('Missing landing-deck grades are restored',()=>{assert.equal(F.optionBudget(option('Landing Deck (improved)'),4,F.defaults).cost,1200000);assert.equal(F.optionBudget(option('Landing Deck (advanced)'),4,F.defaults).spaces,40)});
test('Luxury exterior SOC13 uses handbook +500%',()=>assert.equal(F.optionBudget(option('Luxury Exterior (SOC 13+)'),1,F.defaults).cost,45000));
test('Docking and hangar bay allocations use worksheet prices',()=>{assert.deepEqual(F.optionBudget(option('Docking Bay'),22,F.defaults),{spaces:22,cost:275000});assert.deepEqual(F.optionBudget(option('Hangar Bay'),40,F.defaults),{spaces:40,cost:400000})});
test('Digger blade uses variable Spaces with 25% maximum',()=>{assert.deepEqual(F.optionBudget(option('Digger Blade'),3,F.defaults),{spaces:3,cost:7500});assert.ok(has(build({equipment:[{name:'Digger Blade',quantity:4}]}),'DIGGER_LIMIT'))});
test('External tank includes hardpoint, mass and p102 range example',()=>{const r=build({spaces:20,equipment:[{name:'Auxiliary Fuel Tank (external hardpoint)',quantity:5}]});assert.equal(r.range,1200);assert.equal(r.weaponMass,1250);assert.equal(r.total,27500);assert.equal(r.used,1)});
test('Self-contained AMS is not charged for another turret',()=>{const r=build({tl:9,spaces:20,weapons:[{weapon:'Anti-Missile System: Minigun',mount:'Turret',quantity:1,fireControl:'none',ammo:0}]});assert.equal(r.weaponResults[0].cost,200000);assert.equal(r.weaponResults[0].spaces,3)});
test('Gun shields use armour pricing and ignore AFV triple cap',()=>{const r=build({weapons:[{weapon:'Machinegun (medium)',quantity:1,mount:'Pintle Mount',gunShield:6,fireControl:'none',ammo:0}]});const b=build({weapons:[{weapon:'Machinegun (medium)',quantity:1,mount:'Pintle Mount',fireControl:'none',ammo:0}]});assert.equal(r.total-b.total,750);assert.ok(has(build({features:['AFV'],spaces:20,weapons:[{weapon:'Machinegun (medium)',quantity:1,mount:'Pintle Mount',gunShield:31,ammo:0}]}),'SHIELD_ARMOUR'))});
test('All 26 special ammunition profiles are present',()=>assert.equal(F.ammunition.length,27));
test('Special reserve ammo cost multiplier applies and requires compatibility review',()=>{const w={weapon:'Machinegun (medium)',quantity:1,mount:'Fixed Mount',ammo:100,ammoType:'Armour Piercing'};const special=build({weapons:[w]}),normal=build({weapons:[{...w,ammoType:'Standard'}]});const data=F.weapons.find(x=>x.Weapon===w.weapon);assert.equal(special.total-normal.total,Math.ceil(100/data.Mag)*data.MagCost*3);assert.ok(special.review)});
test('Biological weapons are omitted by scope',()=>assert.ok(F.weapons.every(w=>w.Bio!=='B')));
test('Structure rounds Hull upward in tenths (Handbook p6)',()=>{for(const [spaces,structure] of [[1,1],[5,1],[6,2],[12,3]])assert.equal(build({spaces}).structure,structure);assert.equal(build({spaces:12,hull:'Reinforced'}).structure,3)});
test('Each catalog option belongs to exactly one system dropdown',()=>{const actual=U.groups(F.options).flatMap(g=>g.options.map(o=>o.Name)).sort();assert.deepEqual(actual,F.options.filter(o=>!o.Name.startsWith('Control System')).map(o=>o.Name).sort())});
test('Autopilot and radio variants group separately from radio accessories',()=>{const g=U.groups(F.options);assert.equal(g.find(x=>x.name==='Autopilot').options.length,5);assert.equal(g.find(x=>x.name==='Transceiver').options.length,18);assert.equal(g.find(x=>x.name==='Transceiver Encryption').options.length,1)});
test('Underwater and tightbeam variants retain separate selectors',()=>{assert.equal(U.family('Sensor System (basic, underwater)'),'Underwater sensors');assert.notEqual(U.family('Long Range Transceiver (5M km)'),U.family('Long Range Transceiver (5M km) Tightbeam'))});
test('Unavailable features are omitted and invalid selections remain recoverable',()=>{const s={...structuredClone(F.defaults),type:'Watercraft',tl:1,features:['Off-Roader']};assert.ok(!U.availableFeatures(F,s).some(f=>f['Feature Effect']==='Off-Roader'));assert.ok(U.unavailableSelected(F,s).includes('Off-Roader'));for(const f of U.availableFeatures(F,s))assert.deepEqual(F.featureReasons(f['Feature Effect'],s),[])});
test('Feature selector unlocks prerequisites without changing saved selections',()=>{const s={...structuredClone(F.defaults),type:'Aeroplane',tl:12,spaces:30,features:[]};const before=JSON.stringify(s);U.availableFeatures(F,s);assert.equal(JSON.stringify(s),before);const unlocked=U.availableFeatures(F,{...s,features:['Jet Engines']});assert.ok(unlocked.length>U.availableFeatures(F,s).length)});
test('Entertainment contributes CP without consuming volume (p83)',()=>{const r=build({equipment:[{name:'Entertainment System',quantity:10}]});assert.equal(r.comfort,2);assert.equal(r.used,1)});
test('Tour guide contributes two CP without consuming volume (p100)',()=>{const r=build({tl:12,equipment:[{name:'Tour Guide',quantity:1}]});assert.equal(r.comfort,3);assert.equal(r.used,1)});
test('Pre-TL9 autopilots support grav aircraft but not ground vehicles (p58)',()=>{assert.ok(!has(build({type:'Grav Vehicle',tl:8,equipment:[{name:'Autopilot (improved)',quantity:1}]}),'AUTOPILOT_TYPE'));assert.ok(has(build({tl:8,equipment:[{name:'Autopilot (improved)',quantity:1}]}),'AUTOPILOT_TYPE'))});
test('Luxury treatment upgrades existing Spaces and stacks with entertainment (pp84–85)',()=>{const r=build({tl:12,crew:2,equipment:[{name:'Luxury Interior Space (enhanced)',quantity:2},{name:'Entertainment System',quantity:20}]});assert.equal(r.comfort,5);assert.equal(r.used,2);assert.ok(!has(r,'LUXURY_ALLOCATION'))});
test('Luxury cannot upgrade more accommodation than allocated',()=>assert.ok(has(build({equipment:[{name:'Luxury Interior Space (basic)',quantity:2}]}),'LUXURY_ALLOCATION')));
test('Linked 150kg missiles round separately under dedicated p104 rule',()=>{const w={weapon:'Anti-Air Missile (standard)',quantity:5,mount:'Hardpoint',ammo:0};const r=build({tl:12,spaces:20,weapons:[w]});assert.equal(r.weaponMass,750);assert.equal(r.weaponResults[0].cost,F.weapons.find(x=>x.Weapon===w.weapon).Cost*5+10000)});
require('node:fs').writeFileSync('verification.json',JSON.stringify({date:new Date().toISOString(),passed,total:tests.length,tests},null,2));
console.log(`${passed}/${tests.length} construction tests passed.`);
