import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import * as A from '../js/amounts.mjs';
import * as R from '../js/rules.mjs';
import * as S from '../js/state.mjs';
import * as M from '../js/map.mjs';
const core=JSON.parse(await readFile(new URL('../rules/core-2022.json',import.meta.url)));
const mp=JSON.parse(await readFile(new URL('../rules/merchant-prince-1e.json',import.meta.url)));
const w=(id='0,0',x=0,y=0)=>({id,x,y,name:id,sector:'Test',hex:'0101',uwp:'A788899-C',zone:'Safe',gasGiants:1});
test('routing uses configured maximum jump, longer legs first, and explicit shorter stops',()=>{
 const worlds=Object.fromEntries(Array.from({length:14},(_,y)=>w('0,'+y,0,y)).map(x=>[x.id,x]));
 for(let jump=1;jump<=6;jump++){
  const route=M.plan(worlds,['0,0','0,13'],{jump,scoops:false},core);
  const legs=route.slice(1).map((id,i)=>M.distance(worlds[route[i]],worlds[id]));
  assert.equal(legs.length,Math.ceil(13/jump));assert.ok(legs.every(n=>n<=jump));
  assert.ok(legs.slice(0,-1).every(n=>n===jump));
 }
 assert.deepEqual(M.plan(worlds,['0,0','0,1','0,5'],{jump:4,scoops:false},core),['0,0','0,1','0,5']);
 worlds['0,4'].fuelOverride=false;
 assert.deepEqual(M.plan(worlds,['0,0','0,5'],{jump:4,scoops:false},core),['0,0','0,3','0,5']);
 assert.deepEqual(M.plan(worlds,['0,0','0,3'],{jump:4,scoops:false},core),['0,0','0,3']);
});
function campaign(){const s=S.initial();s.initialized=true;s.bank='1000000';s.worlds={'0,0':w(),'1,0':w('1,0',1,0)};s.actual='0,0';s.route=['0,0','1,0'];s.snapshots=[{id:'s',kind:'supplier',hours:0,startedHours:0,worldId:'0,0',party:'supplier',offers:[{id:'o',commodity:'11',description:'Electronics',unitPrice:'100',quantity:'10',remaining:'10',expired:false}]}];return s;}
const lot=(id,basis='100',quantity='1',commodity='11')=>({id,quantity,basis,goodsValue:basis,commodity,description:id});
const opts={percent:75,feePercent:0,government:'4',criminal:false,taxEnabled:false};
test('decimal cargo is exact beyond floating point precision',()=>{assert.equal(A.decimal(A.add('0.1','0.2')),'0.3');assert.equal(A.decimal(A.sub('12345678901234567890.125','.125'.replace(/^\./,'0.'))),'12345678901234567890');assert.equal(A.floor('-1.1'),-2n);assert.throws(()=>A.dec('Infinity'));});
test('allocations reconcile with stable remainder',()=>{assert.deepEqual(A.allocate(5n,[{id:'b',weight:1},{id:'a',weight:1}]),[2n,3n]);assert.deepEqual(A.allocate(0n,[{id:'a',weight:0}]),[0n]);});
test('UWP transport and local codes',()=>{const c=R.context(w(),core);assert.deepEqual(c.codes,['Ht','Ri']);assert.equal(R.parseUWP('A788899-J',core).techLevel,18);assert.throws(()=>R.parseUWP('AS88899-C',core));assert.equal(R.parseUWP('A??????-?',core).population,null);assert.ok(R.tradeCodes(R.parseUWP('A??????-?',core),core).unknown.length);});
test('negative-only DM is not silently clamped',()=>{const c=R.context({...w(),uwp:'A000500-8'},core),g=core.commodities.find(g=>g.id==='15');const q=R.quote(g,c,{skill:0,side:'buy',rollTotal:10,counterparty:2},core);assert.equal(q.audit.purchase.selected,-4);assert.equal(q.audit.sale.selected,1);assert.equal(q.audit.modified,3);assert.equal(q.unitPrice,'625');});
test('local broker uses one skill plus local bonus',()=>{const q=R.quote(core.commodities[0],R.context({...w(),uwp:'A000900-C'},core),{skill:2,local:true,rollTotal:10,counterparty:2,side:'buy'},core);assert.equal(q.audit.skill,2);assert.equal(q.audit.localDM,2);assert.equal(q.audit.purchase.selected,3);});
test('price endpoint clamping',()=>{const c=R.context(w(),core);assert.equal(R.quote(core.commodities[0],c,{skill:-50,counterparty:2,rollTotal:3,side:'buy'},core).audit.percent,300);assert.equal(R.quote(core.commodities[0],c,{skill:50,counterparty:2,rollTotal:18,side:'sell'},core).audit.percent,400);});
test('small markets can have zero common goods',()=>{const c=R.context({...w(),uwp:'A000000-0'},core);const offers=R.market(c,{skill:0,counterparty:2},core,()=>1);assert.equal(offers.filter(o=>Number(o.commodity)<20).length,6);assert.ok(offers.every(o=>o.quantity==='0'));});
test('black markets retain common legal goods',()=>{const c=R.context({...w(),uwp:'A000000-C'},core);const offers=R.market(c,{illegal:true,skill:0,counterparty:2},core,()=>1);assert.ok(offers.some(o=>o.commodity==='11'));assert.ok(offers.some(o=>o.commodity==='62'));});
test('per-lot gain/loss reduction without netting',()=>{const p=R.salePreview([lot('a'),lot('b')],[{lotId:'a',quantity:'1',unitPrice:'200'},{lotId:'b',quantity:'1',unitPrice:'0'}],opts,core,mp);assert.deepEqual(p.lines.map(l=>l.adjusted),['75','-100']);assert.equal(p.bankDelta,'175');});
test('partial lot cost remainder reconciles',()=>{let lots=[lot('a','100','3')];const bases=[];for(let i=0;i<3;i++){const p=R.salePreview(lots,[{lotId:'a',quantity:'1',unitPrice:'100'}],opts,core,mp);bases.push(p.lines[0].basis);lots[0].basis=String(BigInt(lots[0].basis)-BigInt(p.lines[0].basis));lots[0].quantity=String(2-i);}assert.deepEqual(bases,['33','33','34']);});
test('tax benchmark differs from actual basis; ordering matches source case',()=>{const p=R.salePreview([lot('a','60000')],[{lotId:'a',quantity:'1',unitPrice:'80000',benchmarkPrice:'70000'}],{...opts,taxEnabled:true},core,mp);assert.equal(p.tax.amount,'800');assert.equal(p.lines[0].raw,'20000');assert.equal(p.lines[0].afterTax,'19200');assert.equal(p.lines[0].adjusted,'14400');assert.equal(p.bankDelta,'74400');});
test('one sale bracket nets taxable gains and losses',()=>{const p=R.salePreview([lot('a'),lot('b'),lot('c')],[{lotId:'a',quantity:1,unitPrice:16000,benchmarkPrice:10000},{lotId:'b',quantity:1,unitPrice:14000,benchmarkPrice:10000},{lotId:'c',quantity:1,unitPrice:8000,benchmarkPrice:10000}],{...opts,taxEnabled:true},core,mp);assert.equal(p.tax.amount,'640');assert.deepEqual(p.lines.map(l=>l.tax),['384','256','0']);});
test('tax-induced actual loss is not reduced',()=>{const p=R.salePreview([lot('a','79900')],[{lotId:'a',quantity:1,unitPrice:80000,benchmarkPrice:70000}],{...opts,taxEnabled:true},core,mp);assert.equal(p.lines[0].adjusted,'-700');assert.equal(p.lines[0].adjustment,'0');});
test('criminal market tax exemption even with manual rate',()=>{assert.equal(R.taxRate(100000,'4',true,true,mp,()=>6,50).amount,0n);});
test('fractional tax bracket and corrected boundaries',()=>{assert.equal(R.taxRate('1000.75','4',false,true,mp).amount,51n);for(const value of [75001,76000,76001])assert.equal(R.taxRate(value,'4',false,true,mp).bracket,6);assert.equal(R.taxRate(75000,'4',false,true,mp).bracket,5);assert.equal(R.taxRate('-0.1','4',false,true,mp).amount,0n);});
test('unsupported government requires manual rate',()=>{assert.throws(()=>R.taxRate(1000,'E',false,true,mp));assert.equal(R.taxRate(1000,'E',false,true,mp,()=>1,10).amount,100n);});
test('insurance example and additive once-only surcharges',()=>{const p=R.insuranceQuote(80800,70,3,['Amber'],mp);assert.equal(p.premium,'8888');assert.equal(p.potentialPayout,'56560');assert.equal(R.insuranceQuote(1000,70,3,['Amber','Amber','Red'],mp).rate,16);assert.throws(()=>R.insuranceQuote(1000,70,7,[],mp));assert.equal(R.insuranceQuote(1000,70,7,[],mp,'123').premium,'123');});
test('buy fees and insurance debit once and form cost basis',()=>{let s=campaign();s.settings.insurance=true;const policy={...R.insuranceQuote(200,70,1,[],mp),destination:'1,0',route:['0,0','1,0'],routeProgress:0};s=S.transition(s,'buy',x=>S.buy(x,{snapshotId:'s',offerId:'o',quantity:'2',feePercent:10,insurance:policy}));assert.equal(s.bank,'999764');assert.equal(s.lots[0].basis,'236');assert.equal(s.snapshots[0].offers[0].remaining,'8');const before=S.undo(s);assert.equal(before.bank,'1000000');assert.equal(before.lots.length,0);assert.equal(before.policies.length,0);});
test('claim is approved, partial, excludes taxes and rejects duplicate exhausted claims',()=>{let s=campaign();s.settings.insurance=true;s.settings.tax=true;const policy={...R.insuranceQuote(1000,70,1,[],mp),destination:'1,0',route:['0,0','1,0']};S.buy(s,{snapshotId:'s',offerId:'o',quantity:'10',insurance:policy});const id=s.policies[0].id;assert.throws(()=>S.claim(s,{policyId:id,quantity:2,reason:'Lost',approved:false}));const before=BigInt(s.bank);S.claim(s,{policyId:id,quantity:2,reason:'Pirates',approved:true});assert.equal(BigInt(s.bank)-before,140n);assert.equal(s.lots[0].quantity,'8');assert.equal(s.policies[0].remainingQuantity,'8');S.claim(s,{policyId:id,quantity:8,reason:'Lost remainder',approved:true});assert.throws(()=>S.claim(s,{policyId:id,quantity:1,reason:'Again',approved:true}));});
test('partial claim retains exact insured fraction before payout rounding',()=>{const s=campaign();s.settings.insurance=true;s.snapshots[0].offers[0].unitPrice='2.9';const policy={...R.insuranceQuote(29,70,1,[],mp),destination:'1,0',route:['0,0','1,0']};S.buy(s,{snapshotId:'s',offerId:'o',quantity:10,insurance:policy});S.claim(s,{policyId:s.policies[0].id,quantity:1,reason:'Loss',approved:true});assert.equal(s.policies[0].claims[0].payout,'3');});
test('selling ends coverage on quantity sold and sale bank reconciles',()=>{const s=campaign();s.settings.insurance=true;S.buy(s,{snapshotId:'s',offerId:'o',quantity:2,insurance:{...R.insuranceQuote(200,70,1,[],mp),destination:'1,0',route:['0,0','1,0']}});const p=R.salePreview(s.lots,[{lotId:s.lots[0].id,quantity:1,unitPrice:200}],opts,core,mp),before=BigInt(s.bank);S.sell(s,p,'0,0','buyer');assert.equal(BigInt(s.bank)-before,BigInt(p.bankDelta));assert.equal(s.policies[0].remainingQuantity,'1');});
test('purchase checks actual location, capacity, expiry and affordability',()=>{for(const mode of ['world','capacity','expired','bank']){const s=campaign();if(mode==='world')s.actual='1,0';if(mode==='capacity')s.ship.capacity='0';if(mode==='expired')s.snapshots[0].offers[0].expired=true;if(mode==='bank')s.bank='0';assert.throws(()=>S.buy(s,{snapshotId:'s',offerId:'o',quantity:1}));}});
test('freight/mail combined modifiers and mail all-or-none size',()=>{const a=R.context({...w(),uwp:'A788800-9',zone:'Amber'},core),b=R.context({...w(),uwp:'E000100-6',zone:'Red'},core);assert.equal(R.freightDM(a,b,3,3,core).total,-5);const m=R.mailOffer(a,b,3,3,{armed:true},{rank:2,soc:1},core,()=>4);assert.equal(m.audit.total,12);assert.equal(m.quantity,'20');assert.equal(m.payment,'100000');});
test('contract delivery once at destination and late penalty',()=>{const s=campaign();S.acceptContract(s,{offerId:'f',kind:'freight',origin:'0,0',destination:'1,0',quantity:'5',payment:'10000',dueHours:5});const id=s.contracts[0].id;assert.throws(()=>S.deliver(s,id,2));s.actual='1,0';s.hours=10;const bank=BigInt(s.bank);S.deliver(s,id,2);assert.equal(BigInt(s.bank)-bank,4000n);assert.equal(A.decimal(S.used(s)),'0');assert.throws(()=>S.deliver(s,id,2));});
test('opening cargo never debits bank; correction and undo preserve history',()=>{const s=campaign();const n=S.transition(s,'opening',x=>S.addLot(x,lot('a','100','0.5'),'Opening cargo',true));assert.equal(n.bank,s.bank);assert.equal(A.decimal(S.used(n)),'1');assert.equal(S.undo(n).lots.length,0);});
test('campaign round-trip and malformed imports',()=>{const s=campaign();assert.deepEqual(S.validate(JSON.parse(JSON.stringify(s))),s);const bad=campaign();bad.worlds['0,0'].id='\" onmouseover=alert(1)';assert.throws(()=>S.validate(bad));const big=campaign();big.ship.capacity='-1';assert.throws(()=>S.validate(big));});
test('world-space hex distances across negative and positive parity',()=>{assert.equal(M.distance(w('-110,-70',-110,-70),w('-111,-71',-111,-71)),1);assert.equal(M.distance(w('-110,-70',-110,-70),w('-111,-70',-111,-70)),1);assert.equal(M.distance(w('0,0',0,0),w('1,-1',1,-1)),1);});
test('fewest-jumps route, mandatory stops and unavailable fuel',()=>{const worlds=Object.fromEntries([w(),w('1,0',1,0),w('2,0',2,0),w('3,0',3,0)].map(x=>[x.id,x]));const ship={jump:2,scoops:false};assert.deepEqual(M.plan(worlds,['0,0','3,0'],ship,core),['0,0','2,0','3,0']);assert.deepEqual(M.plan(worlds,['0,0','1,0','3,0'],ship,core),['0,0','1,0','3,0']);assert.deepEqual(M.plan(worlds,['0,0','2,0','3,0'],ship,core),['0,0','2,0','3,0']);worlds['3,0'].fuelOverride=false;assert.throws(()=>M.plan(worlds,['0,0','3,0'],ship,core));});

test('insure held cargo charges only premium, blocks overlapping policies, and undoes atomically',()=>{
 const s=campaign();s.lots=[lot('held','1000','2')];const q={...R.insuranceQuote('1000',70,1,['Red'],mp),route:['0,0','1,0'],destination:'1,0',routeProgress:0};
 const after=S.transition(s,'Insure existing cargo',n=>S.insureLot(n,'held',q));
 assert.equal(after.lots[0].quantity,'2');assert.equal(after.lots[0].goodsValue,'1000');assert.equal(BigInt(after.bank),BigInt(s.bank)-BigInt(q.premium));assert.equal(BigInt(after.lots[0].basis),1000n+BigInt(q.premium));assert.equal(after.policies.length,1);
 assert.throws(()=>S.insureLot(after,'held',q),/already has coverage/);const undone=S.undo(after);assert.equal(undone.bank,s.bank);assert.equal(undone.lots[0].basis,'1000');assert.equal(undone.policies.length,0);
 const poor=campaign();poor.lots=[lot('held','1000','2')];poor.bank='0';assert.throws(()=>S.insureLot(poor,'held',q),/Insufficient/);assert.equal(poor.policies.length,0);
});

