import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {join} from 'node:path';
const artifacts=fileURLToPath(new URL('../verification-artifacts/',import.meta.url));
await mkdir(artifacts,{recursive:true});
const {chromium}=createRequire(import.meta.url)(process.argv[2]||'playwright');
const base=process.env.TRAVELLER_TEST_URL||'http://127.0.0.1:8765/';
const browser=await chromium.launch({headless:true,...(process.env.TRAVELLER_BROWSER_CHANNEL?{channel:process.env.TRAVELLER_BROWSER_CHANNEL}:{})});
const ctx=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});
const sample=[{Name:'Regina',Hex:'1910',UWP:'A788899-C',PBG:'703',Zone:'',WorldX:-110,WorldY:-70,Sector:'Spinward Marches'},{Name:'Jenghe',Hex:'1810',UWP:'C799663-9',PBG:'323',Zone:'',WorldX:-111,WorldY:-70,Sector:'Spinward Marches'},{Name:'Ruie',Hex:'1809',UWP:'C776977-7',PBG:'701',Zone:'A',WorldX:-111,WorldY:-71,Sector:'Spinward Marches'}];
await ctx.route('https://travellermap.com/api/jumpworlds?*',async route=>{const u=new URL(route.request().url());const rows=u.searchParams.get('jump')==='0'?sample.filter(w=>w.Hex===(u.searchParams.get('hex')||'1910')):sample;await route.fulfill({json:{Worlds:rows},headers:{'Access-Control-Allow-Origin':'*'}});});
await ctx.route('https://travellermap.com/api/universe?*',route=>route.fulfill({json:{Sectors:[{Names:[{Text:'Spinward Marches'}],Abbreviation:'Spin'},{Names:[{Text:'Empty Sector'}]}]}}));
await ctx.route('https://travellermap.com/api/metadata?*',route=>route.fulfill({json:{Subsectors:[{Index:'C',Name:'Regina'},{Index:'A',Name:'Cronor'}]}}));
await ctx.route('https://travellermap.com/api/sec?*',route=>route.fulfill({json:'Hex\tName\r\n'+sample.map(w=>w.Hex+'\t'+w.Name).join('\r\n')}));
const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const click=async label=>{const modal=page.locator('#modal[open]');const target=modal.getByRole('button',{name:label,exact:true});if(await target.count())return target.click();return page.getByRole('button',{name:label,exact:true}).click();};
const fill=(name,value)=>page.locator('[name="'+name+'"]').fill(String(value));
const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('traveller-trade-route-calculator:v1')));
const closed=()=>page.locator('#modal').waitFor({state:'hidden'});
try{
 await page.goto(base);await page.getByText('Editing in this tab',{exact:true}).waitFor();
 await click('Set up campaign');await page.locator('#setup-world .picker-selection').getByText(/Hex 1910/).waitFor();await fill('bank','1000000');await click('Start campaign');await closed();
 assert.equal((await read()).bank,'1000000');
 await click('Find supplier');await fill('dice',12);await click('Preview search');await click('Commit search');await closed();
 assert.ok((await read()).snapshots[0].offers.length>=6);
 assert.deepEqual(await page.locator('.purchase-table th').allTextContents(),['Commodity','Available','Retail','Price %','Purchase Price','Offer Status','Actions']);
 const assertGrid=async selector=>{const cells=await page.locator(selector).evaluate(table=>[...table.querySelectorAll('thead th')].map((h,i)=>{const d=table.querySelector('tbody tr').children[i],a=h.getBoundingClientRect(),b=d.getBoundingClientRect();return {left:Math.abs(a.left-b.left),width:Math.abs(a.width-b.width),align:getComputedStyle(h).textAlign,cellAlign:getComputedStyle(d).textAlign};}));assert.ok(cells.every(c=>c.left<1&&c.width<1));assert.ok(cells.slice(1,5).every(c=>c.align==='right'&&c.cellAlign==='right'));};
 await assertGrid('.purchase-table');
 const initialOffer=(await read()).snapshots[0].offers[0];
 assert.equal(await page.locator('.purchase-table tbody tr').first().locator('td').nth(3).textContent(),initialOffer.audit.percent+'%');
 await page.screenshot({path:join(artifacts,'purchase-table.png'),fullPage:true});
 const offerId=(await read()).snapshots[0].offers[0].id;await page.locator('[data-expire="'+offerId+'"]').click();assert.equal((await read()).snapshots[0].offers.filter(o=>o.expired).length,1);await page.locator('#market-filter').selectOption('all');const expired=page.locator('.expired-row');assert.equal(await expired.getByRole('button',{name:'Buy',exact:true}).isDisabled(),true);assert.equal(await expired.getByRole('button',{name:'Audit',exact:true}).isEnabled(),true);await expired.getByRole('button',{name:'Audit',exact:true}).click();await page.getByRole('heading',{name:/Commodity audit/}).waitFor();await click('Close');await page.locator('[data-expire="'+offerId+'"]').click();assert.equal((await read()).snapshots[0].offers.filter(o=>o.expired).length,0);
 await page.getByRole('button',{name:'Buy',exact:true}).first().click();
 assert.equal(await page.getByRole('group',{name:'Optional',exact:true}).count(),1);
 assert.equal(await page.locator('[name="purchaseTax"]').count(),0);assert.equal(await page.locator('[name="insure"]').isChecked(),false);
 await page.locator('[name="insure"]').check();assert.equal(await page.locator('#purchase-insurance-options').isVisible(),true);await page.locator('[name="insure"]').uncheck();
 await fill('quantity','0.5');await click('Preview purchase');
 await click('Cancel');assert.equal((await read()).settings.tax,false);assert.equal((await read()).lots.length,0);
 await page.getByRole('button',{name:'Buy',exact:true}).first().click();await page.screenshot({path:join(artifacts,'purchase-optional.png')});await fill('quantity','0.5');await click('Preview purchase');await click('COMMIT PURCHASE');await closed();
 let saved=await read();assert.equal(saved.settings.tax,false);assert.equal(saved.settings.insurance,false);assert.equal(saved.lots[0].quantity,'0.5');const afterBuy=saved.bank;
 assert.deepEqual(await page.locator('.cargo-table th').allTextContents(),['Commodity','Tons Held','Retail','Price %','Sale Price','Lot / Description','Actions']);
 await assertGrid('.cargo-table');assert.match(await page.locator('.cargo-table tbody').textContent(),/Not negotiated/);
 await page.locator('.cargo-table [data-action="lot-correct"]').first().click();await fill('description','Independent cargo lot');await fill('reason','Table edit verification');await click('Save');await closed();assert.equal((await read()).lots[0].description,'Independent cargo lot');
 // Browsing a real map node changes neither location nor economic state.
 await page.locator('svg [data-arg="-111,-70"]').click();assert.equal((await read()).actual,'-110,-70');assert.equal((await read()).bank,afterBuy);
 await click('Current ship');await page.locator('[data-lot]').first().check();await click('Preview sale');
 await fill('dice',12);await click('Preview search');await click('Commit search');
 await page.getByRole('heading',{name:/Prepare sale/}).waitFor();
 const saleLot=(await read()).lots[0],quotedPrice=await page.locator('[name="price_'+saleLot.id+'"]').inputValue();
 assert.equal(await page.locator('.cargo-table tbody tr td').nth(4).textContent(),'Cr '+quotedPrice.replace(/\B(?=(\d{3})+(?!\d))/g,',')+' / t');
 assert.match(await page.locator('.cargo-table tbody tr td').nth(3).textContent(),/^\d+%$/);
 await click('Cancel');await page.locator('.cargo-table [data-action="lot-audit"]').first().click();assert.match(await page.locator('#modal-body').textContent(),/saleQuote/);assert.match(await page.locator('#modal-body').textContent(),/tableResult/);await click('Close');
 const displayedQuote=await page.locator('.cargo-table tbody tr td').nth(4).textContent();await click('Cargo');assert.equal(await page.locator('.cargo-table tbody tr td').nth(4).textContent(),displayedQuote);
 await page.locator('.cargo-table [data-action="lot-sell"]').first().click();await click('Negotiate sale');await click('Preview sale');await page.getByRole('heading',{name:'Confirm sale'}).waitFor();await click('COMMIT SALE');await closed();assert.equal((await read()).lots.length,0);
 await click('History');await click('Undo latest change');assert.equal((await read()).lots.length,1);
 await click('Overview');await click('Plot route');await page.locator('#route-destination').getByLabel('Subsector',{exact:true}).selectOption('C');await page.locator('#route-destination').getByLabel('World',{exact:true}).selectOption('1810');await click('Calculate route');await click('Save route');await closed();assert.equal((await read()).route.length,2);
 await click('Settings');await click('Ship, trader & options');await page.locator('[name="insurance"]').uncheck();await page.locator('[name="tax"]').check();await click('Save');await closed();
 await click('Overview');await page.getByRole('button',{name:'Buy',exact:true}).first().click();await fill('quantity','1');await page.locator('[name="insure"]').check();await click('Preview purchase');await click('COMMIT PURCHASE');await closed();assert.equal((await read()).policies.length,1);assert.equal((await read()).settings.insurance,true);
 await click('Cargo');await click('Loss / claim');await fill('quantity','0.25');await fill('reason','Referee-confirmed partial loss');await page.locator('[name="approved"]').check();await click('Preview claim');await click('Commit loss & claim');await closed();assert.equal((await read()).policies[0].remainingQuantity,'0.75');
 await click('Contracts');await click('Find contracts');await fill('dice',12);await page.getByText('Override freight / mail dice',{exact:true}).click();await fill('diceSequence',Array(300).fill(6).join(','));await click('Generate offers');await closed();
 const freight=page.locator('.freight-table').first();assert.deepEqual(await freight.locator('th').allTextContents(),['Freight Lot / Description','Tons','Destination','Rate / ton','Total Revenue','Due / Delivery Date','Status','Actions']);
 await freight.getByRole('button',{name:'Edit',exact:true}).first().click();await fill('description','Referee freight lot');await fill('quantity','0.5');await fill('payment','900');await fill('due','');await fill('reason','Freight table edit');await click('Save');await closed();
 assert.match(await freight.locator('tbody tr').first().textContent(),/Referee freight lot/);assert.match(await freight.locator('tbody tr').first().textContent(),/No due date/);
 await freight.getByRole('button',{name:'Audit/View',exact:true}).first().click();assert.match(await page.locator('#modal-body').textContent(),/Freight table edit/);await click('Close');
 await page.screenshot({path:join(artifacts,'freight-table.png'),fullPage:true});
 await freight.getByRole('button',{name:'Accept',exact:true}).first().click();await click('Accept whole contract');await closed();assert.equal((await read()).contracts.at(-1).description,'Referee freight lot');
 await click('History');await click('Undo latest change');assert.equal((await read()).contracts.length,0);
 await click('Contracts');await click('Manual contract');await page.locator('[name="destination"]').selectOption('-111,-70');await fill('quantity','1');await fill('payment','1000');await fill('days','0');await fill('reason','Browser verification delivery');await click('Save');await closed();
 await click('Overview');await click('COMMIT JUMP → Jenghe');await fill('hours','160');await click('COMMIT JUMP');await closed();assert.equal((await read()).actual,'-111,-70');assert.equal((await read()).policies[0].status,'arrived');
 await click('Contracts');const beforeDelivery=BigInt((await read()).bank);await click('Deliver');await fill('die','2');await click('Commit delivery & payout');await closed();assert.equal(BigInt((await read()).bank)-beforeDelivery,400n);
 await click('Overview');
 // A second tab cannot overwrite state, and explicit transfer hands off the lock.
 await click('Accounts');await click('Record expense');await fill('amount','1');await fill('reason','Stale preview must not commit');
 const second=await ctx.newPage();await second.goto(base);await second.getByText('Read-only: campaign open in another tab.',{exact:true}).waitFor();
 assert.equal(await second.getByRole('button',{name:'Find supplier',exact:true}).isDisabled(),true);
 await second.getByRole('button',{name:'Take over editing',exact:true}).click();await second.getByText('Editing in this tab',{exact:true}).waitFor();await page.getByText('Read-only: editing transferred to another tab.',{exact:true}).waitFor();
 await second.getByRole('button',{name:'Accounts',exact:true}).click();await second.getByRole('button',{name:'Record expense',exact:true}).click();await second.locator('[name="amount"]').fill('2');await second.locator('[name="reason"]').fill('Second-tab change');await second.locator('#modal-submit').click();await second.locator('#modal').waitFor({state:'hidden'});
 const bankAfterOtherTab=(await read()).bank;await click('Save');await page.locator('#modal-error').getByText(/Campaign changed/).waitFor();assert.equal((await read()).bank,bankAfterOtherTab);await click('Cancel');
 await second.close();await page.getByRole('button',{name:'Take over editing',exact:true}).click();await page.getByText('Editing in this tab',{exact:true}).waitFor();
 // Long-list layout and safe import/export round-trip use a valid expanded campaign fixture.
 let many=await read();const seed=many.lots[0];many.lots=Array.from({length:15},(_,i)=>({...seed,id:'fixture-'+i,quantity:'0.5',basis:String(100+i),goodsValue:'100',description:'Fixture cargo '+(i+1)}));many.policies=[];many.undo=[];many.revision++;
 await page.evaluate(s=>localStorage.setItem('traveller-trade-route-calculator:v1',JSON.stringify(s)),many);await page.reload();await page.getByText('Editing in this tab',{exact:true}).waitFor();
 await click('Cargo');assert.equal(await page.locator('[data-lot]').count(),15);assert.match(await page.locator('.cargo-table tbody').textContent(),/Cost basis: Cr 114/);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:join(artifacts,'mobile-preview.png'),fullPage:true});
 assert.ok(await page.locator('body').evaluate(e=>e.scrollWidth)<=410);
 await page.setViewportSize({width:1440,height:1100});await click('Overview');await page.screenshot({path:join(artifacts,'desktop-preview.png'),fullPage:true});
 await click('Settings');const downloadPromise=page.waitForEvent('download');await click('Export backup');const download=await downloadPromise;assert.ok(download.suggestedFilename().endsWith('.json'));
 await click('Reset campaign');await click('Cancel');assert.equal((await read()).lots.length,15);
 const beforeBadImport=(await read()).bank;await page.locator('#import-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{broken')});await page.locator('#message.error').waitFor();assert.equal((await read()).bank,beforeBadImport);
 const restore=await read();await page.locator('#import-file').setInputFiles({name:'restore.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(restore))});await page.getByRole('heading',{name:'Import campaign'}).waitFor();await page.locator('[name="backed"]').check();await click('Replace campaign');await closed();assert.equal((await read()).lots.length,15);
 // A failed browser save must leave the prior stored campaign intact.
 await click('Accounts');await click('Record expense');await fill('amount','3');await fill('reason','Quota failure check');const bankBeforeFailure=(await read()).bank;
 await page.evaluate(()=>{window.savedSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw new DOMException('Storage full','QuotaExceededError');};});await click('Save');await page.locator('#modal-error').getByText('Storage full',{exact:true}).waitFor();assert.equal((await read()).bank,bankBeforeFailure);await page.evaluate(()=>{Storage.prototype.setItem=window.savedSetItem;});await click('Cancel');
 await page.locator('#notes').click();await page.getByRole('heading',{name:'INT-018 · Criminal-market exemption'}).waitFor();await click('Close');
 const recoveryCopy=await read();await page.evaluate(()=>localStorage.setItem('traveller-trade-route-calculator:v1','{corrupt'));await page.reload();await page.getByRole('heading',{name:'Recover saved campaign'}).waitFor();assert.equal(await page.evaluate(()=>localStorage.getItem('traveller-trade-route-calculator:v1')),'{corrupt');await page.locator('#import-file').setInputFiles({name:'recovery.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(recoveryCopy))});await page.getByRole('heading',{name:'Import campaign'}).waitFor();await page.locator('[name="backed"]').check();await click('Replace campaign');await closed();assert.equal((await read()).lots.length,15);
 assert.deepEqual(errors,[]);console.log('PASS: browser purchase/sale/undo, browsing, route/jump, insurance/partial claim, late freight delivery, two-tab transfer/stale preview, 15 cargo rows, mobile layout, backup/import/reset cancellation, quota failure and notes. API responses stubbed from live sample.');
}finally{await browser.close();}
