import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir,readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {join} from 'node:path';
const artifacts=fileURLToPath(new URL('../verification-artifacts/',import.meta.url));
await mkdir(artifacts,{recursive:true});
const {chromium}=createRequire(import.meta.url)(process.argv[2]||'playwright');
const base=process.env.TRAVELLER_TEST_URL||'http://127.0.0.1:8765/';
const browser=await chromium.launch({headless:true,...(process.env.TRAVELLER_BROWSER_CHANNEL?{channel:process.env.TRAVELLER_BROWSER_CHANNEL}:{})});
const ctx=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});
const sample=[{Name:'Regina',Hex:'1910',UWP:'A788899-C',PBG:'703',Zone:'',WorldX:-110,WorldY:-70,Sector:'Spinward Marches'},{Name:'Jenghe',Hex:'1810',UWP:'C799663-9',PBG:'323',Zone:'',WorldX:-111,WorldY:-70,Sector:'Spinward Marches'},{Name:'Ruie',Hex:'1809',UWP:'C776977-7',PBG:'701',Zone:'A',WorldX:-112,WorldY:-70,Sector:'Spinward Marches'}];
await ctx.route('https://travellermap.com/api/jumpworlds?*',async route=>{const u=new URL(route.request().url());const rows=u.searchParams.get('jump')==='0'?sample.filter(w=>w.Hex===(u.searchParams.get('hex')||'1910')):sample;await route.fulfill({json:{Worlds:rows},headers:{'Access-Control-Allow-Origin':'*'}});});
await ctx.route('https://travellermap.com/api/universe?*',route=>route.fulfill({json:{Sectors:[{Names:[{Text:'Spinward Marches'}],Abbreviation:'Spin'},{Names:[{Text:'Empty Sector'}]}]}}));
await ctx.route('https://travellermap.com/api/metadata?*',route=>route.fulfill({json:{Subsectors:[{Index:'C',Name:'Regina'},{Index:'A',Name:'Cronor'}]}}));
await ctx.route('https://travellermap.com/api/sec?*',route=>route.fulfill({json:'Hex\tName\r\n'+sample.map(w=>w.Hex+'\t'+w.Name).join('\r\n')}));
const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const click=async label=>{const modal=page.locator('#modal[open]');const target=modal.getByRole('button',{name:label,exact:true});if(await target.count())return target.click();return page.getByRole('button',{name:label,exact:true}).click();};
const fill=(name,value)=>page.locator('[name="'+name+'"]').fill(String(value));
const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('traveller-trade-route-calculator:v1')));
const closed=()=>page.locator('#modal').waitFor({state:'hidden'});
const choose=id=>page.locator('svg [data-action="map-world"][data-arg="'+id+'"]').click();
const ready=()=>page.getByRole('button',{name:'Save planned route',exact:true}).waitFor({state:'visible'}).then(()=>page.waitForFunction(()=>!document.querySelector('[data-action="route-save"]').disabled));
try{
 await page.goto(base);await page.getByText('Editing in this tab',{exact:true}).waitFor();await click('Set up campaign');await page.locator('#setup-world .picker-selection').getByText(/Hex 1910/).waitFor();
 await fill('rooms-high',1);await fill('rooms-middle',6);await fill('people-middle',4);await fill('people-high',2);assert.equal(await page.getByLabel('How many passengers — Middle?',{exact:true}).inputValue(),'4');assert.equal(await page.getByLabel('How many passengers — High?',{exact:true}).inputValue(),'2');await fill('supportRemaining',14);
 assert.equal(await page.locator('[name="passengers-high"]').count(),0);assert.equal(await page.locator('[name="crew-high"]').count(),0);
 await page.locator('#accommodation-estimate').getByText(/7 total cabins \(0 low, 6 middle, 1 high\) · 6 total people/).waitFor();
 await click('Start campaign');await closed();const opening=await read();assert.match(await page.locator('.life-support-counter').textContent(),/14 days remaining/);assert.equal(await page.locator('.life-support-counter progress').getAttribute('value'),'336');await click('Refill life support');await page.getByText(/Cr 8,500/).waitFor();await click('Pay & refill');await closed();assert.equal((await read()).ship.lifeSupport.remainingHours,672);assert.match(await page.locator('.life-support-counter').textContent(),/28 days remaining/);assert.equal((await read()).bank,'91500');await click('Refill life support');await page.getByText('Life support is full',{exact:true}).waitFor();await click('Close');const before=await read();assert.equal(before.ship.staterooms,7);assert.equal(before.ship.accommodation.luggageTons,'2');
 await click('Settings');await click('Ship, trader & options');assert.equal(await page.locator('[name="people-middle"]').inputValue(),'4');await fill('people-high',0);await fill('people-middle',0);await click('Save');await closed();
 const empty=await read();assert.equal(empty.ship.staterooms,7);assert.equal(empty.ship.accommodation.rooms.high,1);assert.equal(empty.ship.accommodation.luggageTons,'0');assert.equal(empty.bank,before.bank);
 await click('Ship expenses');await page.locator('[name="include-berthing"]').uncheck();await page.locator('[name="include-staterooms"]').check();await page.locator('[name="stateroomsPeriod"]').selectOption('month');
 await page.locator('#expense-estimate').getByText(/7,000/).first().waitFor();await click('Cancel');assert.equal((await read()).bank,before.bank);
 await click('Ship, trader & options');await page.getByText('Cabin charges — rules & campaign assumptions',{exact:true}).click();await page.getByText(/High Guard Update 2022, p. 51/).waitFor();await page.setViewportSize({width:390,height:844});assert.ok(await page.locator('body').evaluate(e=>e.scrollWidth)<=410);
 await page.screenshot({path:join(artifacts,'combined-cabins-mobile.png'),fullPage:true});assert.deepEqual(errors,[]);console.log('PASS: combined cabin/headcount fields, save and reload, empty high cabin charge, luggage preservation, rules note and mobile layout');
}finally{await browser.close();}
