import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir,readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {join} from 'node:path';
const artifacts=fileURLToPath(new URL('../verification-artifacts/',import.meta.url));
await mkdir(artifacts,{recursive:true});
const {chromium}=createRequire(import.meta.url)(process.argv[2]||'playwright');
const base=process.env.TRAVELLER_TEST_URL||'http://127.0.0.1:8765/';
const browser=await chromium.launch({headless:true,...(process.env.TRAVELLER_BROWSER_CHANNEL?{channel:process.env.TRAVELLER_BROWSER_CHANNEL}:{})});
const ctx=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});
const sample=[{Name:'Regina',Hex:'1910',UWP:'A788899-C',PBG:'703',Zone:'',WorldX:-110,WorldY:-70,Sector:'Spinward Marches'},{Name:'Jenghe',Hex:'1810',UWP:'C799663-9',PBG:'323',Zone:'',WorldX:-111,WorldY:-70,Sector:'Spinward Marches'},{Name:'Ruie',Hex:'1809',UWP:'C776977-7',PBG:'701',Zone:'A',WorldX:-112,WorldY:-70,Sector:'Spinward Marches'}];
await ctx.route('https://travellermap.com/api/jumpworlds?*',async route=>{const u=new URL(route.request().url());const rows=u.searchParams.get('jump')==='0'?sample.filter(w=>w.Hex===(u.searchParams.get('hex')||'1910')):sample;await route.fulfill({json:{Worlds:rows},headers:{'Access-Control-Allow-Origin':'*'}});});
await ctx.route('https://travellermap.com/api/universe?*',route=>route.fulfill({json:{Sectors:[{Names:[{Text:'Spinward Marches'}],Abbreviation:'Spin'},{Names:[{Text:'Empty Sector'}]}]}}));
await ctx.route('https://travellermap.com/api/metadata?*',route=>route.fulfill({json:{Subsectors:[{Index:'C',Name:'Regina'},{Index:'A',Name:'Cronor'}]}}));
await ctx.route('https://travellermap.com/api/sec?*',route=>route.fulfill({json:'Hex\tName\r\n'+sample.map(w=>w.Hex+'\t'+w.Name).join('\r\n')}));
const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const click=async label=>{const modal=page.locator('#modal[open]');const target=modal.getByRole('button',{name:label,exact:true});if(await target.count())return target.click();return page.getByRole('button',{name:label,exact:true}).click();};
const fill=(name,value)=>page.locator('[name="'+name+'"]').fill(String(value));
const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('traveller-trade-route-calculator:v1')));
const closed=()=>page.locator('#modal').waitFor({state:'hidden'});
const choose=id=>page.locator('svg [data-action="map-world"][data-arg="'+id+'"]').click();
const ready=()=>page.getByRole('button',{name:'Save planned route',exact:true}).waitFor({state:'visible'}).then(()=>page.waitForFunction(()=>!document.querySelector('[data-action="route-save"]').disabled));
const units=s=>Number(s.ship.lifeSupport.stockUnits.numerator)/Number(s.ship.lifeSupport.stockUnits.denominator);
const overview=()=>page.locator('#tabs [data-arg="Overview"]').click();
const undo=async()=>{await click('History');await click('Undo latest change');await overview();};
try{
 await page.goto(base);await page.getByText('Editing in this tab',{exact:true}).waitFor();assert.equal(await page.locator('[data-action="day-forward"]').count(),0);
 await click('Set up campaign');await page.locator('#setup-world .picker-selection').getByText(/Hex 1910/).waitFor();await fill('shipTons',200);await fill('fuelCapacity',40);await fill('fuelAboard',20);await fill('rooms-middle',1);await fill('people-middle',1);await click('Start campaign');await closed();
 const back=page.locator('[data-action="day-back"]'),forward=page.locator('[data-action="day-forward"]');assert.equal(await back.isDisabled(),true);
 await page.evaluate(()=>{const k='traveller-trade-route-calculator:v1',s=JSON.parse(localStorage.getItem(k));s.dateLabel='365-1105';s.ship.lifeSupport={capacityHours:672,remainingHours:48};localStorage.setItem(k,JSON.stringify(s));});
 await page.reload();await page.getByText('Editing in this tab',{exact:true}).waitFor();const initial=await read();
 await forward.click();let s=await read();assert.equal(s.hours,24);assert.equal(units(s),1);assert.match(await page.locator('.campaign-time').textContent(),/001-1106/);assert.equal(s.bank,initial.bank);assert.deepEqual(s.ledger,initial.ledger);assert.deepEqual(s.lots,initial.lots);
 await click('History');assert.match(await page.locator('.action-history').textContent(),/Time advanced \+1 day/);await click('Undo latest change');await overview();s=await read();assert.equal(s.hours,0);assert.deepEqual(s.ship.lifeSupport,initial.ship.lifeSupport,'Undo restores the original legacy representation');
 await forward.click();await back.click();s=await read();assert.equal(s.hours,0);assert.equal(units(s),1);assert.equal(await back.isDisabled(),true);await click('History');assert.match(await page.locator('.action-history').textContent(),/supplies and transactions unchanged/);await overview();
 await undo();s=await read();assert.equal(s.hours,24);assert.equal(units(s),1);await forward.click();s=await read();assert.equal(s.hours,48);assert.equal(units(s),0);
 await page.reload();await page.getByText('Editing in this tab',{exact:true}).waitFor();assert.equal((await read()).hours,48);assert.equal(units(await read()),0);
 const other=await ctx.newPage();await other.goto(base);await other.getByText('Read-only: campaign open in another tab.',{exact:true}).waitFor();assert.equal(await other.locator('[data-action="day-forward"]').isDisabled(),true);assert.equal(await other.locator('[data-action="day-back"]').isDisabled(),true);await other.close();
 await page.evaluate(()=>{const k='traveller-trade-route-calculator:v1',s=JSON.parse(localStorage.getItem(k));s.hours=23;delete s.ship.lifeSupport;localStorage.setItem(k,JSON.stringify(s));});await page.reload();await page.getByText('Editing in this tab',{exact:true}).waitFor();assert.equal(await back.isDisabled(),true);await forward.click();assert.equal((await read()).hours,47);assert.equal((await read()).ship.lifeSupport,undefined);await back.click();assert.equal((await read()).hours,23);
 await page.evaluate(()=>{const k='traveller-trade-route-calculator:v1',s=JSON.parse(localStorage.getItem(k));s.ship.lifeSupport={capacityHours:672,remainingHours:672,elapsedHours:6};localStorage.setItem(k,JSON.stringify(s));});await page.reload();await page.getByText('Editing in this tab',{exact:true}).waitFor();
 await click('Settings');await click('Ship, trader & options');assert.equal(await page.locator('[name="supportRemaining"]').inputValue(),'27.75');assert.equal(await page.locator('[name="supportRemaining"]').getAttribute('step'),'any');await click('Save');await closed();assert.equal(units(await read()),27.75,'Unrelated settings preserve exact partly consumed supplies');
 await overview();const beforeRefill=await read();await click('Refill life support');assert.match(await page.locator('#service-panel').textContent(),/Cr 18/);await page.locator('[data-action="service-confirm"]').click();await page.locator('#service-panel').waitFor({state:'hidden'});const refilled=await read();assert.equal(refilled.hours,beforeRefill.hours);assert.equal(units(refilled),28);assert.equal(BigInt(beforeRefill.bank)-BigInt(refilled.bank),18n,'A quarter-day missing stock uses exact billing, rounded once to Credits');
 await undo();assert.deepEqual((await read()).ship.lifeSupport,beforeRefill.ship.lifeSupport);assert.equal((await read()).bank,beforeRefill.bank);
 await page.setViewportSize({width:390,height:844});assert.ok(await page.locator('body').evaluate(e=>e.scrollWidth)<=410);await page.screenshot({path:join(artifacts,'day-controls-mobile.png')});assert.deepEqual(errors,[]);
 console.log('PASS: daily controls, year rollover, start boundary, exact LSS depletion, Undo/legacy preservation, read-only tabs, partial-day refill and mobile layout.');
}finally{await browser.close();}
