import {plan} from '../js/map.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import * as S from '../js/state.mjs';
import {jumpFuel,consumeJumpFuel,validateFuel,configureFuel,bladderSpace} from '../js/fuel.mjs';
function campaign(){const s=S.initial();s.initialized=true;s.actual='0,0';s.bank='100000';s.worlds={'0,0':{id:'0,0',x:0,y:0,hex:'0101',sector:'Test',name:'Port',uwp:'A788899-C',zone:'Safe'}};s.route=['0,0'];s.ship.fuel={displacementTons:200,capacityTons:40,aboardTons:10};return s;}
test('fuel uses actual parsecs and total hull, rounds up, and enforces rating',()=>{const s=campaign();assert.equal(jumpFuel(s.ship,1).tons,20);assert.equal(jumpFuel(s.ship,2).tons,40);assert.equal(jumpFuel(s.ship,0).tons,20);s.ship.fuel.displacementTons=201;assert.equal(jumpFuel(s.ship,1).tons,21);assert.equal(jumpFuel(s.ship,2).tons,41);assert.throws(()=>jumpFuel(s.ship,3));});
test('fuel purchases and collections change tank and bank atomically; undo restores both',()=>{const s=campaign();const p=S.transition(s,'Refuel',n=>S.shipExpenses(n,[{kind:'fuel',tons:10,fuelType:'refined',fuelShip:{fuel:{capacityTons:999}}}]));assert.equal(p.ship.fuel.aboardTons,20);assert.equal(p.bank,'95000');assert.equal(S.undo(p).ship.fuel.aboardTons,10);assert.equal(S.undo(p).bank,'100000');assert.match(JSON.stringify(p.ledger[0].expense.details),/Fuel aboard after/);const w=S.transition(p,'Collect',n=>S.shipExpenses(n,[{kind:'fuel',tons:20,fuelType:'water'}]));assert.equal(w.ship.fuel.aboardTons,40);assert.equal(w.bank,p.bank);assert.deepEqual(S.validate(JSON.parse(JSON.stringify(w))),w);});
test('invalid or unaffordable refuelling leaves the entire expense batch unchanged',()=>{for(const [tons,bank]of [[31,'100000'],[10,'1']]){const s=campaign();s.bank=bank;const before=structuredClone(s);assert.throws(()=>S.shipExpenses(s,[{kind:'salary',monthly:1,months:1},{kind:'fuel',fuelType:'refined',tons}]));assert.deepEqual(s,before);}});
test('jump consumption is preview-only until committed, records insufficient fuel and undoes',()=>{const s=campaign(),before=structuredClone(s);jumpFuel(s.ship,1);assert.deepEqual(s,before);const low=S.transition(s,'Jump',n=>{const q=consumeJumpFuel(n.ship,1);assert.equal(q.shortfall,10);assert.equal(q.consumed,10);});assert.equal(low.ship.fuel.aboardTons,0);assert.equal(S.undo(low).ship.fuel.aboardTons,10);assert.deepEqual(s,before);s.ship.fuel.aboardTons=40;const next=S.transition(s,'Jump',n=>{consumeJumpFuel(n.ship,2);n.hours+=168;});assert.equal(next.ship.fuel.aboardTons,0);assert.equal(next.bank,s.bank);assert.equal(S.undo(next).ship.fuel.aboardTons,40);});
test('legacy campaigns remain valid without guessed stock; invalid imported tank fields rejected',()=>{const s=campaign();delete s.ship.fuel;assert.equal(jumpFuel(s.ship,2),null);S.validate(s);for(const fuel of [{displacementTons:0,capacityTons:40,aboardTons:0},{displacementTons:200,capacityTons:40,aboardTons:41},{displacementTons:200,capacityTons:201,aboardTons:0},{displacementTons:200,capacityTons:40,aboardTons:0.5}])assert.throws(()=>validateFuel({fuel}));});

test('bladders reserve only fuel carried and respect hull and drive limits',()=>{const s=campaign();s.ship.capacity='150';s.ship.fuel=configureFuel(200,40,40,3,2);assert.equal(s.ship.fuel.capacityTons,160);assert.equal(bladderSpace(s.ship),0);assert.equal(String(S.used(s).n), '0');S.validate(s);assert.equal(jumpFuel(s.ship,1).tons,20);assert.throws(()=>jumpFuel(s.ship,3));assert.throws(()=>configureFuel(200,40,100,0,2));assert.throws(()=>configureFuel(200,40,40,1.5,2));s.ship.capacity='60';S.validate(s);s.ship.fuel.aboardTons=160;assert.equal(bladderSpace(s.ship),120);assert.throws(()=>S.validate(s),/exceed.*capacity/);});

test('route planning permits unavailable and empty stops but never exceeds drive range',()=>{const a={id:'0,0',x:0,y:0,name:'Start',fuelOverride:false},b={id:'0,2',x:0,y:2,name:'Empty',emptySpace:true},c={id:'0,4',x:0,y:4,name:'End',fuelOverride:false};assert.deepEqual(plan({'0,0':a,'0,2':b,'0,4':c},[a.id,c.id],{jump:2},{}),[a.id,b.id,c.id]);assert.throws(()=>plan({'0,0':a,'0,4':c},[a.id,c.id],{jump:2},{}),/No valid connection/);});

test('bladder cargo follows refuelling, jumps, undo and imported stock',()=>{const s=campaign();s.ship.capacity='25';s.ship.fuel=configureFuel(200,40,0,2,2);assert.equal(bladderSpace(s.ship),0);s.ship.fuel.aboardTons=40;const loaded=S.transition(s,'Refuel',n=>S.shipExpenses(n,[{kind:'fuel',tons:20,fuelType:'water'}]));assert.equal(bladderSpace(loaded.ship),20);assert.equal(bladderSpace(S.undo(loaded).ship),0);const before=structuredClone(loaded);assert.throws(()=>S.shipExpenses(loaded,[{kind:'fuel',tons:10,fuelType:'water'}]),/exceed.*capacity/);assert.deepEqual(loaded,before);const jumped=S.transition(loaded,'Jump',n=>consumeJumpFuel(n.ship,1));assert.equal(bladderSpace(jumped.ship),0);assert.equal(bladderSpace(S.undo(jumped).ship),20);assert.equal(bladderSpace(S.validate(JSON.parse(JSON.stringify(before))).ship),20);});
