// Exact-head actual Chromium regression gate for campaign import/reset.
// Run: node verification/replacement-completion-browser.test.mjs [playwright-module]
// --fixtures-only checks exact synthetic fixtures and source wiring without Chromium.
// Real app handlers, native localStorage, versioned Store and Web Locks execute
// unchanged. Only replacement completion and File.text timing are test-owned.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir,readFile,readdir,stat,writeFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {join} from 'node:path';
import * as S from '../js/state.mjs';
import {configureFuel} from '../js/fuel.mjs';
import {createDashboardBaseline} from '../js/dashboard-baseline.mjs';

const base=process.env.TRAVELLER_TEST_URL||'http://127.0.0.1:8765/';
const root=fileURLToPath(new URL('../../../',import.meta.url)),artifacts=fileURLToPath(new URL('../verification-artifacts/',import.meta.url));
const KEY='traveller-trade-route-calculator:v1',LOCK=KEY+':writer',corrupt='{synthetic unreadable campaign';
const sizes=[{width:1440,height:1100},{width:390,height:844}];
const modes=['success','prewrite','unknown-before','unknown-after','notification-before','notification-after','cleanup','close-before','newer-dialog','tokenless-before','tokenless-after','takeover','late-role-loss','sync','idle-invalidated'];
const scenarios=[...['import','reset'].flatMap(path=>modes.map(mode=>({id:path+'-'+mode,path,mode,recovery:false}))),...['import','reset'].flatMap(path=>['success','prewrite','notification-after','sync'].map(mode=>({id:'recovery-'+path+'-'+mode,path,mode,recovery:true}))),...['selection','dialog','publication','editor-reacquired'].flatMap(staleBy=>['resolve','reject'].map(outcome=>({id:'file-'+staleBy+'-'+outcome,path:'import',mode:'file-race',staleBy,outcome}))),{id:'import-created-baseline',path:'import',mode:'success',withoutBaseline:true},{id:'import-reused-offer-ids',path:'import',mode:'offers'},{id:'import-consumed-mulligan',path:'import',mode:'protected-mulligan'}];
const report={suite:'Campaign import/reset replacement completion',startedAt:new Date().toISOString(),requestedCommit:process.env.TRAVELLER_COMMIT||null,node:process.version,declaredCases:scenarios.length*sizes.length,cases:[],errors:[],scope:'Actual file input/change and reset handlers, exact runtime Store/controller, owned delayed replacement completion, native localStorage/Web Locks, normal/corrupt recovery, backup acknowledgement, immutable import economics/history/Undo and Dashboard baseline, stale file reads, desktop/mobile JPEG evidence. No live campaigns or arbitrary replacement backends are certified.'};
let browser;
function fixture(){const s=S.initial(),origin={id:'0,0',x:0,y:0,name:'Replacement Origin',sector:'Synthetic',hex:'0101',uwp:'A788899-C',zone:'Safe'},destination={...origin,id:'1,0',x:1,name:'Replacement Destination',hex:'0201'};Object.assign(s,{initialized:true,name:'Disposable replacement campaign',actual:origin.id,worlds:{[origin.id]:origin,[destination.id]:destination},route:[origin.id,destination.id],bank:'100000'});Object.assign(s.ship,{capacity:'100',armed:true,staterooms:2,fuel:configureFuel(200,40,60,40,2),lifeSupport:{capacityHours:672,stockUnits:{numerator:'56',denominator:'1'}},accommodation:{rooms:{low:0,middle:2,high:0},passengers:{low:0,middle:0,high:0},crew:{low:0,middle:2,high:0}}});s.lots=[{id:'replacement-cargo',commodity:'11',description:'Retained cargo',quantity:'5',basis:'1000',goodsValue:'1000'}];s.contracts=[{id:'replacement-mail',kind:'mail',status:'accepted',firstDeparture:null,origin:origin.id,destination:destination.id,quantity:'5',payment:'1000',dueHours:null}];s.policies=[{id:'replacement-policy',lotId:'replacement-cargo',claims:[],status:'active',initialQuantity:'5',remainingQuantity:'5',insuredValue:'1000',remainingValue:'1000',coverage:70,route:[origin.id,destination.id],routeProgress:0,destination:destination.id}];s.dashboardBaseline=createDashboardBaseline(s);return S.transition(S.validate(s),'Manual deposit',next=>S.deposit(next,125,'Preserved old campaign'));}
function imported({withoutBaseline=false}={}){const s=S.transition(fixture(),'Imported deposit',next=>S.deposit(next,77,'Preserved imported history'));s.revision=91;s.actual='1,0';s.name='Imported synthetic campaign';if(withoutBaseline)delete s.dashboardBaseline;return S.validate(s);}
function protectedImport(){const jump=s=>{const prepared=S.prepareJump(s,()=>({dice:[3,3,3,3,3,3],total:18}));return S.transition(prepared.state,'Jump: Replacement Origin → Replacement Destination',next=>S.commitJump(next,{attemptId:prepared.attempt.id,elapsed:160}));};const s=jump(S.undoJump(jump(fixture())));s.revision=913;s.name='Imported consumed-mulligan campaign';return S.validate(s);}
const candidate=scenario=>scenario.path==='reset'?S.initial():scenario.mode==='protected-mulligan'?protectedImport():imported(scenario);
function expected(next,revision){const saved=structuredClone(next);saved.revision=revision+1;if(saved.initialized&&!saved.dashboardBaseline)saved.dashboardBaseline=createDashboardBaseline(saved);return S.validate(saved);}
const raw=page=>page.evaluate(key=>localStorage.getItem(key),KEY),read=async page=>JSON.parse(await raw(page));
const action=(page,name)=>page.locator('[data-action="'+name+'"]').filter({visible:true}).first();
const tab=(page,name)=>page.locator('#tabs [data-action="tab"][data-arg="'+name+'"]').click();
const frames=page=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
const closed=page=>page.locator('#modal').waitFor({state:'hidden'}),gate=page=>page.evaluate(()=>replacementGate.snapshot());
const errorText=error=>error?.stack||String(error),successPattern=/Campaign replaced\./;
async function contextFor(result,scenario){
 const context=await browser.newContext({viewport:result.viewport,serviceWorkers:'block'});context.setDefaultTimeout(10000);context.setDefaultNavigationTimeout(15000);
 context.on('page',page=>{page.on('pageerror',error=>result.pageErrors.push(errorText(error)));page.on('console',entry=>{if(entry.type()==='error')result.consoleErrors.push(entry.text());});});
 await context.exposeBinding('__replacementUnhandled',(_source,message)=>{result.unhandledRejections.push(message);});
 await context.addInitScript(({key,bytes,origin})=>{
  if(location.origin!==origin)return;addEventListener('unhandledrejection',event=>{void globalThis.__replacementUnhandled(String(event.reason?.stack||event.reason));});if(!localStorage.getItem(key))localStorage.setItem(key,bytes);
  const native=Storage.prototype.setItem;globalThis.replacementStorage={attempts:0,writes:0,failNext:false,observations:[]};Storage.prototype.setItem=function(name,value){if(this!==localStorage||name!==key)return Reflect.apply(native,this,[name,value]);replacementStorage.attempts++;replacementStorage.observations.push({message:document.querySelector('#message')?.textContent||'',open:!!document.querySelector('#modal')?.open});if(replacementStorage.failNext){replacementStorage.failNext=false;throw Error('Synthetic known prewrite replacement storage rejection');}const result=Reflect.apply(native,this,[name,value]);replacementStorage.writes++;return result;};
  const text=File.prototype.text;globalThis.replacementReads=[];File.prototype.text=function(){if(!this.name.startsWith('deferred-'))return Reflect.apply(text,this,[]);return new Promise((resolve,reject)=>replacementReads.push({name:this.name,resolve,reject}));};
  globalThis.replacementDiceCalls=0;const random=crypto.getRandomValues.bind(crypto);crypto.getRandomValues=array=>{if(array instanceof Uint32Array&&array.length===1){replacementDiceCalls++;array[0]=2;return array;}return random(array);};
 },{key:KEY,bytes:scenario.recovery?corrupt:JSON.stringify(fixture()),origin:new URL(base).origin});
 await context.route('**/*',async route=>{const url=new URL(route.request().url());if(url.href===new URL('verification/replacement-peer.html',base).href)return route.fulfill({contentType:'text/html',body:'<!doctype html><title>Disposable replacement Store peer</title>'});if(url.origin===new URL(base).origin)return route.continue();if(url.origin==='https://travellermap.com'&&url.pathname.startsWith('/api/'))return route.fulfill({json:url.pathname.endsWith('/jumpworlds')?{Worlds:[]}:url.pathname.endsWith('/universe')?{Sectors:[]}:url.pathname.endsWith('/metadata')?{Subsectors:[]}:'' ,headers:{'Access-Control-Allow-Origin':'*'}});result.unexpectedRequests.push(url.href);return route.abort('blockedbyclient');});return context;
}
async function installGate(page,result){
 result.runtime=await page.evaluate(async()=>{
  const appURL=[...document.scripts].find(s=>s.type==='module'&&/\/app\.mjs(?:\?|$)/.test(s.src))?.src;if(!appURL)throw Error('Actual app module unavailable');const response=await fetch(appURL);if(!response.ok)throw Error('Cannot inspect actual runtime app');const source=await response.text(),specifier=source.match(/import\s*\{[^}]*\bStore\b[^}]*\}\s*from\s*['"]([^'"]*persistence\.mjs[^'"]*)['"]/u)?.[1];if(!specifier)throw Error('Exact runtime Store import missing');const storeURL=new URL(specifier,appURL).href;if(!new URL(storeURL).search)throw Error('Expected versioned Store');
  const {Store,KEY}=await import(storeURL),native=Store.prototype.replace,observation=point=>({point,message:document.querySelector('#message')?.textContent||'',open:!!document.querySelector('#modal')?.open,title:document.querySelector('#modal-title')?.textContent||''});
  const g=globalThis.replacementGate={armed:false,pending:null,store:null,args:null,calls:0,executions:0,notifyFault:null,roleFault:false,roleThrows:0,cleanupFault:false,cleanupThrows:0,closeFault:false,closeThrows:0,forwarded:[],publications:[],observations:[],settlements:[]};
  const close=HTMLDialogElement.prototype.close;HTMLDialogElement.prototype.close=function(...args){if(g.closeFault&&this.id==='modal'&&g.settlements.at(-1)?.kind==='native-fulfilled'){g.closeFault=false;g.closeThrows++;throw Error('Synthetic native replacement close before detaching');}return Reflect.apply(close,this,args);};
  const html=Object.getOwnPropertyDescriptor(Element.prototype,'innerHTML');Object.defineProperty(Element.prototype,'innerHTML',{...html,set(value){if(g.cleanupFault&&this.id==='main'&&g.settlements.at(-1)?.kind==='native-fulfilled'){g.cleanupFault=false;g.cleanupThrows++;throw Error('Synthetic post-replacement cleanup render failure');}return Reflect.apply(html.set,this,[value]);}});
  function observeStore(store){if(g.store===store)return;if(g.store)throw Error('Unexpected second app Store');g.store=store;const change=store.onChange,role=store.onRole;store.onChange=function(...args){const record={revision:args[0].revision,replacementTokenPresent:args[1]?.replacementToken!=null,tokenMatchesReplace:args[1]?.replacementToken!=null&&args[1].replacementToken===g.args?.[2],saveTokenPresent:args[1]?.saveToken!=null,actualCallback:false};g.publications.push(record);g.observations.push(observation('before-receiveCampaign'));if(g.notifyFault==='before'){g.notifyFault=null;throw Error('Synthetic notification failure before actual receiveCampaign');}const value=Reflect.apply(change,this,args);record.actualCallback=true;g.observations.push(observation('after-receiveCampaign'));if(g.notifyFault==='after'){g.notifyFault=null;throw Error('Synthetic notification failure after actual receiveCampaign');}return value;};store.onRole=function(...args){const value=Reflect.apply(role,this,args);if(g.roleFault){g.roleFault=false;g.roleThrows++;throw Error('Synthetic replacement role callback failure');}return value;};}
  Store.prototype.replace=function(...args){observeStore(this);g.args=args;if(!g.armed)return Reflect.apply(native,this,args);if(g.pending)throw Error('App invoked Store.replace twice while pending');g.calls++;g.forwarded.push({argumentCount:args.length,tokenPresent:args[2]!=null,expectedRevision:args[1],candidateRevision:args[0].revision});return new Promise((resolve,reject)=>{g.pending={store:this,args,resolve,reject,executed:false,result:undefined,error:null};});};
  g.write=()=>{const p=g.pending;if(!p||p.executed)throw Error('Actual replacement must execute once');p.executed=true;g.executions++;try{p.result=Reflect.apply(native,p.store,p.args);}catch(error){p.error=error;}};
  g.release=kind=>{const p=g.pending;if(!p)throw Error('No pending replacement');if(kind==='unknown-before'){g.pending=null;g.settlements.push({kind,executed:false});p.reject(Error('Synthetic unknown replacement outcome'));return;}if(!p.executed)g.write();g.pending=null;if(kind==='unknown-after'){g.settlements.push({kind,executed:true});p.reject(Error('Synthetic lost response after durable replacement'));}else if(p.error){g.settlements.push({kind:'native-rejected',code:p.error.code||null,committed:p.error.committed??null});p.reject(p.error);}else{g.settlements.push({kind:'native-fulfilled',executed:true});p.resolve(p.result);}};
  g.snapshot=()=>({calls:g.calls,executions:g.executions,pending:!!g.pending,editable:g.store?.editable??null,recovery:!!g.store?.recovery,reloadRequired:!!g.store?.reloadRequired,storage:{...replacementStorage},forwarded:g.forwarded,publications:g.publications,observations:g.observations,settlements:g.settlements,roleThrows:g.roleThrows,cleanupThrows:g.cleanupThrows,closeThrows:g.closeThrows,durableHasToken:/"(?:replacementToken|saveToken)"\s*:/.test(localStorage.getItem(KEY))});return {appURL,storeURL};
 });
}
async function capture(page,result,label){await frames(page);const name='replacement-completion-'+result.id+'-'+label+'.jpg';await page.screenshot({path:join(artifacts,name),type:'jpeg',quality:80});result.screenshots.push(name);const geometry=await page.evaluate(()=>{const dialog=document.querySelector('#modal[open]'),r=dialog?.getBoundingClientRect();return {width:innerWidth,pageOverflow:document.documentElement.scrollWidth-innerWidth,dialog:r?{left:r.left,right:r.right,overflow:dialog.scrollWidth-dialog.clientWidth}:null};});result.layouts.push({label,...geometry});assert.ok(geometry.pageOverflow<=2,'No horizontal page overflow');if(geometry.dialog){assert.ok(geometry.dialog.left>=-1&&geometry.dialog.right<=geometry.width+1,'Replacement dialog remains in viewport');assert.ok(geometry.dialog.overflow<=2,'No horizontal dialog clipping');}}
async function pointer(page,id){const locator=page.locator('#'+id);if(!await locator.isVisible())return;await locator.scrollIntoViewIfNeeded();const box=await locator.boundingBox();assert.ok(box);await page.mouse.click(box.x+box.width/2,box.y+box.height/2,{clickCount:2,delay:20});}
const release=(page,kind='native')=>page.evaluate(kind=>replacementGate.release(kind),kind);
async function loadFile(page,next,name='replacement.json'){await page.locator('#import-file').setInputFiles({name,mimeType:'application/json',buffer:Buffer.from(typeof next==='string'?next:JSON.stringify(next))});}
async function openReview(page,scenario,next=candidate(scenario)){if(!scenario.recovery)await tab(page,'Settings');if(scenario.path==='import'){const chooser=page.waitForEvent('filechooser');await action(page,'import').click();await (await chooser).setFiles({name:'approved-import.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(next))});}else await action(page,'reset').click();await page.locator('#modal-title').filter({hasText:scenario.path==='import'?'Load campaign (JSON)':'Reset campaign'}).waitFor();assert.equal(await page.locator('#import-file').inputValue(),'');}
async function acknowledge(page){await page.locator('#modal [name="backed"]').check();}
async function start(page){await acknowledge(page);await page.locator('#modal-submit').click();}
async function arm(page,scenario){await page.evaluate(({mode})=>{Object.assign(replacementGate,{armed:true,notifyFault:mode==='notification-before'?'before':mode==='notification-after'?'after':null,roleFault:mode==='notification-after'});replacementStorage.failNext=mode==='prewrite';},scenario);}
async function pending(page,result,before){await start(page);await page.waitForFunction(()=>!!replacementGate.pending);await frames(page);assert.equal(await raw(page),before);assert.doesNotMatch(await page.locator('#message').textContent(),successPattern);for(const id of ['modal-submit','modal-cancel','modal-close'])assert.equal(await page.locator('#'+id).isDisabled(),true);await page.locator('#modal-form').evaluate(form=>{globalThis.detachedReplacementSubmit=form.onsubmit;});await pointer(page,'modal-submit');await page.keyboard.press('Enter');await page.locator('#modal-form').evaluate(form=>form.requestSubmit());await page.evaluate(()=>{void detachedReplacementSubmit({preventDefault(){},currentTarget:document.querySelector('#modal-form')});document.querySelector('[data-action="reset"]')?.click();document.querySelector('[data-action="notes"]')?.click();});await pointer(page,'modal-cancel');await pointer(page,'modal-close');await page.keyboard.press('Escape');await frames(page);assert.equal((await gate(page)).calls,1);assert.equal(await page.locator('#modal').evaluate(dialog=>dialog.open),true);assert.equal(await raw(page),before);await capture(page,result,'pending');result.checks.push('Backup-confirmed replacement blocks repeated pointer/Enter/requestSubmit, detached callback, replacement dialogs and Escape until completion');}
async function reloadAndVerify(page,result,bytes){await page.reload();await page.getByText(bytes===corrupt?'Recovery mode: restore saved data':'Editing in this tab',{exact:true}).waitFor();assert.equal(await raw(page),bytes,'Real reload must not replay replacement');assert.equal(await page.evaluate(()=>replacementStorage.writes),0);await capture(page,result,'reloaded');result.checks.push('Authoritative real reload retains exact saved bytes without another replacement');}
async function success(page,result,scenario,next,beforeRevision){await closed(page);assert.deepEqual(await read(page),expected(next,beforeRevision));assert.match(await page.locator('#message').textContent(),successPattern);const g=await gate(page);assert.equal(g.storage.writes-(result.initialWrites||0),1);assert.equal(g.recovery,false);assert.equal(g.durableHasToken,false);for(const forwarded of g.forwarded){assert.equal(forwarded.argumentCount,3);assert.equal(forwarded.tokenPresent,true);assert.equal(forwarded.expectedRevision,beforeRevision);}const publication=g.publications.findLast(p=>p.replacementTokenPresent);assert.ok(publication);assert.equal(publication.tokenMatchesReplace,true);assert.equal(publication.saveTokenPresent,false);assert.equal(publication.revision,beforeRevision+1);for(const observation of [...g.observations,...g.storage.observations])assert.doesNotMatch(observation.message,successPattern,'No success before provider completion');const bytes=await raw(page);await page.evaluate(()=>{void globalThis.detachedReplacementSubmit?.({preventDefault(){},currentTarget:document.querySelector('#modal-form')});});assert.equal(await raw(page),bytes);result.gate=await gate(page);await capture(page,result,'completed');await reloadAndVerify(page,result,bytes);result.checks.push('One replacement rebases imported revision; preserves complete imported economics/history/Undo; retains or creates Dashboard baseline; only completed owner shows success');}
async function terminal(page,result,scenario,next,beforeRevision,original){await page.waitForFunction(()=>/Reload/.test(document.querySelector('#save-status').textContent));await frames(page);const committed=scenario.mode!=='unknown-before',pattern=committed?/saved[\s\S]*Reload/i:/outcome could not be confirmed[\s\S]*Reload/i;for(const id of ['message','save-status','modal-error'])assert.match(await page.locator('#'+id).textContent(),pattern);const g=await gate(page);assert.equal(g.editable,false);assert.equal(g.reloadRequired,true);assert.equal(await page.locator('#takeover').isDisabled(),true);assert.doesNotMatch(await page.locator('#message').textContent(),successPattern);if(committed)assert.deepEqual(await read(page),expected(next,beforeRevision));else assert.equal(await raw(page),original);assert.equal(g.storage.writes-(result.initialWrites||0),committed?1:0);const bytes=await raw(page);await page.locator('#modal-form').evaluate(form=>form.requestSubmit());await page.evaluate(()=>{void detachedReplacementSubmit({preventDefault(){},currentTarget:document.querySelector('#modal-form')});});await frames(page);assert.equal(await raw(page),bytes);assert.equal((await gate(page)).calls,1);await page.waitForFunction(async lock=>(await navigator.locks.query()).held.every(entry=>entry.name!==lock),LOCK);assert.equal(await page.evaluate(lock=>navigator.locks.request(lock,{ifAvailable:true},held=>!!held),LOCK),true);if(scenario.mode==='cleanup')assert.equal(g.cleanupThrows,1);if(scenario.mode==='close-before'){assert.equal(g.closeThrows,1);assert.equal(await page.locator('#modal').evaluate(dialog=>dialog.open),true);for(const id of ['modal-cancel','modal-close'])assert.equal(await page.locator('#'+id).isEnabled(),true);}if(scenario.mode==='notification-after')assert.equal(g.roleThrows,1);result.gate=await gate(page);await capture(page,result,'reload-only');await page.locator('#modal-cancel').click();await closed(page);assert.equal(await page.locator('[data-mutate]:enabled').count(),0);await reloadAndVerify(page,result,bytes);result.checks.push('Durable/unknown failure observes rejection, releases native writer lock and blocks replay until real reload');}
async function peerOwn(context,page,result){const peer=await context.newPage();await peer.goto(new URL('verification/replacement-peer.html',base).href);await peer.evaluate(async({storeURL})=>{const {Store}=await import(storeURL);globalThis.replacementPeer={state:null,editable:false};replacementPeer.store=new Store(next=>{replacementPeer.state=next;},editable=>{replacementPeer.editable=editable;});await replacementPeer.store.acquire(true);},result.runtime);await peer.waitForFunction(()=>replacementPeer.editable);await page.waitForFunction(()=>/Read-only/.test(document.querySelector('#save-status').textContent));return peer;}
async function releasePeer(peer){await peer.evaluate(()=>{replacementPeer.store.yield();replacementPeer.store.channel?.close();});await peer.close();}
async function fileRace(page,result,scenario,context){
 const bytes=await raw(page);await loadFile(page,candidate(scenario),'deferred-old.json');await page.waitForFunction(()=>replacementReads.length===1);assert.equal(await page.locator('#import-file').inputValue(),'');
 if(scenario.staleBy==='selection'){const next=imported();next.name='Newer selected campaign';await loadFile(page,next,'fresh.json');await page.locator('#modal-title').filter({hasText:'Load campaign (JSON)'}).waitFor();}
 if(scenario.staleBy==='dialog'){await tab(page,'Settings');await action(page,'reset').click();await page.locator('#modal-title').filter({hasText:'Reset campaign'}).waitFor();}
 if(scenario.staleBy==='publication')await page.evaluate(key=>dispatchEvent(new StorageEvent('storage',{key,newValue:localStorage.getItem(key)})),KEY);
 if(scenario.staleBy==='editor-reacquired'){const peer=await peerOwn(context,page,result);await releasePeer(peer);await page.locator('#takeover').click();await page.getByText('Editing in this tab',{exact:true}).waitFor();}
 const before=await page.evaluate(()=>({open:document.querySelector('#modal').open,title:document.querySelector('#modal-title').textContent,body:document.querySelector('#modal-body').innerHTML,message:document.querySelector('#message').textContent}));
 await page.evaluate(({outcome,bytes})=>{const read=replacementReads[0];if(outcome==='resolve')read.resolve(bytes);else read.reject(Error('Obsolete file read must be ignored'));},{outcome:scenario.outcome,bytes:JSON.stringify(imported())});await frames(page);const after=await page.evaluate(()=>({open:document.querySelector('#modal').open,title:document.querySelector('#modal-title').textContent,body:document.querySelector('#modal-body').innerHTML,message:document.querySelector('#message').textContent}));assert.deepEqual(after,before,'Obsolete file completion must not overwrite newer UI or report stale errors');assert.equal(await raw(page),bytes);assert.equal(await page.evaluate(()=>replacementStorage.writes),0);await capture(page,result,'stale-file-ignored');result.checks.push('Actual asynchronous file onchange ignores stale '+scenario.outcome+' after '+scenario.staleBy+' without opening or modifying a newer dialog');
 if(scenario.staleBy==='selection'){await start(page);await closed(page);assert.equal((await read(page)).name,'Newer selected campaign','Only the newest selected file owns confirmation');}
}
async function prepareOffers(page){await tab(page,'Contracts');await action(page,'mail-check').click();await page.locator('#modal').getByText('Manual mail rolls (optional)',{exact:true}).click();for(const [name,value]of Object.entries({dice:'8',skill:'0',characteristic:'0',mailAvailability:'12',mailContainers:'3'})){const input=page.locator('#modal [name="'+name+'"]');if(await input.count())await input.fill(value);}await page.locator('#modal-submit').click();await closed(page);assert.ok(await page.locator('[data-action="contract-accept"]').count()>0,'Live current-session offers exist');}
async function runBody(page,result,scenario,context){
 await page.goto(base);await page.getByText(scenario.recovery?'Recovery mode: restore saved data':'Editing in this tab',{exact:true}).waitFor();await installGate(page,result);if(scenario.mode==='file-race'){await fileRace(page,result,scenario,context);return;}
 if(scenario.mode==='offers')await prepareOffers(page);
 const original=await raw(page),beforeRevision=scenario.recovery?0:(await read(page)).revision,next=scenario.mode==='offers'?await read(page):candidate(scenario);result.initialWrites=await page.evaluate(()=>replacementStorage.writes);await openReview(page,scenario,next);
 // Every family retains its backup acknowledgement and cancellation contract.
 await page.locator('#modal-submit').click();await page.locator('#modal-error').filter({hasText:/backup|proceed/}).waitFor();assert.equal(await raw(page),original);assert.equal((await gate(page)).reloadRequired,false);assert.equal(await page.locator('#modal-submit').isEnabled(),true);await page.locator('#modal-cancel').click();await closed(page);assert.equal(await raw(page),original);await openReview(page,scenario,next);
 if(scenario.mode==='sync'){await start(page);await closed(page);assert.deepEqual(await read(page),expected(next,beforeRevision));assert.match(await page.locator('#message').textContent(),successPattern);assert.equal(await page.evaluate(()=>replacementStorage.writes),1);await capture(page,result,'synchronous');await reloadAndVerify(page,result,await raw(page));result.checks.push('Unwrapped native synchronous replacement and backup/cancel behavior unchanged');return;}
 if(scenario.mode==='idle-invalidated'){await page.evaluate(key=>dispatchEvent(new StorageEvent('storage',{key,newValue:localStorage.getItem(key)})),KEY);await frames(page);assert.equal(await page.locator('#modal-submit').isDisabled(),true);await acknowledge(page);await page.locator('#modal-form').evaluate(form=>form.requestSubmit());assert.equal(await raw(page),original);assert.match(await page.locator('#modal-error').textContent(),/changed|reopen/i);await capture(page,result,'stale-review');result.checks.push('Foreign same-revision publication invalidates the reviewed replacement before submit');return;}
 await arm(page,scenario);await pending(page,result,original);
 if(scenario.mode==='takeover'){const peer=await peerOwn(context,page,result);await peer.evaluate(async({storeURL})=>{const url=new URL('state.mjs',storeURL);url.search=new URL(storeURL).search;const S=await import(url.href),next=S.transition(replacementPeer.state,'Peer deposit during replacement',s=>S.deposit(s,9,'Native lock owner'));replacementPeer.store.save(next,replacementPeer.state.revision);},result.runtime);const bytes=await raw(page);await release(page);await frames(page);assert.equal(await raw(page),bytes);assert.equal((await gate(page)).settlements.at(-1).code,'SAVE_NOT_COMMITTED');assert.match(await page.locator('#modal-error').textContent(),/editing|changed|read-only|stale/i);assert.doesNotMatch(await page.locator('#message').textContent(),successPattern);result.gate=await gate(page);await capture(page,result,'owner-changed');await releasePeer(peer);await reloadAndVerify(page,result,bytes);result.checks.push('Second real Store takes native writer lock; old replacement cannot overwrite its newer saved revision');return;}
 if(scenario.mode==='prewrite'){await release(page);await page.locator('#modal-error').filter({hasText:'Synthetic known prewrite'}).waitFor();assert.equal(await raw(page),original);assert.equal((await gate(page)).reloadRequired,false);assert.equal((await gate(page)).recovery,!!scenario.recovery);assert.equal(await page.locator('#modal-submit').isEnabled(),true);await capture(page,result,'retryable');await page.locator('#modal-submit').click();await page.waitForFunction(()=>!!replacementGate.pending);assert.equal((await gate(page)).calls,2);await release(page);await success(page,result,scenario,next,beforeRevision);return;}
 if(scenario.mode==='newer-dialog'){await page.locator('#modal').evaluate(dialog=>dialog.close());await closed(page);await page.locator('#notes').click();await page.locator('#modal-title').filter({hasText:'Rules & Notes'}).waitFor();const body=await page.locator('#modal-body').innerHTML();await release(page);await frames(page);assert.deepEqual(await read(page),expected(next,beforeRevision));assert.equal(await page.locator('#modal-title').textContent(),'Rules & Notes');assert.equal(await page.locator('#modal-body').innerHTML(),body);assert.equal(await page.locator('#modal-error').textContent(),'');assert.doesNotMatch(await page.locator('#message').textContent(),successPattern);await capture(page,result,'newer-dialog-preserved');result.gate=await gate(page);result.checks.push('Native detached-dialog event retires old owner; its completion cannot dismiss or modify a newer read-only dialog');return;}
 if(['tokenless-before','tokenless-after','late-role-loss'].includes(scenario.mode)){
  if(scenario.mode!=='tokenless-before')await page.evaluate(()=>replacementGate.write());if(scenario.mode==='late-role-loss'){await page.evaluate(()=>replacementGate.store.yield());await page.waitForFunction(async lock=>(await navigator.locks.query()).held.every(entry=>entry.name!==lock),LOCK);await page.evaluate(()=>document.querySelector('#takeover').click());await page.getByText('Editing in this tab',{exact:true}).waitFor();}else await page.evaluate(()=>replacementGate.store.onChange(replacementGate.store.read()));await release(page);await frames(page);assert.deepEqual(await read(page),expected(next,beforeRevision));assert.doesNotMatch(await page.locator('#message').textContent(),successPattern);const bytes=await raw(page);await page.locator('#modal-form').evaluate(form=>form.requestSubmit());assert.equal((await gate(page)).calls,1);assert.equal(await raw(page),bytes);result.gate=await gate(page);await capture(page,result,'retired-completion');await reloadAndVerify(page,result,bytes);result.checks.push('Same-revision foreign publication or lost-and-reacquired editor permanently retires old replacement completion');return;
 }
 if(['success','offers','protected-mulligan'].includes(scenario.mode)){await page.evaluate(()=>replacementGate.write());await frames(page);assert.deepEqual(await read(page),expected(next,beforeRevision));assert.equal(await page.locator('#modal').evaluate(dialog=>dialog.open),true);assert.doesNotMatch(await page.locator('#message').textContent(),successPattern);for(const id of ['modal-submit','modal-cancel','modal-close'])assert.equal(await page.locator('#'+id).isDisabled(),true);await capture(page,result,'durable-awaiting-completion');await release(page);await closed(page);if(scenario.mode==='offers'){await tab(page,'Contracts');assert.equal(await page.locator('[data-action="contract-accept"]').count(),0,'Reused imported audit/offer IDs cannot resurrect session offers');assert.deepEqual((await read(page)).events,next.events);result.checks.push('Genuine import immediately retires live offers while preserving the reused historical mail audit');}if(scenario.mode==='protected-mulligan')assert.equal(await page.evaluate(()=>replacementDiceCalls),0,'Actual import must not reroll saved jump dice');await success(page,result,scenario,next,beforeRevision);if(scenario.mode==='protected-mulligan'){assert.equal(await page.evaluate(()=>replacementDiceCalls),0,'Reload/import must not generate new jump dice');assert.equal(S.jumpUndoEligibility(await read(page)).allowed,false);assert.equal((await read(page)).jumpAttempts[0].mulliganUsed,true);assert.equal((await read(page)).jumpAttempts[0].rolls.length,2);for(const key of ['jumpAttempts','events','undo'])assert.deepEqual((await read(page))[key],next[key]);const bytes=await raw(page);await tab(page,'Overview');assert.equal(await action(page,'jump-undo').isDisabled(),true);await tab(page,'History');await action(page,'undo').click();assert.match(await page.locator('#message').textContent(),/Mulligan used/);assert.equal(await raw(page),bytes);assert.equal(await page.evaluate(()=>replacementDiceCalls),0);await capture(page,result,'protected-mulligan-retained');result.checks.push('Imported consumed mulligan and both saved rolls preserve exact jump/audit/Undo linkage across rebased revision and reload; protected inverse and reroll remain blocked');}return;}
 if(scenario.mode==='close-before')await page.evaluate(()=>{replacementGate.closeFault=true;});if(scenario.mode==='cleanup')await page.evaluate(()=>{replacementGate.cleanupFault=true;});await release(page,scenario.mode.startsWith('unknown-')?scenario.mode:'native');await terminal(page,result,scenario,next,beforeRevision,original);
}
async function writeReport(){await writeFile(join(artifacts,'replacement-completion-report.json'),JSON.stringify(report,null,2)+'\n');}
async function runCase(scenario,viewport){const result={id:scenario.id+'-'+viewport.width,path:scenario.path,mode:scenario.mode,recovery:!!scenario.recovery,viewport,status:'running',checks:[],screenshots:[],layouts:[],pageErrors:[],unhandledRejections:[],consoleErrors:[],unexpectedRequests:[],errors:[]};report.cases.push(result);let context;try{context=await contextFor(result,scenario);const page=await context.newPage();await runBody(page,result,scenario,context);await frames(page);assert.deepEqual(result.pageErrors,[]);assert.deepEqual(result.unhandledRejections,[]);assert.deepEqual(result.consoleErrors,[]);assert.deepEqual(result.unexpectedRequests,[]);result.status='passed';}catch(error){result.status='failed';result.errors.push(errorText(error));const page=context?.pages()[0];if(page){await capture(page,result,'failure').catch(()=>{});result.failedGate=await gate(page).catch(()=>null);}}finally{await context?.close();await writeReport();}console.log(result.status.toUpperCase()+': '+result.id);for(const error of result.errors)console.error(error);}
if(process.argv.includes('--fixtures-only')){
 for(const scenario of scenarios){const next=candidate(scenario),before=structuredClone(next),saved=expected(next,scenario.recovery?0:fixture().revision);assert.equal(saved.revision,(scenario.recovery?0:fixture().revision)+1);assert.deepEqual(next,before);for(const key of ['bank','ship','lots','contracts','policies','ledger','events','undo','jumpAttempts','hours','actual','route'])assert.deepEqual(saved[key],next[key]);if(next.initialized)assert.deepEqual(saved.dashboardBaseline,next.dashboardBaseline||createDashboardBaseline(next));}
 const protectedState=protectedImport();assert.equal(protectedState.jumpAttempts.length,1);assert.equal(protectedState.jumpAttempts[0].mulliganUsed,true);assert.equal(protectedState.jumpAttempts[0].rolls.length,2);assert.equal(S.jumpUndoEligibility(protectedState).allowed,false);assert.throws(()=>S.undo(protectedState),/Mulligan used/);
 const html=await readFile(new URL('../index.html',import.meta.url),'utf8'),app=await readFile(new URL('../js/app.mjs',import.meta.url),'utf8');assert.match(html,/<script type="module" src="js\/app\.mjs\?[^"]+"/);assert.match(app,/import\s*\{[^}]*\bStore\b[^}]*\}\s*from\s*['"]\.\/persistence\.mjs\?[^'"]+['"]/);assert.equal(new Set(scenarios.map(s=>s.id)).size,scenarios.length);console.log(`PASS: exact synthetic replacement economic/history/Undo/baseline fixtures and actual versioned Store wiring; ${scenarios.length} scenarios x ${sizes.length} widths = ${report.declaredCases} browser cases declared. Chromium was not launched.`);
}else{
 await mkdir(artifacts,{recursive:true});try{report.testedCommit=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim();if(report.requestedCommit)assert.equal(report.testedCommit,report.requestedCommit);const {chromium}=createRequire(import.meta.url)(process.argv[2]||'playwright');browser=await chromium.launch({headless:true,...(process.env.TRAVELLER_BROWSER_CHANNEL?{channel:process.env.TRAVELLER_BROWSER_CHANNEL}:{})});report.browser={name:'Chromium',version:browser.version()};for(const viewport of sizes)for(const scenario of scenarios)await runCase(scenario,viewport);const files=(await readdir(artifacts)).filter(name=>name.startsWith('replacement-completion-'));report.screenshotCount=files.filter(name=>name.endsWith('.jpg')).length;report.artifactBytes=(await Promise.all(files.map(async name=>(await stat(join(artifacts,name))).size))).reduce((a,b)=>a+b,0);assert.ok(report.artifactBytes<24*1024*1024-65536,'Replacement evidence must fit below bounded 24 MiB download size');}catch(error){report.errors.push(errorText(error));}finally{await browser?.close();report.finishedAt=new Date().toISOString();report.passed=report.errors.length===0&&report.cases.length===report.declaredCases&&report.cases.every(result=>result.status==='passed');await writeReport();}if(!report.passed)throw Error('Replacement completion Chromium checks failed; see verification-artifacts/replacement-completion-report.json');console.log(`PASS: ${report.declaredCases} actual import/reset browser cases, exact replacement economics/history/Undo, native locks, file-read races, desktop/mobile JPEG evidence; no uncaught errors or unhandled rejections.`);
}
