import test from 'node:test';
import assert from 'node:assert/strict';
import {createServicePanels,maxFuelAddition,fuelCorrection} from '../js/service-panels.mjs';
import {configureFuel} from '../js/fuel.mjs';
import * as S from '../js/state.mjs';
const campaign=()=>{const s=S.initial();s.initialized=true;s.bank='100000';s.actual='0,0';s.route=['0,0'];s.worlds={'0,0':{id:'0,0',name:'Actual origin',x:0,y:0,sector:'Test',hex:'0101',uwp:'A788899-C',zone:'Safe'}};s.ship.fuel=configureFuel(200,43,20,0,2);return s;};
function harness(s=campaign()){let state=s,editable=true;const h={renders:0,commits:0},document={getElementById(){return null;},querySelector(){return null;},querySelectorAll(){return [];}};h.services=createServicePanels({document,getState:()=>state,isEditable:()=>editable,commit(label,fn,revision){assert.equal(revision,state.revision);if(!editable)throw Error('read-only');state=S.transition(state,label,fn);h.commits++;},render(){h.renders++;},showOverview(){},message(){},nextJumpFuel:()=>20});h.state=()=>state;h.setState=s=>state=s;h.readOnly=()=>editable=false;return h;}
test('fuel maximum preserves odd tons and combines empty base tanks with exact free cargo',()=>{const s=campaign();assert.equal(maxFuelAddition(s),23);s.ship.fuel=configureFuel(200,43,40,1,2);s.ship.capacity='9';s.lots=[{quantity:'5.2'}];assert.equal(maxFuelAddition(s),6);s.ship.fuel.aboardTons=50;assert.equal(maxFuelAddition(s),0);});
test('fuel correction is reduction-only, audited, bank-neutral, releases bladder cargo and undoes',()=>{const s=campaign();s.ship.fuel=configureFuel(200,43,55,1,2);const before=structuredClone(s),n=S.transition(s,'Adjusted fuel aboard',n=>fuelCorrection(n,'41','Actual tank check'));assert.equal(n.bank,s.bank);assert.equal(n.ship.fuel.aboardTons,41);assert.equal(n.events[0].fuelCorrection.removed,14);assert.equal(n.events[0].fuelCorrection.reason,'Actual tank check');assert.equal(n.ledger.length,0);assert.deepEqual(S.undo(n).ship,before.ship);for(const bad of ['','56','-1','2.5','55'])assert.throws(()=>fuelCorrection(structuredClone(s),bad));assert.deepEqual(s,before);});
test('opening, adjusting, reviewing and cancelling never mutate the campaign',async()=>{const h=harness(),before=structuredClone(h.state());h.services.open('fuel');assert.match(h.services.panel(),/Refuel · Summary/);assert.match(h.services.panel(),/Actual origin/);await h.services.action('service-adjust','');assert.match(h.services.panel(),/value="23"/);await h.services.action('service-review','');assert.equal(h.commits,0);await h.services.action('service-back','');assert.equal(h.services.active(),false);assert.deepEqual(h.state(),before);});
test('only final summary Confirm saves once; repeated click cannot pay again',async()=>{const h=harness();h.services.open('fuel');await h.services.action('service-adjust','');await h.services.action('service-confirm','');assert.equal(h.commits,0);await h.services.action('service-review','');await h.services.action('service-confirm','');await h.services.action('service-confirm','');assert.equal(h.commits,1);assert.equal(h.state().ship.fuel.aboardTons,43);assert.equal(h.state().bank,'88500');assert.equal(S.undo(h.state()).ship.fuel.aboardTons,20);});
test('stale and read-only drafts cannot commit and keep frozen actual-world display',async()=>{for(const mode of ['revision','ownership']){const h=harness();h.services.open('fuel');if(mode==='revision'){const next=S.transition(h.state(),'Other change',s=>s.bank='99999');h.setState(next);}else h.readOnly();assert.match(h.services.panel(),/Campaign or editing ownership changed/);await assert.rejects(h.services.action('service-confirm',''),/Campaign or editing ownership changed/);assert.equal(h.commits,0);await h.services.action('service-cancel','');assert.equal(h.services.active(),false);}});
test('LSS preview rejects funds and cargo overflow before offering payment',()=>{for(const kind of ['funds','cargo']){const s=campaign();s.ship.accommodation={rooms:{low:0,middle:4,high:0},passengers:{low:0,middle:4,high:0},crew:{low:0,middle:0,high:0}};s.ship.lifeSupport={capacityHours:672,stockUnits:{numerator:'56',denominator:'1'}};if(kind==='funds')s.bank='1';else{s.ship.fuel=configureFuel(10,4,2,0,2);s.ship.capacity='0';}const h=harness(s);h.services.open('support');assert.match(h.services.panel(),kind==='funds'?/Insufficient funds/:/exceed available cargo/);assert.equal(h.commits,0);}});
