// Exact-head Settings completion gate. Uses disposable campaigns, the actual
// versioned Store, native Web Locks and production inline/modal callbacks.
// --fixtures-only checks fixture/source wiring without loading Playwright.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir,readFile,readdir,stat,writeFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {join} from 'node:path';
import * as S from '../js/state.mjs';
import {configureFuel} from '../js/fuel.mjs';
import {guiFixture,campaignKey as KEY} from './fixtures/gui-parity.mjs';
import {settingsGroups} from '../js/settings-layout.mjs';
import {dashboardData} from '../js/dashboard-data.mjs';

const base=process.env.TRAVELLER_TEST_URL||'http://127.0.0.1:8765/';
const root=fileURLToPath(new URL('../../../',import.meta.url)),artifacts=fileURLToPath(new URL('../verification-artifacts/',import.meta.url));
const sizes=[{width:1440,height:1100},{width:390,height:844}],LOCK=KEY+':writer';
const scenarios=[...['sync','success','prewrite','validation','notification-before','notification-after','unknown-before','unknown-after','missing','contradictory','foreign','editor-regain','stale-disk','detached','pending-ui-before','pending-ui-after','render','focus','close','report'].map(mode=>({id:'inline-'+mode,path:'inline',mode})),...['success','prewrite','notification-after'].map(mode=>({id:'modal-'+mode,path:'modal',mode}))];
const report={suite:'Settings save completion',startedAt:new Date().toISOString(),requestedCommit:process.env.TRAVELLER_COMMIT||null,node:process.version,declaredCases:scenarios.length*sizes.length,cases:[],errors:[],scope:'Inline and legacy Settings only: actual DOM, suspension/remount, synchronous compatibility, deferred publication/completion, native Web Locks, retired ownership, validation, exact candidate/economic/audit bytes, reload and Undo. Synthetic fixtures; no live campaign or map data; no arbitrary provider certification.'};
let browser;
const draft={name:'Completion Settings campaign',ship:'Completion Trader',capacity:'160.1',jump:'3',broker:'3',streetwise:'2',admin:'1',characteristic:'-1',rank:'4',soc:'2',mode:'custom',custom:'62.5',shipTons:'300',fuelCapacity:'60',bladderTons:'90',fuelAboard:'65','rooms-low':'1','roomService-low':'custom','roomCustom-low':'200','rooms-middle':'5','roomService-middle':'custom','roomCustom-middle':'1300','rooms-high':'2','roomService-high':'custom','roomCustom-high':'1700','people-middle':'6','people-high':'3',occupiedLowBerths:'2',luggageOverride:true,luggageTons:'7',supportCapacity:'35',supportRemaining:'13.75',supportUnits:'',creditStep:'100',scoops:false,armed:true,reducedProfitLimitsEnabled:true,minPurchasePercent:'90',maxSalePercent:'110',maxBaseRetailEnabled:true,maxBaseRetail:'50000',useRawIllegalPrices:true,tax:true,insurance:true,mortgageOriginal:'24000000',mortgagePayment:'100001',mortgageRemaining:'360',mortgagePaid:'12000000',mortgageDueDate:'029-1105',maintenancePayment:'2001',maintenanceDueDate:'015-1105'};
function fixture(){const s=guiFixture().state;s.ship.lifeSupport.elapsedHours=6;s.policies=[{id:'settings-policy',lotId:'lot-opening',claims:[],status:'active',initialQuantity:'2',remainingQuantity:'2',insuredValue:'2000',remainingValue:'2000',coverage:70,route:s.route.slice(s.routeIndex),routeProgress:0,destination:s.route.at(-1)}];return S.validate(s);}
const errorText=e=>e?.stack||String(e),successPattern=/Ship \/ trader settings saved\./;
const raw=page=>page.evaluate(key=>localStorage.getItem(key),KEY),read=async page=>JSON.parse(await raw(page));
const frames=page=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
const tab=(page,name)=>page.locator('#tabs [data-action="tab"][data-arg="'+name+'"]').click();
const gate=page=>page.evaluate(()=>settingsGate.snapshot()),closed=page=>page.locator('#modal').waitFor({state:'hidden'});
const scope=(page,path)=>page.locator(path==='inline'?'#settings-form':'#modal-form');
const values=(page,path='inline')=>scope(page,path).locator('[name]').evaluateAll(fields=>Object.fromEntries(fields.map(el=>[el.name,el.type==='checkbox'?el.checked:el.value])));
const disclosures=page=>page.locator('#main details[data-settings-group]').evaluateAll(nodes=>Object.fromEntries(nodes.map(el=>[el.dataset.settingsGroup,el.open])));
async function setField(page,path,name,value){const field=scope(page,path).locator('[name="'+name+'"]');for(const detail of await field.locator('xpath=ancestor::details').all())if(!await detail.evaluate(el=>el.open))await detail.locator(':scope > summary').click({position:{x:8,y:8}});const tag=await field.evaluate(el=>el.type==='checkbox'?'checkbox':el.tagName);if(tag==='checkbox')await field.setChecked(value);else if(tag==='SELECT')await field.selectOption(String(value));else await field.fill(String(value));await field.dispatchEvent('change');}
async function prepare(page,path){
 await tab(page,'Settings');if(path==='modal'){await setField(page,'inline','name','Unrelated dirty inline draft');await setField(page,'inline','capacity','121.1');await page.locator('#main [data-action="settings-edit"]').click();await page.locator('#modal-title').filter({hasText:'Ship, trader & options'}).waitFor();assert.equal(await page.locator('#settings-form').count(),0,'Legacy modal suspends the dirty inline form');}
 for(const [name,value]of Object.entries(draft))await setField(page,path,name,value);
 if(path==='inline')await page.locator('#main details[data-settings-group]').evaluateAll(nodes=>nodes.forEach((el,i)=>el.open=i%3===0));
 await frames(page);return {values:await values(page,path),groups:await disclosures(page)};
}
async function contextFor(result){
 const context=await browser.newContext({viewport:result.viewport,serviceWorkers:'block'});context.setDefaultTimeout(10000);context.setDefaultNavigationTimeout(15000);
 context.on('page',page=>{page.on('pageerror',e=>result.pageErrors.push(errorText(e)));page.on('console',entry=>{if(entry.type()==='error')result.consoleErrors.push(entry.text());});page.on('requestfailed',request=>{if(request.failure()?.errorText!=='net::ERR_ABORTED')result.networkErrors.push(request.url()+': '+request.failure()?.errorText);});page.on('response',response=>{if(response.status()>=400)result.networkErrors.push(response.status()+' '+response.url());});});
 await context.exposeBinding('__settingsUnhandled',(_source,message)=>result.unhandledRejections.push(message));
 await context.addInitScript(({key,bytes,origin})=>{if(location.origin!==origin)return;addEventListener('unhandledrejection',event=>{void globalThis.__settingsUnhandled(String(event.reason?.stack||event.reason));});if(!localStorage.getItem(key))localStorage.setItem(key,bytes);const native=Storage.prototype.setItem;globalThis.settingsStorage={attempts:0,writes:0,failNext:false,observations:[]};Storage.prototype.setItem=function(name,value){if(this!==localStorage||name!==key)return Reflect.apply(native,this,[name,value]);settingsStorage.attempts++;settingsStorage.observations.push({message:document.querySelector('#message')?.textContent||'',open:!!document.querySelector('#modal')?.open});if(settingsStorage.failNext){settingsStorage.failNext=false;throw Error('Synthetic known Settings prewrite rejection');}const result=Reflect.apply(native,this,[name,value]);settingsStorage.writes++;return result;};},{key:KEY,bytes:JSON.stringify(fixture()),origin:new URL(base).origin});
 const map=guiFixture();await context.route('**/*',async route=>{const url=new URL(route.request().url());if(url.href===new URL('verification/settings-peer.html',base).href)return route.fulfill({contentType:'text/html',body:'<!doctype html><title>Synthetic Settings lock peer</title>'});if(url.origin===new URL(base).origin)return route.continue();if(url.origin==='https://travellermap.com'&&url.pathname.startsWith('/api/')){assert.equal(url.searchParams.get('milieu'),'M1105');if(url.pathname.endsWith('/jumpworlds'))return route.fulfill({json:{Worlds:map.apiWorlds},headers:{'Access-Control-Allow-Origin':'*'}});if(url.pathname.endsWith('/universe'))return route.fulfill({json:map.universe,headers:{'Access-Control-Allow-Origin':'*'}});if(url.pathname.endsWith('/metadata'))return route.fulfill({json:map.metadata,headers:{'Access-Control-Allow-Origin':'*'}});if(url.pathname.endsWith('/sec'))return route.fulfill({body:map.sec,headers:{'Access-Control-Allow-Origin':'*'}});}result.unexpectedRequests.push(url.href);return route.abort('blockedbyclient');});return context;
}
async function installGate(page,result){
 result.runtime=await page.evaluate(async()=>{
  const appURL=[...document.scripts].find(s=>s.type==='module'&&/\/app\.mjs(?:\?|$)/.test(s.src))?.src;if(!appURL)throw Error('Runtime app module unavailable');const response=await fetch(appURL);if(!response.ok)throw Error('Cannot inspect runtime app');const source=await response.text(),specifier=source.match(/import\s*\{[^}]*\bStore\b[^}]*\}\s*from\s*['"]([^'"]*persistence\.mjs[^'"]*)['"]/u)?.[1];if(!specifier)throw Error('Actual Store import missing');const storeURL=new URL(specifier,appURL).href;if(!new URL(storeURL).search)throw Error('Expected versioned Store import');
  const {Store,KEY}=await import(storeURL),nativeSave=Store.prototype.save;
  const g=globalThis.settingsGate={armed:false,pending:null,store:null,args:null,calls:0,executions:0,reentrantReviews:[],notifyFault:null,cleanupFault:null,pendingUI:null,faults:[],candidates:[],forwarded:[],publications:[],observations:[],settlements:[],inlineForm:null,submittedForm:null,pendingNodes:null,pendingMarkup:null,oldSubmit:null,oldReset:null,submittedFields:null,mainBefore:null};
  const observation=point=>({point,message:document.querySelector('#message')?.textContent||'',open:!!document.querySelector('#modal')?.open,mainSame:document.querySelector('#main').innerHTML===g.mainBefore,formConnected:g.inlineForm?.isConnected??null,formMounted:document.querySelector('#settings-form')===g.inlineForm});
  const text=Object.getOwnPropertyDescriptor(Node.prototype,'textContent');Object.defineProperty(Node.prototype,'textContent',{...text,set(value){if(g.pendingUI&&this.id==='modal-title'&&value==='Saving Settings'){g.faults.push(g.pendingUI);g.pendingUI=null;throw Error('Synthetic pending Settings UI construction fault');}if(g.cleanupFault==='report'&&this.id==='message'&&/Ship \/ trader settings saved\./.test(value)){g.cleanupFault=null;g.faults.push('report');throw Error('Synthetic Settings success reporting fault');}return Reflect.apply(text.set,this,[value]);}});
  const html=Object.getOwnPropertyDescriptor(Element.prototype,'innerHTML');Object.defineProperty(Element.prototype,'innerHTML',{...html,set(value){if(g.cleanupFault==='render'&&this.id==='main'&&g.settlements.at(-1)?.kind==='native-fulfilled'){g.cleanupFault=null;g.faults.push('render');throw Error('Synthetic Settings cleanup render fault');}return Reflect.apply(html.set,this,[value]);}});
  const focus=HTMLElement.prototype.focus;HTMLElement.prototype.focus=function(...args){if(g.cleanupFault==='focus'&&this.id==='settings-save'&&g.settlements.at(-1)?.kind==='native-fulfilled'){g.cleanupFault=null;g.faults.push('focus');throw Error('Synthetic Settings cleanup focus fault');}return Reflect.apply(focus,this,args);};
  const close=HTMLDialogElement.prototype.close;HTMLDialogElement.prototype.close=function(...args){if(g.cleanupFault==='close'&&this.id==='modal'&&g.settlements.at(-1)?.kind==='native-fulfilled'){g.cleanupFault=null;g.faults.push('close');throw Error('Synthetic Settings native close fault');}return Reflect.apply(close,this,args);};
  function observeStore(store){if(g.store===store)return;if(g.store)throw Error('Unexpected second app Store');g.store=store;const change=store.onChange;store.onChange=function(...args){const publication={revision:args[0].revision,token:args[1]?.saveToken===g.args?.[2],actualCallback:false};g.publications.push(publication);g.observations.push(observation('before-publication'));if(g.notifyFault==='before'){g.notifyFault=null;throw Error('Synthetic notification before Settings publication');}if(g.notifyFault==='missing')return;const result=Reflect.apply(change,this,args);publication.actualCallback=true;g.observations.push(observation('after-publication'));if(g.notifyFault==='after'){g.notifyFault=null;throw Error('Synthetic notification after Settings publication');}return result;};}
  Store.prototype.save=function(...args){observeStore(this);g.args=args;if(!g.armed)return Reflect.apply(nativeSave,this,args);if(g.pending)throw Error('Duplicate Settings Store.save while pending');g.calls++;g.candidates.push(JSON.stringify(args[0]));g.forwarded.push({argumentCount:args.length,token:args[2]!=null,revision:args[0].revision,expected:args[1]});const before={title:document.querySelector('#modal-title').textContent,open:document.querySelector('#modal').open,form:document.querySelector('#settings-form')};document.querySelector('#notes').click();g.reentrantReviews.push({sameTitle:document.querySelector('#modal-title').textContent===before.title,sameOpen:document.querySelector('#modal').open===before.open,sameForm:document.querySelector('#settings-form')===before.form});const promise=new Promise((resolve,reject)=>{g.pending={store:this,args,resolve,reject,executed:false,error:null,result:undefined};});if(g.pendingUI==='after')g.write();return promise;};
  g.write=()=>{const p=g.pending;if(!p||p.executed)throw Error('Native Settings write must execute once');p.executed=true;g.executions++;try{p.result=Reflect.apply(nativeSave,p.store,p.args);}catch(error){p.error=error;}};
  g.release=kind=>{const p=g.pending;if(!p)throw Error('No pending Settings completion');if(kind==='unknown-before'){g.pending=null;g.settlements.push({kind,executed:false});p.reject(Error('Synthetic unknown Settings result'));return;}if(!p.executed)g.write();g.pending=null;if(kind==='unknown-after'||kind==='contradictory'){g.settlements.push({kind,executed:true});p.reject(kind==='contradictory'?Object.assign(Error('Contradictory prewrite result'),{code:'SAVE_NOT_COMMITTED',committed:false}):Error('Synthetic response lost after Settings save'));}else if(p.error){g.settlements.push({kind:'native-rejected',code:p.error.code,committed:p.error.committed});p.reject(p.error);}else{g.settlements.push({kind:'native-fulfilled',executed:true});p.resolve(p.result);}};
  g.remember=path=>{g.inlineForm=path==='inline'?document.querySelector('#settings-form'):null;const form=g.inlineForm||document.querySelector('#modal-form');g.submittedForm=form;g.oldSubmit=form.onsubmit;g.oldReset=document.querySelector('#settings-reset')?.onclick;g.submittedFields=[...form.querySelectorAll('[name]')].map(el=>[el.name,el.type==='checkbox'?el.checked:el.value]);g.mainBefore=document.querySelector('#main').innerHTML;};
  g.snapshot=()=>({calls:g.calls,executions:g.executions,reentrantReviews:g.reentrantReviews,pending:!!g.pending,editable:g.store?.editable??null,reloadRequired:!!g.store?.reloadRequired,storage:{...settingsStorage},candidates:g.candidates,forwarded:g.forwarded,publications:g.publications,observations:g.observations,settlements:g.settlements,faults:g.faults,inlineConnected:g.inlineForm?.isConnected??null,currentIsSubmitted:!!g.inlineForm&&document.querySelector('#settings-form')===g.inlineForm,pendingDOMSame:g.pendingNodes?[...document.querySelector('#main').childNodes].length===g.pendingNodes.length&&g.pendingNodes.every((node,i)=>document.querySelector('#main').childNodes[i]===node)&&document.querySelector('#main').innerHTML===g.pendingMarkup:null,submittedFields:g.submittedForm?[...g.submittedForm.querySelectorAll('[name]')].map(el=>[el.name,el.type==='checkbox'?el.checked:el.value]):g.submittedFields,durableToken:/"saveToken"\s*:/.test(localStorage.getItem(KEY))});return {appURL,storeURL};
 });
}
async function capture(page,result,label){await frames(page);const name='settings-completion-'+result.id+'-'+label+'.jpg';await page.screenshot({path:join(artifacts,name),type:'jpeg',quality:80});result.screenshots.push(name);const geometry=await page.evaluate(()=>{const d=document.querySelector('#modal[open]'),r=d?.getBoundingClientRect();return {width:innerWidth,pageOverflow:document.documentElement.scrollWidth-innerWidth,dialog:r?{left:r.left,right:r.right,overflow:d.scrollWidth-d.clientWidth}:null};});result.layouts.push({label,...geometry});assert.ok(geometry.pageOverflow<=2,'No horizontal page overflow');if(geometry.dialog){assert.ok(geometry.dialog.left>=-1&&geometry.dialog.right<=geometry.width+1,'Dialog within viewport');assert.ok(geometry.dialog.overflow<=2,'No dialog horizontal clipping');}}
const release=(page,kind='native')=>page.evaluate(kind=>settingsGate.release(kind),kind);
async function start(page,path){await page.evaluate(path=>settingsGate.remember(path),path);await page.locator(path==='inline'?'#settings-save':'#modal-submit').click();}
function economic(saved,before){for(const key of ['bank','ledger','lots','contracts','policies','snapshots','route','routeIndex','actual','hours','dateLabel','dashboardBaseline'])assert.deepEqual(saved[key],before[key],key);assert.equal(saved.revision,before.revision+1);assert.equal(saved.undo.length,before.undo.length+1);assert.equal(saved.ship.capacity,'161');assert.deepEqual(saved.ship.fuel,configureFuel(300,60,65,90,3));assert.deepEqual(saved.ship.lifeSupport,{capacityHours:840,stockUnits:{numerator:'55',denominator:'2'}});assert.equal(saved.ship.accommodation.passengers.middle,6);assert.equal(saved.ship.accommodation.passengers.high,3);assert.equal(saved.ship.mortgage.payment,'100001');assert.equal(saved.ship.maintenance.payment,'2001');assert.equal(saved.settings.creditStep,100);assert.deepEqual(dashboardData(saved).baseline,dashboardData(before).baseline);assert.equal(dashboardData(saved).operatingResult,dashboardData(before).operatingResult);const added=saved.events.slice(before.events.length);assert.ok(added.some(e=>e.label==='Mortgage settings audit'));assert.ok(added.some(e=>e.label==='Maintenance settings audit'));assert.ok(added.some(e=>e.label==='Rounding applied [R]'));}
async function replay(page,path){await page.evaluate(path=>{const g=settingsGate,form=g.inlineForm||document.querySelector('#modal-form');void g.oldSubmit({preventDefault(){},currentTarget:form});g.oldReset?.();form.requestSubmit();if(g.inlineForm){for(const node of g.inlineForm.querySelectorAll('input,select,button')){if(node.tagName==='BUTTON')node.click();else{node.dispatchEvent(new Event('input',{bubbles:true}));node.dispatchEvent(new Event('change',{bubbles:true}));}}}for(const [name,arg]of [['tab','Overview'],['refuel',''],['settings-edit',''],['reset','']])document.querySelector('[data-action="'+name+'"]'+(arg?'[data-arg="'+arg+'"]':''))?.click();},path);await page.keyboard.press('Enter');await page.keyboard.press('Escape');await frames(page);}
async function pending(page,result,scenario,bytes,prepared){
 await start(page,scenario.path);await page.waitForFunction(()=>!!settingsGate.pending);await frames(page);assert.equal(await raw(page),bytes);assert.doesNotMatch(await page.locator('#message').textContent(),successPattern);assert.equal(await page.locator('#modal').evaluate(el=>el.open),true);assert.equal(await page.locator('#modal-submit').isHidden(),scenario.path==='inline');if(scenario.path==='modal')assert.equal(await page.locator('#modal-submit').isDisabled(),true);for(const id of ['modal-cancel','modal-close'])assert.equal(await page.locator('#'+id).isDisabled(),true);
 if(scenario.path==='inline'){assert.equal(await page.locator('#settings-form').count(),0,'Only the submitted real form is suspended for pending UI');assert.equal((await gate(page)).inlineConnected,false);assert.ok(await page.evaluate(()=>[...settingsGate.inlineForm.querySelectorAll('input,select,textarea,button')].every(el=>el.disabled)),'Every submitted input, checkbox, select, stepper and Revert is disabled');}
 await page.evaluate(()=>{settingsGate.pendingNodes=[...document.querySelector('#main').childNodes];settingsGate.pendingMarkup=document.querySelector('#main').innerHTML;});for(const id of ['modal-submit','modal-cancel','modal-close']){const button=page.locator('#'+id);if(await button.isVisible()){await button.scrollIntoViewIfNeeded();const box=await button.boundingBox();await page.mouse.click(box.x+box.width/2,box.y+box.height/2,{clickCount:2,delay:20});}}await replay(page,scenario.path);assert.equal((await gate(page)).calls,1);assert.deepEqual((await gate(page)).reentrantReviews,[{sameTitle:true,sameOpen:true,sameForm:true}],'Owner blocks a genuine notes callback synchronously inside provider invocation');assert.equal(await raw(page),bytes);assert.equal(await page.locator('#modal').evaluate(el=>el.open),true);assert.deepEqual(Object.fromEntries((await gate(page)).submittedFields),prepared.values,'Pending gestures cannot mutate normalized submitted controls');await capture(page,result,'pending');result.checks.push('One pending write; real submitted form retained; duplicate click, Enter, controls, Revert and navigation blocked');
}
async function reloadUndo(page,result,before,{committed=true}={}){const bytes=await raw(page);await page.reload();await page.getByText('Editing in this tab',{exact:true}).waitFor();assert.equal(await raw(page),bytes);assert.equal(await page.evaluate(()=>settingsStorage.writes),0);if(committed){economic(await read(page),before);await tab(page,'History');await page.locator('#main [data-action="undo"]').click();await closed(page);const undone=await read(page);for(const key of ['name','ship','trader','settings','bank','ledger','lots','contracts','policies','route','actual','hours','dashboardBaseline'])assert.deepEqual(undone[key],before[key],key+' after real History Undo');assert.equal(undone.undo.length,before.undo.length);assert.equal(await page.evaluate(()=>settingsStorage.writes),1);}else assert.deepEqual(await read(page),before);await capture(page,result,'reload-undo');result.checks.push('Reload does not repeat Settings; actual History Undo restores prior fields, stock, economics and Dashboard baseline');}
async function success(page,result,scenario,before,prepared){
 await closed(page);const snapshot=await gate(page);result.gate=snapshot;const saved=await read(page);economic(saved,before);assert.equal(await raw(page),snapshot.candidates.at(-1));assert.equal(snapshot.storage.writes,1);assert.equal(snapshot.durableToken,false);assert.match(await page.locator('#message').textContent(),successPattern);for(const item of snapshot.forwarded){assert.ok(item.argumentCount>=3);assert.equal(item.token,true);assert.equal(item.revision,item.expected+1);}for(const item of [...snapshot.observations,...snapshot.storage.observations])assert.doesNotMatch(item.message,successPattern,'No success before completion');
 if(scenario.path==='inline'){assert.equal(snapshot.currentIsSubmitted,false,'Successful completion remounts after settlement');assert.deepEqual(await disclosures(page),prepared.groups);assert.equal(await page.locator('#settings-save').evaluate(el=>el===document.activeElement),true);assert.equal((await values(page)).name,draft.name);}
 else{assert.equal((await values(page)).name,'Unrelated dirty inline draft','Legacy save must preserve unrelated inline draft');const bytes=await raw(page);await page.locator('#settings-save').click();assert.equal(await raw(page),bytes);assert.match(await page.locator('#settings-error').textContent(),/changed.*Revert/i);await page.locator('#settings-reset').click();assert.equal((await values(page)).name,draft.name);}
 const bytes=await raw(page),calls=snapshot.calls;await page.evaluate(()=>{void settingsGate.oldSubmit({preventDefault(){},currentTarget:settingsGate.inlineForm||document.querySelector('#modal-form')});settingsGate.oldReset?.();});await frames(page);assert.equal(await raw(page),bytes);assert.equal((await gate(page)).calls,calls);await capture(page,result,'completed');await reloadUndo(page,result,before);
}
async function terminal(page,result,before,{committed}){
 await page.waitForFunction(()=>/Reload/.test(document.querySelector('#save-status').textContent));await frames(page);assert.equal((await gate(page)).editable,false);assert.equal((await gate(page)).reloadRequired,true);assert.equal(await page.locator('#takeover').isDisabled(),true);assert.doesNotMatch(await page.locator('#message').textContent(),successPattern);if(committed)economic(await read(page),before);else assert.deepEqual(await read(page),before);
 const bytes=await raw(page),unexpectedNavigations=[];const recordNavigation=frame=>{if(frame===page.mainFrame())unexpectedNavigations.push(frame.url());};page.on('framenavigated',recordNavigation);try{await page.evaluate(()=>{void settingsGate.oldSubmit?.({preventDefault(){},currentTarget:settingsGate.inlineForm||document.querySelector('#modal-form')});document.querySelector('#modal-form').requestSubmit();});await frames(page);assert.deepEqual(unexpectedNavigations,[],'Terminal native modal submission must not navigate, including partial pending-screen construction');assert.equal(await raw(page),bytes);assert.equal((await gate(page)).calls,1);}finally{page.off('framenavigated',recordNavigation);result.terminalReplayNavigations=unexpectedNavigations;}await page.waitForFunction(async lock=>(await navigator.locks.query()).held.every(item=>item.name!==lock),LOCK);assert.equal(await page.evaluate(lock=>navigator.locks.request(lock,{ifAvailable:true},held=>!!held),LOCK),true);result.gate=await gate(page);await capture(page,result,'reload-only');await reloadUndo(page,result,before,{committed});result.checks.push('Terminal outcome releases actual writer lock and blocks all replay until reload');
}
async function editorRegain(page,result,context){
 const peer=await context.newPage();await peer.goto(new URL('verification/settings-peer.html',base).href);await peer.evaluate(async({storeURL})=>{const {Store}=await import(storeURL);globalThis.settingsPeer={editable:false};settingsPeer.store=new Store(()=>{},editable=>settingsPeer.editable=editable);await settingsPeer.store.acquire(true);},result.runtime);await peer.waitForFunction(()=>settingsPeer.editable);await page.waitForFunction(()=>settingsGate.store.editable===false);await peer.evaluate(()=>{settingsPeer.store.yield();settingsPeer.store.channel?.close();});await peer.close();await page.evaluate(()=>settingsGate.store.acquire(true));await page.waitForFunction(()=>settingsGate.store.editable===true);result.checks.push('Actual second Store takes and releases native writer lock; production editor callback runs on loss and reacquisition');
}
async function runBody(page,result,scenario,context){
 await page.goto(base);await page.getByText('Editing in this tab',{exact:true}).waitFor();await frames(page);await installGate(page,result);const prepared=await prepare(page,scenario.path),before=await read(page),bytes=await raw(page);
 if(scenario.mode==='sync'){await start(page,'inline');assert.equal(await page.locator('#modal').evaluate(el=>el.open),false);economic(await read(page),before);assert.match(await page.locator('#message').textContent(),successPattern);assert.equal((await gate(page)).calls,0);assert.equal(await page.evaluate(()=>settingsStorage.writes),1);assert.deepEqual(await disclosures(page),prepared.groups);await capture(page,result,'synchronous');await reloadUndo(page,result,before);return;}
 if(scenario.mode==='validation'){
  for(const [name,value,native]of [['jump','0',true],['shipTons','',false],['capacity','1',false],['supportRemaining','',false]]){await setField(page,'inline',name,value);await page.locator('#main details[data-settings-group]').evaluateAll(nodes=>nodes.forEach(el=>el.open=false));await page.locator('#settings-save').click();assert.equal(await raw(page),bytes);assert.equal((await gate(page)).calls,0);if(native)assert.equal(await page.locator('#settings-form [name="'+name+'"]').evaluate(el=>el===document.activeElement&&el.closest('details').open),true);else{assert.ok(await page.locator('#settings-error').textContent());assert.equal(await page.locator('#settings-error').evaluate(el=>el===document.activeElement),true);assert.ok((await page.locator('#settings-form details[data-settings-group]').evaluateAll(nodes=>nodes.map(el=>el.open))).every(Boolean));}await setField(page,'inline',name,prepared.values[name]);}
  await capture(page,result,'validation');result.checks.push('Native and cross-field errors focus/reveal the retained form and never write');return;
 }
 await page.evaluate(({mode})=>{settingsGate.armed=true;settingsGate.notifyFault=mode==='notification-before'?'before':mode==='notification-after'?'after':mode==='missing'?'missing':null;settingsStorage.failNext=mode==='prewrite';if(mode.startsWith('pending-ui-'))settingsGate.pendingUI=mode.endsWith('after')?'after':'before';},scenario);
 if(scenario.mode.startsWith('pending-ui-')){await start(page,'inline');await page.waitForFunction(()=>settingsGate.faults.length===1&&settingsGate.store.reloadRequired);const committed=scenario.mode.endsWith('after'),durable=await raw(page);if(committed)economic(await read(page),before);else assert.equal(durable,bytes);await release(page);await frames(page);assert.equal(await raw(page),durable);await terminal(page,result,before,{committed});return;}
 await pending(page,result,scenario,bytes,prepared);
 if(scenario.mode==='prewrite'){
  await release(page);await page.locator('#modal-error').filter({hasText:'Synthetic known Settings prewrite'}).waitFor();assert.equal(await raw(page),bytes);assert.equal((await gate(page)).reloadRequired,false);assert.equal(await page.locator('#modal-cancel').isEnabled(),true);await capture(page,result,'retryable');
  if(scenario.path==='inline'){await page.locator('#modal-cancel').click();await closed(page);assert.equal((await gate(page)).currentIsSubmitted,true,'Known failure restores the exact submitted DOM form');assert.deepEqual(await values(page),prepared.values);assert.deepEqual(await disclosures(page),prepared.groups);await setField(page,'inline','name','Correction after failed write');prepared.values.name='Correction after failed write';await start(page,'inline');}else{await setField(page,'modal','name','Correction after failed write');prepared.values.name='Correction after failed write';await start(page,'modal');}
  await page.waitForFunction(()=>!!settingsGate.pending);assert.equal((await gate(page)).calls,2);await release(page);await closed(page);assert.equal((await read(page)).name,'Correction after failed write');assert.equal((await gate(page)).storage.writes,1);assert.equal((await gate(page)).storage.attempts,2);economic(await read(page),before);await capture(page,result,'corrected-retry');await reloadUndo(page,result,before);return;
 }
 if(['foreign','editor-regain','detached','stale-disk'].includes(scenario.mode)){
  if(scenario.mode==='foreign')await page.evaluate(()=>settingsGate.store.onChange(settingsGate.store.read()));
  if(scenario.mode==='editor-regain')await editorRegain(page,result,context);
  if(scenario.mode==='detached')await page.evaluate(()=>{const dialog=document.querySelector('#modal');dialog.close();dialog.dispatchEvent(new Event('close'));});
  if(scenario.mode==='stale-disk')await page.evaluate(async({storeURL,key})=>{const url=new URL('state.mjs',storeURL);url.search=new URL(storeURL).search;const S=await import(url.href),next=S.transition(settingsGate.store.read(),'External deposit',s=>S.deposit(s,7,'Synthetic newer disk'));localStorage.setItem(key,JSON.stringify(next));},{...result.runtime,key:KEY});
  const current=await raw(page);await release(page);await frames(page);assert.doesNotMatch(await page.locator('#message').textContent(),successPattern);if(scenario.mode==='stale-disk'){assert.equal(await raw(page),current);assert.equal((await gate(page)).settlements.at(-1).code,'SAVE_NOT_COMMITTED');}else economic(await read(page),before);
  const durable=await raw(page);assert.equal((await gate(page)).calls,1);if(scenario.mode==='detached')assert.equal(await page.locator('#modal').evaluate(el=>el.open),false);else{assert.equal(await page.locator('#modal-submit').isHidden(),true,'Inline pending/recovery dialog has no submit action');if(scenario.mode==='stale-disk'){assert.match(await page.locator('#modal-error').textContent(),/stale/i);await page.evaluate(()=>{document.querySelector('#modal-form').requestSubmit();void settingsGate.oldSubmit({preventDefault(){},currentTarget:settingsGate.inlineForm});});await frames(page);assert.equal((await gate(page)).calls,1,'Known stale-disk failure never replays from its non-submit status dialog');assert.equal(await raw(page),durable);}else assert.equal(await page.locator('#modal-submit').isDisabled(),true);await page.locator('#modal-cancel').click();await closed(page);}assert.equal(await page.locator('#settings-reset').isEnabled(),true,'Retired owner must not leave Revert frozen');for(const name of ['name','jump','scoops','mode'])assert.equal(await page.locator('#settings-form [name="'+name+'"]').isEnabled(),true,'Retired owner unlocks '+name+' before Revert/remount');if(['foreign','editor-regain'].includes(scenario.mode)){await setField(page,'inline','name','An edit cannot revive stale ownership');await page.locator('#settings-save').click();assert.equal(await raw(page),durable);assert.equal((await gate(page)).calls,1);assert.match(await page.locator('#settings-error').textContent(),/changed.*Revert/i);}await page.locator('#settings-reset').click();assert.equal(await page.locator('#settings-form [name="name"]').isEnabled(),true);assert.equal(await page.locator('#settings-form [name="jump"]').isEnabled(),true);assert.equal(await page.locator('#settings-form [name="scoops"]').isEnabled(),true);assert.equal(await page.locator('#settings-form [name="mode"]').isEnabled(),true);assert.equal((await values(page)).name,(await read(page)).name);await page.locator('#main [data-action="settings-edit"]').click();await page.locator('#modal-title').filter({hasText:'Ship, trader & options'}).waitFor();await page.evaluate(()=>{void settingsGate.oldSubmit({preventDefault(){},currentTarget:settingsGate.inlineForm});settingsGate.oldReset?.();});assert.equal(await page.locator('#modal-title').textContent(),'Ship, trader & options');assert.equal(await page.locator('#modal-error').textContent(),'');assert.equal(await raw(page),durable);result.gate=await gate(page);await capture(page,result,'retired-owner');result.checks.push('Obsolete completion cannot clear, remount, focus, report success, replay or close a newer Settings review');return;
 }
 if(['render','focus','close','report'].includes(scenario.mode))await page.evaluate(mode=>settingsGate.cleanupFault=mode,scenario.mode);
 if(scenario.mode==='success'){
  const retained=await gate(page);await page.evaluate(()=>settingsGate.write());await frames(page);economic(await read(page),before);assert.equal(await page.locator('#modal').evaluate(el=>el.open),true);assert.doesNotMatch(await page.locator('#message').textContent(),successPattern);assert.deepEqual((await gate(page)).submittedFields,retained.submittedFields);if(scenario.path==='inline'){assert.equal((await gate(page)).pendingDOMSame,true,'Owned publication cannot rerender or replace the suspended form placeholder');assert.equal((await gate(page)).inlineConnected,false);assert.equal(await page.locator('#settings-form').count(),0);assert.equal(await page.evaluate(()=>document.activeElement?.id==='settings-save'),false);}await capture(page,result,'durable-pending');await release(page);await success(page,result,scenario,before,prepared);return;
 }
 const kind=['unknown-before','unknown-after','contradictory'].includes(scenario.mode)?scenario.mode:'native';await release(page,kind);await terminal(page,result,before,{committed:scenario.mode!=='unknown-before'});if(['render','focus','close','report'].includes(scenario.mode))assert.deepEqual(result.gate.faults,[scenario.mode]);
}
async function writeReport(){await writeFile(join(artifacts,'settings-completion-report.json'),JSON.stringify(report,null,2)+'\n');}
async function runCase(scenario,viewport){const result={id:scenario.id+'-'+viewport.width,...scenario,viewport,status:'running',checks:[],screenshots:[],layouts:[],pageErrors:[],unhandledRejections:[],consoleErrors:[],networkErrors:[],unexpectedRequests:[],errors:[]};result.id=scenario.id+'-'+viewport.width;report.cases.push(result);let context;try{context=await contextFor(result);const page=await context.newPage();await runBody(page,result,scenario,context);await frames(page);for(const key of ['pageErrors','unhandledRejections','consoleErrors','networkErrors','unexpectedRequests'])assert.deepEqual(result[key],[],key);result.status='passed';}catch(error){result.status='failed';result.errors.push(errorText(error));const page=context?.pages()[0];if(page){await capture(page,result,'failure').catch(()=>{});result.failedGate=await gate(page).catch(()=>null);}}finally{await context?.close();await writeReport();}console.log(result.status.toUpperCase()+': '+result.id);for(const error of result.errors)console.error(error);}
if(process.argv.includes('--fixtures-only')){
 const s=fixture();S.validate(s);assert.equal(s.ship.lifeSupport.elapsedHours,6);assert.equal(s.policies.length,1);assert.deepEqual(Object.keys(draft).sort(),settingsGroups.flatMap(g=>g.names).sort());assert.equal(Object.keys(draft).length,51);assert.equal(new Set(scenarios.map(s=>s.id)).size,scenarios.length);assert.equal(dashboardData(s).currentBank,s.bank);const html=await readFile(new URL('../index.html',import.meta.url),'utf8'),app=await readFile(new URL('../js/app.mjs',import.meta.url),'utf8');assert.match(html,/<script type="module" src="js\/app\.mjs\?[^\"]+"/);assert.match(app,/import\s*\{[^}]*\bStore\b[^}]*\}\s*from\s*['"]\.\/persistence\.mjs\?[^'"]+['"]/);assert.match(app,/function completeSettingsWrite\(owner,data\)/);assert.match(app,/function awaitInlineSettings\(owner,result\)/);assert.match(app,/saveContext:'settings-save'/);console.log(`PASS: Settings synthetic fixtures, 51-field inventory, exact versioned Store discovery and production completion wiring; ${scenarios.length} scenarios x ${sizes.length} widths = ${report.declaredCases} declared browser cases. Chromium was not launched.`);
}else{
 await mkdir(artifacts,{recursive:true});try{report.testedCommit=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim();if(report.requestedCommit)assert.equal(report.testedCommit,report.requestedCommit);const {chromium}=createRequire(import.meta.url)(process.argv[2]||'playwright');browser=await chromium.launch({headless:true,...(process.env.TRAVELLER_BROWSER_CHANNEL?{channel:process.env.TRAVELLER_BROWSER_CHANNEL}:{})});report.browser={name:'Chromium',version:browser.version()};for(const viewport of sizes)for(const scenario of scenarios)await runCase(scenario,viewport);const files=(await readdir(artifacts)).filter(name=>name.startsWith('settings-completion-'));report.screenshotCount=files.filter(name=>name.endsWith('.jpg')).length;report.artifactBytes=(await Promise.all(files.map(async name=>(await stat(join(artifacts,name))).size))).reduce((a,b)=>a+b,0);assert.ok(report.artifactBytes<24*1024*1024-65536,'Bound Settings evidence below 24 MiB');}catch(error){report.errors.push(errorText(error));}finally{await browser?.close();report.finishedAt=new Date().toISOString();report.passed=report.errors.length===0&&report.cases.length===report.declaredCases&&report.cases.every(c=>c.status==='passed');await writeReport();}if(!report.passed)throw Error('Settings completion browser checks failed; see verification-artifacts/settings-completion-report.json');console.log(`PASS: ${report.declaredCases} actual inline/modal Settings cases with native locking, exact economics, reload/Undo and desktop/mobile JPEG evidence.`);
}
