import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {S,same,ui,flush} from './deposit-save-harness.mjs';
import {serviceSaveGate} from './service-save-harness.mjs';
import {guiFixture} from './fixtures/gui-parity.mjs';
import {configureFuel} from '../js/fuel.mjs';
import {dashboardData} from '../js/dashboard-data.mjs';

// Production setup/location callbacks, campaign controller, transition and Store.
// Only DOM, map transport and private storage are doubled. The companion suite
// owns actual picker DOM, native requestSubmit, Chromium, layout and Web Locks.
const harnessURL=new URL('./app-harness.mjs',import.meta.url),storageURL=new URL('./deposit-save-harness.mjs',import.meta.url);
const app=await readFile(new URL('../js/app.mjs',import.meta.url),'utf8');
const marker='store=new Store(receiveCampaign,',roleStart=app.indexOf(marker);assert.ok(roleStart>=0);
const roleCallback=app.slice(roleStart+marker.length).split(');try{state=store.read();}')[0];assert.ok(roleCallback.startsWith('(editable,text)=>'));
const absolutize=(source,url)=>source.replaceAll('import.meta.url',JSON.stringify(url.href)).replace(/from '(\.[^']+)'/g,(_all,path)=>'from '+JSON.stringify(new URL(path,url).href));
let harnessSource=absolutize(await readFile(harnessURL,'utf8'),harnessURL);
function replace(source,from,to){assert.ok(source.includes(from),'Expected harness boundary '+from);return source.replace(from,to);}
harnessSource=replace(harnessSource,'clearTimeout:cancel=clearTimeout}={}','$MAP$');
harnessSource=harnessSource.replace('$MAP$','clearTimeout:cancel=clearTimeout,mapControl}={}');
harnessSource=replace(harnessSource,'...bindings,R:rules,document:dom.document','...bindings,M:{...bindings.M,nearby:(...args)=>mapControl.nearby(...args)},createWorldPicker:(...args)=>mapControl.createPicker(...args),createGlobalWorldSearch:()=>({}),R:rules,document:dom.document');
harnessSource=replace(harnessSource,"'takeover','import-file'","'takeover','setup-world','find-world','global-world-search','choose-starting-world','import-file'");
harnessSource=replace(harnessSource,'globalThis.api={setStore','globalThis.api={setup,setLocation,findWorld,roleChange:'+roleCallback+',setStore');
const harnessModule='data:text/javascript;base64,'+Buffer.from(harnessSource).toString('base64');
let storageSource=absolutize(await readFile(storageURL,'utf8'),storageURL);
storageSource=replace(storageSource,JSON.stringify(harnessURL.href),JSON.stringify(harnessModule));
const {depositHarness}=await import('data:text/javascript;base64,'+Buffer.from(storageSource).toString('base64'));
const fixtureMap=guiFixture(),target=fixtureMap.state.worlds[fixtureMap.state.route[5]];
const opening='900719925474099312345678901234567890.1',roundedOpening='900719925474099312345678901234567891';
const setupDraft={name:'Synthetic completion campaign',ship:'Exact Credit Trader',bank:opening,capacity:'160.1',jump:'3',date:'032-1105',shipTons:'300',fuelCapacity:'60',fuelAboard:'65',bladderTons:'90','rooms-middle':'4','people-middle':'2',supportCapacity:'28',supportRemaining:'14',supportUnits:'28'};
const reason='Correct independently verified starting coordinates';
function fixture({jump=true,legacy=true}={}){
 let s=guiFixture().state;
 s.ship.fuel=configureFuel(200,40,60,40,2);s.ship.lifeSupport={capacityHours:672,stockUnits:{numerator:'560',denominator:'1'}};
 s.contracts.push({id:'location-mail',kind:'mail',status:'accepted',origin:s.actual,destination:s.route[4],quantity:'5',payment:'9007199254740993',dueHours:null,firstDeparture:null,audit:{manual:true,reason:'Saved mail terms'}});
 s.policies=[{id:'location-policy',lotId:'lot-opening',claims:[],status:'active',initialQuantity:'2',remainingQuantity:'2',insuredValue:'2000',remainingValue:'2000',coverage:70,route:s.route.slice(s.routeIndex),routeProgress:0,destination:s.route.at(-1)}];
 s=S.transition(s,'Passenger capacity',n=>S.configurePassengerCapacity(n,{reservedCabins:2,installedLowBerths:2}));
 const offers=['low','basic','middle','high'].map((passageClass,i)=>({offerId:'location-passage-'+i,passageClass,count:2,fare:String(1000+i*1000),origin:s.actual,destination:s.route[3],audit:{synthetic:true}}));
 s=S.transition(s,'Passenger search',n=>S.recordPassengerSearch(n,{id:'location-search',label:'Passenger search audit',hours:n.hours,world:n.actual,destination:n.route[3],offers}));
 s=S.transition(s,'Accepted passenger booking',n=>S.acceptPassengers(n,'location-passage-2',{count:1,cabinMode:'private',serviceConfirmed:true,spaceConfirmed:true}));
 if(jump){const commit=(state,face)=>{const p=S.prepareJump(state,()=>({dice:Array(6).fill(face),total:face*6}));return S.transition(p.state,'Saved jump',n=>S.commitJump(n,{attemptId:p.attempt.id,elapsed:160}));};s=commit(S.undoJump(commit(s,3)),2);}
 if(legacy)s.ship.lifeSupport={capacityHours:672,remainingHours:336,elapsedHours:6};
 return S.validate(s);
}
function mapControl(){
 const calls={resolve:0,nearby:0,create:0},queues={resolve:[],nearby:[]};
 function consume(kind,fallback,args){calls[kind]++;const queued=queues[kind].shift();return queued?queued(...args):Promise.resolve(fallback);}
 return {calls,pickers:[],selected:target,createPicker(){calls.create++;const picker={resolve:()=>consume('resolve',this.selected,[])};this.pickers.push(picker);return picker;},nearby(...args){return consume('nearby',Object.values(fixtureMap.state.worlds),args);},fail(kind,message){queues[kind].push(()=>Promise.reject(Error(message)));},hold(kind){let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no;});promise.catch(()=>{});queues[kind].push(()=>promise);return {resolve:value=>resolve(value??(kind==='resolve'?this.selected:Object.values(fixtureMap.state.worlds))),reject:(error=Error('Synthetic map lookup failure'))=>reject(error)};}};
}
function setup(path='location',saved=path==='setup'?S.initial():fixture()){
 const map=mapControl(),h=depositHarness(saved,{setTimeout:()=>0,clearTimeout(){},mapControl:map});
 h.hooks.onRole=(editable,text)=>h.api.roleChange(editable,text);
 const form=h.dom.ids.get('modal-form'),query=form.querySelectorAll;form.querySelectorAll=selector=>selector==='input,select,textarea,button'?[...h.dom.fields().values()]:query(selector);
 return {...h,map,path};
}
async function open(h,edits={}){if(h.path==='setup'){await h.api.setup();h.fill({...setupDraft,...edits});assert.equal(ui(h).modalTitle,'Start your campaign');}else{h.api.setLocation(target);h.fill({reason,...edits});assert.equal(ui(h).modalTitle,'Set ship location');}}
const fields=h=>Object.fromEntries([...h.dom.fields()].map(([name,field])=>[name,field.attributes.type==='checkbox'?field.checked:field.value]));
const event=h=>({preventDefault(){},currentTarget:h.dom.ids.get('modal-form')});
const successPattern=/Campaign setup saved\.|Ship location set:.*saved\./;
const noSuccess=h=>assert.doesNotMatch(ui(h).message,successPattern);
function busy(h,session){assert.equal(h.api.modalSession,session);assert.equal(ui(h).modalOpen,true);assert.equal(session.busy,true);assert.equal(session.awaitSave,true);assert.equal(ui(h).submitDisabled,true);for(const id of ['modal-close','modal-cancel'])assert.equal(h.dom.ids.get(id).disabled,true);noSuccess(h);}
function terminal(h){assert.equal(h.store.reloadRequired,true);assert.equal(h.store.editable,false);assert.equal(ui(h).submitDisabled,true);assert.equal(h.dom.ids.get('takeover').disabled,true);for(const id of ['message','save-status'])assert.match(h.dom.ids.get(id).textContent,/reload/i);if(ui(h).modalOpen)assert.match(ui(h).modalError,/reload/i);noSuccess(h);}
function canonical(value){const ids=new Map();return JSON.parse(JSON.stringify(value,(_key,v)=>{if(typeof v==='string'&&/^[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}$/i.test(v)){if(!ids.has(v))ids.set(v,'generated-'+ids.size);return ids.get(v);}return v;}));}
function exact(h,before,entry){same(h.persisted(),entry.args[0]);same(h.api.state,entry.args[0]);assert.equal(h.persisted().revision,before.revision+1);assert.equal(h.persisted().undo.length,before.undo.length+1);assert.equal(h.counters.writes,1);assert.equal(entry.args[1],before.revision);assert.ok(entry.args[2]);assert.doesNotMatch(h.bytes(),/saveToken|replacementToken/);}
function economics(h,before){const saved=h.persisted();
 if(h.path==='setup'){assert.equal(saved.initialized,true);assert.equal(saved.bank,roundedOpening);assert.equal(saved.ship.capacity,'161');assert.equal(saved.actual,target.id);same(saved.route,[target.id]);assert.equal(saved.ledger.length,1);assert.equal(saved.ledger[0].type,'Opening bank');assert.equal(saved.ledger[0].amount,roundedOpening);assert.equal(saved.dashboardBaseline.origin,'opening');assert.equal(saved.dashboardBaseline.bank,roundedOpening);same(saved.dashboardBaseline.excludedLedgerIds,[saved.ledger[0].id]);const d=dashboardData(saved);assert.equal(d.currentBank,roundedOpening);assert.equal(d.operatingResult,'0');assert.equal(d.adjustment,'0');assert.equal(d.otherInflows,'0');assert.equal(d.cashPoints.length,1);assert.ok(saved.events.some(e=>e.label==='Rounding applied [R]'));}
 else{for(const key of ['name','bank','ledger','lots','contracts','snapshots','hours','dateLabel','dashboardBaseline','trader','settings'])same(saved[key],before[key]);assert.equal(saved.actual,target.id);same(saved.route,[target.id]);assert.equal(saved.routeIndex,0);same(saved.mandatoryStops,[]);const policies=structuredClone(before.policies);for(const p of policies)if(p.status==='active')p.status='amendment-required';same(saved.policies,policies);assert.ok(saved.events.slice(before.events.length).some(e=>e.label==='Starting-world / location correction'&&e.from===before.actual&&e.to===target.id&&e.reason===reason&&e.hours===before.hours));same(dashboardData(saved),dashboardData(before));for(const [i,attempt]of before.jumpAttempts.entries()){same(saved.jumpAttempts[i].rolls,attempt.rolls);assert.equal(saved.jumpAttempts[i].mulliganUsed,attempt.mulliganUsed);}const ship=structuredClone(saved.ship);delete ship.lifeSupport;const oldShip=structuredClone(before.ship);delete oldShip.lifeSupport;same(ship,oldShip);}
}
async function pending(t,path,h=setup(path),edits={}){const before=structuredClone(h.api.state),raw=h.bytes();await open(h,edits);const gate=serviceSaveGate(h.store),detached=h.dom.ids.get('modal-form').onsubmit,operation=h.submit();await flush();assert.equal(gate.entries.length,1,'Production callback enters deferred real Store exactly once');t.after(async()=>{for(const entry of gate.entries)if(!entry.settled)entry.fulfill();await operation;gate.restore();});return {h,before,raw,gate,operation,detached,session:h.api.modalSession};}

for(const path of ['setup','location'])test(`${path} immediate Store completes with one revision and Undo; no provider replacement semantics`,async()=>{const h=setup(path),before=h.persisted();await open(h);await h.submit();await flush();assert.equal(h.counters.writes,1);assert.equal(h.persisted().revision,before.revision+1);assert.equal(h.persisted().undo.length,before.undo.length+1);assert.equal(ui(h).modalOpen,false);economics(h,before);assert.match(ui(h).message,successPattern);});
for(const path of ['setup','location'])test(`${path} lookup, durable publication and settlement are separate and sync/delayed candidates match`,async t=>{const h=setup(path),before=h.persisted(),raw=h.bytes();await open(h);const lookup=h.map.hold(path==='setup'?'resolve':'nearby'),gate=serviceSaveGate(h.store),operation=h.submit(),session=h.api.modalSession;await flush();assert.equal(gate.entries.length,0);assert.equal(h.bytes(),raw);assert.equal(session.busy,true);assert.equal(session.awaitSave,false);for(const id of ['modal-cancel','modal-close'])assert.equal(h.dom.ids.get(id).disabled,false);lookup.resolve();await flush();assert.equal(gate.entries.length,1);busy(h,session);const retained=fields(h),rounding=structuredClone(h.api.inputRounding);gate.entries[0].write();exact(h,before,gate.entries[0]);economics(h,before);busy(h,session);same(fields(h),retained);same(h.api.inputRounding,rounding);gate.entries[0].fulfill();await operation;await flush();assert.equal(ui(h).modalOpen,false);assert.match(ui(h).message,successPattern);const sync=setup(path,before);await open(sync);await sync.submit();await flush();same(canonical(h.persisted()),canonical(sync.persisted()));for(const observation of h.trace)assert.doesNotMatch(observation.message,successPattern);gate.restore();t.after(()=>gate.restore());});
for(const path of ['setup','location'])for(const dismissal of ['Cancel','Close','Escape'])test(`${path} ${dismissal} during lookup makes late resolution harmless`,async()=>{const h=setup(path),raw=h.bytes();await open(h);const lookup=h.map.hold(path==='setup'?'resolve':'nearby'),gate=serviceSaveGate(h.store),operation=h.submit(),detached=h.dom.ids.get('modal-form').onsubmit;await flush();if(dismissal==='Escape'){let prevented=false;h.dom.ids.get('modal').dispatch('cancel',{preventDefault(){prevented=true;}});assert.equal(prevented,true);assert.equal(ui(h).modalOpen,false);}else h.dom.ids.get(dismissal==='Cancel'?'modal-cancel':'modal-close').onclick();lookup.resolve();await operation;assert.equal(ui(h).modalOpen,false);assert.equal(h.bytes(),raw);assert.equal(gate.entries.length,0);await detached(event(h));assert.equal(gate.entries.length,0);noSuccess(h);gate.restore();});
for(const path of ['setup','location'])test(`${path} pending save blocks duplicate, reentrant, detached submission, dismissal and replacement`,async t=>{const {h,raw,gate,operation,session,detached}=await pending(t,path),body=h.dom.ids.get('modal-body').innerHTML;await h.submit();await detached(event(h));h.dom.ids.get('modal-cancel').onclick();h.dom.ids.get('modal-close').onclick();let blocked=false;h.dom.ids.get('modal').dispatch('cancel',{preventDefault(){blocked=true;}});assert.equal(blocked,true);h.api.modal('Unrelated review','Keep pending operation',null);await h.runAction('reset');busy(h,session);assert.equal(h.dom.ids.get('modal-body').innerHTML,body);assert.equal(h.bytes(),raw);assert.equal(gate.entries.length,1);gate.entries[0].fulfill();await operation;const bytes=h.bytes();await detached(event(h));assert.equal(h.bytes(),bytes);assert.equal(gate.entries.length,1);});
for(const path of ['setup','location'])test(`${path} known prewrite rejection retains fields and allows one corrected explicit retry`,async t=>{const {h,raw,before,gate,operation,session,detached}=await pending(t,path),retained=fields(h),rounding=structuredClone(h.api.inputRounding);h.failNext();gate.entries[0].fulfill();await operation;assert.equal(h.bytes(),raw);same(h.api.state,before);same(fields(h),retained);same(h.api.inputRounding,rounding);assert.equal(h.api.modalSession,session);assert.match(ui(h).modalError,/quota/i);assert.equal(ui(h).submitDisabled,false);assert.equal(h.store.reloadRequired??false,false);h.fill(path==='setup'?{name:'Corrected setup after quota'}:{reason:'Corrected explicit retry'});const retry=h.submit();await flush();assert.equal(gate.entries.length,2);await detached(event(h));assert.equal(gate.entries.length,2);gate.entries[1].fulfill();await retry;assert.equal(h.counters.attempts,2);assert.equal(h.counters.writes,1);assert.equal(h.persisted().undo.length,before.undo.length+1);if(path==='setup')assert.equal(h.persisted().name,'Corrected setup after quota');else assert.ok(h.persisted().events.some(e=>e.reason==='Corrected explicit retry'));});
for(const path of ['setup','location'])test(`${path} map prewrite failure retains exact fields, calls no provider, and retries corrected data`,async()=>{const h=setup(path),raw=h.bytes();await open(h);const gate=serviceSaveGate(h.store);h.map.fail(path==='setup'?'resolve':'nearby','Synthetic Traveller Map 503');const failed=h.submit(),retained=fields(h);await failed;assert.equal(h.bytes(),raw);assert.equal(gate.entries.length,0);same(fields(h),retained);assert.match(ui(h).modalError,/503/);assert.equal(ui(h).submitDisabled,false);assert.equal(h.store.reloadRequired??false,false);h.fill(path==='setup'?{name:'Corrected map retry'}:{reason:'Corrected map retry'});const operation=h.submit();await flush();assert.equal(gate.entries.length,1);gate.entries[0].fulfill();await operation;assert.equal(h.counters.writes,1);assert.equal(ui(h).modalOpen,false);gate.restore();});
for(const [name,value,pattern]of [['bank','-1',/negative|bank/i],['date','367-1105',/date|day/i],['shipTons','',/together/i],['capacity','1',/capacity|hold/i],['jump','1.5',/jump/i]])test(`setup invalid ${name} never calls Store and preserves review`,async()=>{const h=setup('setup'),raw=h.bytes();await open(h,{[name]:value});const gate=serviceSaveGate(h.store);await h.submit();assert.equal(h.bytes(),raw);assert.equal(gate.entries.length,0);assert.match(ui(h).modalError,pattern);assert.equal(h.store.reloadRequired??false,false);assert.equal(ui(h).submitDisabled,false);gate.restore();});
test('blank location reason validates before map lookup or Store',async()=>{const h=setup(),raw=h.bytes();await open(h,{reason:'  '});const gate=serviceSaveGate(h.store);await h.submit();assert.equal(h.map.calls.nearby,0);assert.equal(gate.entries.length,0);assert.equal(h.bytes(),raw);assert.match(ui(h).modalError,/reason/);gate.restore();});

test('setup nearby failure after save is ancillary and cannot duplicate opening funds',async()=>{const h=setup('setup'),before=h.persisted();await open(h);const detached=h.dom.ids.get('modal-form').onsubmit;h.map.fail('nearby','Synthetic ancillary nearby 503');await h.submit();await flush();economics(h,before);assert.equal(h.counters.writes,1);assert.equal(h.persisted().ledger.length,1);assert.equal(ui(h).modalOpen,false);assert.equal(h.store.reloadRequired??false,false);assert.match(ui(h).message,/saved[\s\S]*nearby|nearby[\s\S]*saved/i);const bytes=h.bytes();await detached(event(h));assert.equal(h.bytes(),bytes);assert.equal(h.counters.writes,1);});
test('same-world location refresh does not write, consume Undo or alter exact campaign bytes',async()=>{const h=setup(),raw=h.bytes(),gate=serviceSaveGate(h.store);await h.api.setLocation(h.api.state.actual);assert.equal(h.map.calls.nearby,1);assert.equal(gate.entries.length,0);assert.equal(h.bytes(),raw);assert.equal(ui(h).modalOpen,false);h.map.fail('nearby','Synthetic same-world 503');await h.api.setLocation(h.api.state.actual);assert.equal(h.bytes(),raw);assert.equal(gate.entries.length,0);assert.match(ui(h).message,/Could not refresh nearby/);gate.restore();});
for(const path of ['setup','location'])for(const point of ['beforeNotify','afterNotify'])test(`${path} durable ${point} failure is terminal and reload Undo recovers economics`,async t=>{const {h,before,gate,operation,detached}=await pending(t,path);h.hooks[point]=()=>{throw Error('Injected '+point+' failure');};gate.entries[0].fulfill();await operation;terminal(h);same(h.persisted(),gate.entries[0].args[0]);economics(h,before);const bytes=h.bytes();await detached(event(h));await h.store.acquire(true);assert.equal(h.bytes(),bytes);assert.equal(gate.entries.length,1);const fresh=setup(path,h.store.read());await fresh.runAction('undo');for(const key of ['initialized','name','ship','bank','ledger','lots','contracts','policies','route','actual','hours','dateLabel'])same(fresh.persisted()[key],before[key]);});
for(const path of ['setup','location'])for(const afterWrite of [false,true])test(`${path} unknown rejection ${afterWrite?'after':'before'} owned publication fails closed`,async t=>{const {h,raw,gate,operation,detached}=await pending(t,path);if(afterWrite)gate.entries[0].write();gate.entries[0].reject();await operation;terminal(h);assert.match(ui(h).message,afterWrite?/saved, but/:/outcome.*could not be confirmed/);if(!afterWrite)assert.equal(h.bytes(),raw);const bytes=h.bytes();await detached(event(h));assert.equal(h.bytes(),bytes);assert.equal(gate.entries.length,1);});
for(const path of ['setup','location'])for(const publication of ['missing','wrong token','wrong revision'])test(`${path} fulfilled provider with ${publication} publication cannot report success`,async t=>{const {h,gate,operation}=await pending(t,path);if(publication==='missing')h.store.onChange=()=>{};else h.hooks.beforeNotify=(next,metadata)=>{if(publication==='wrong token')metadata.saveToken={};else next.revision++;};gate.entries[0].fulfill();await operation;terminal(h);assert.match(ui(h).message,/outcome.*could not be confirmed/);assert.equal(h.counters.writes,1);await h.submit();assert.equal(gate.entries.length,1);});
for(const path of ['setup','location'])test(`${path} owned publication outranks contradictory known-prewrite provider rejection`,async t=>{const {h,gate,operation}=await pending(t,path);gate.entries[0].write();gate.entries[0].reject(Object.assign(Error('Contradictory prewrite result'),{code:'SAVE_NOT_COMMITTED',committed:false}));await operation;terminal(h);assert.match(ui(h).message,/saved, but/);await h.submit();assert.equal(h.counters.writes,1);assert.equal(gate.entries.length,1);});
for(const path of ['setup','location'])for(const when of ['before','after'])test(`${path} foreign same-revision publication ${when} owned write permanently retires completion cleanup`,async t=>{const {h,gate,operation}=await pending(t,path);if(when==='after')gate.entries[0].write();h.external(structuredClone(h.persisted()));if(when==='before')gate.entries[0].write();h.api.setView('newer-browsing');h.api.setSelected(['newer-selection']);gate.entries[0].fulfill();await operation;noSuccess(h);assert.equal(h.api.view,'newer-browsing');same(h.api.selected,['newer-selection']);assert.equal(ui(h).modalOpen,true);assert.equal(ui(h).submitDisabled,true);});
for(const path of ['setup','location'])for(const change of ['disk only','published revision'])test(`${path} rechecks ${change} before writing and cannot overwrite it`,async t=>{const {h,gate,operation}=await pending(t,path),next=S.transition(h.persisted(),'External name',s=>s.name='New owner');h.external(next,{publish:change==='published revision'});const bytes=h.bytes();gate.entries[0].fulfill();await operation;assert.equal(h.bytes(),bytes);assert.equal(h.counters.writes,0);noSuccess(h);assert.match(ui(h).modalError,/stale|changed|editing|read-only/i);});
for(const path of ['setup','location'])for(const afterWrite of [false,true])test(`${path} real production editor loss and regain ${afterWrite?'after':'before'} publication retires its owner`,async t=>{const {h,gate,operation,detached}=await pending(t,path);if(afterWrite)gate.entries[0].write();h.store.yield();h.store.editable=true;h.store.onRole(true,'Editing again');if(!afterWrite)gate.entries[0].write();gate.entries[0].fulfill();await operation;noSuccess(h);assert.equal(ui(h).modalOpen,true);assert.equal(ui(h).submitDisabled,true);assert.equal(h.dom.ids.get('modal-cancel').disabled,false);const bytes=h.bytes();await detached(event(h));assert.equal(h.bytes(),bytes);assert.equal(gate.entries.length,1);});
for(const path of ['setup','location'])for(const failure of [false,true])test(`${path} detached completion cannot report into or close newer dialog, failure=${failure}`,async t=>{const {h,gate,operation,detached}=await pending(t,path),dialog=h.dom.ids.get('modal');dialog.close();dialog.dispatch('close');h.api.modal('Newer unrelated review','Preserve newer dialog',null);const newer=h.api.modalSession;if(failure)h.failNext();gate.entries[0].fulfill();await operation;assert.equal(h.api.modalSession,newer);assert.equal(ui(h).modalTitle,'Newer unrelated review');assert.equal(ui(h).modalError,'');assert.equal(ui(h).modalOpen,true);noSuccess(h);const bytes=h.bytes();await detached(event(h));assert.equal(h.bytes(),bytes);});
for(const path of ['setup','location'])for(const fault of ['close before','close after','render','success reporting','terminal reporting'])test(`${path} ${fault} fault remains observed and reload-only after durable save`,async t=>{const {h,gate,operation}=await pending(t,path);let faults=0;const dialog=h.dom.ids.get('modal');if(fault.startsWith('close')){const close=dialog.close;dialog.close=function(){if(faults++)return close.call(this);if(fault==='close after'){close.call(this);dialog.dispatch('close');}throw Error('Synthetic location '+fault);};}else if(fault==='render'){const main=h.dom.ids.get('main');let html=main.innerHTML;Object.defineProperty(main,'innerHTML',{get:()=>html,set(next){if(gate.entries[0].settled&&!faults++){throw Error('Synthetic completion render fault');}html=next;}});}else{const node=h.dom.ids.get('message');let text=node.textContent;Object.defineProperty(node,'textContent',{get:()=>text,set(next){if(!faults&&((fault==='success reporting'&&successPattern.test(next))||(fault==='terminal reporting'&&/Reload/.test(next)))){faults++;throw Error('Synthetic reporting fault');}text=next;}});}if(fault==='terminal reporting'){gate.entries[0].write();gate.entries[0].reject();}else gate.entries[0].fulfill();await operation;assert.ok(faults);assert.equal(h.store.reloadRequired,true);assert.equal(h.store.editable,false);assert.equal(h.counters.writes,1);assert.match(h.dom.ids.get('save-status').textContent,/Reload/);if(ui(h).modalOpen)assert.match(ui(h).modalError,/saved[\s\S]*Reload/i);assert.equal(ui(h).submitDisabled,true);const bytes=h.bytes();await h.submit();assert.equal(h.bytes(),bytes);assert.equal(gate.entries.length,1);});

for(const path of ['setup','location'])for(const changedBy of ['same-revision publication','editor loss and regain','new modal'])for(const outcome of ['resolve','reject'])test(`${path} obsolete lookup ${outcome} after ${changedBy} cannot revive mutable intent`,async()=>{
 const h=setup(path),raw=h.bytes();await open(h);const lookup=h.map.hold(path==='setup'?'resolve':'nearby'),gate=serviceSaveGate(h.store),operation=h.submit();await flush();
 if(changedBy==='same-revision publication')h.external(structuredClone(h.persisted()));
 else if(changedBy==='editor loss and regain'){h.store.yield();h.store.editable=true;h.store.onRole(true,'Editing again');}
 else h.api.modal('Newer read-only review','Retain newer content',null);
 const session=h.api.modalSession,before=ui(h);if(outcome==='resolve')lookup.resolve();else lookup.reject(Error('Obsolete lookup must not be reported'));await operation;
 assert.equal(h.bytes(),raw);assert.equal(gate.entries.length,0);assert.equal(h.api.modalSession,session);assert.equal(ui(h).modalTitle,before.modalTitle);assert.equal(ui(h).modalError,before.modalError);assert.equal(ui(h).message,before.message);noSuccess(h);gate.restore();
});
for(const path of ['setup','location'])for(const changedBy of ['same-revision publication','editor loss and regain'])test(`${path} opening-time ownership blocks first submit after ${changedBy}`,async()=>{
 const h=setup(path),raw=h.bytes();await open(h);const gate=serviceSaveGate(h.store);if(changedBy==='same-revision publication')h.external(structuredClone(h.persisted()));else{h.store.yield();h.store.editable=true;h.store.onRole(true,'Editing again');}await h.submit();assert.equal(h.bytes(),raw);assert.equal(h.map.calls.resolve+h.map.calls.nearby,0);assert.equal(gate.entries.length,0);assert.equal(ui(h).submitDisabled,true);gate.restore();
});
for(const path of ['setup','location'])test(`${path} save owner exists before synchronous reentrant publication and freezes inputs only in save phase`,async()=>{
 const h=setup(path);await open(h);const lookup=h.map.hold(path==='setup'?'resolve':'nearby'),operation=h.submit();await flush();assert.ok([...h.dom.fields().values()].some(field=>!field.disabled),'Lookup remains editable and dismissible');let writes=0,reentry;
 h.hooks.beforeNotify=()=>{writes++;assert.ok([...h.dom.fields().values()].every(field=>field.disabled),'Prepared provider owns frozen form');reentry=h.submit();h.api.modal('Reentrant unrelated review','Cannot replace provider owner',null);};lookup.resolve();await operation;await reentry;assert.equal(writes,1);assert.equal(h.counters.writes,1);assert.equal(ui(h).modalOpen,false);
});
test('setup retains submitted rounding when unrelated global rounding changes while world lookup is pending',async()=>{
 const h=setup('setup');await open(h);const lookup=h.map.hold('resolve'),operation=h.submit();await flush();const original=structuredClone(h.api.inputRounding);assert.ok(original.some(r=>r.before===opening));h.api.setInputRounding([{label:'Unrelated draft',before:'7.1',after:'8'}]);lookup.resolve();await operation;const rounding=h.persisted().events.find(e=>e.label==='Rounding applied [R]');same(rounding.roundingChanges,original);assert.equal(h.persisted().bank,roundedOpening);
});
test('setup after Undo records a new opening bank and resets Dashboard baseline without duplicated funds',async()=>{
 const h=setup('setup');await open(h);await h.submit();const first=h.persisted();await h.runAction('undo');const undone=h.persisted();assert.equal(undone.initialized,false);assert.equal(undone.bank,'0');assert.equal(undone.ledger.length,0);assert.equal(undone.undo.length,0);assert.equal(dashboardData(undone),null);
 await open(h,{bank:'12345678901234567890.01',name:'Second setup',date:'003-1106'});await h.submit();const saved=h.persisted();assert.equal(saved.bank,'12345678901234567891');assert.equal(saved.revision,first.revision+2);assert.equal(saved.ledger.length,1);assert.equal(saved.ledger[0].type,'Opening bank');assert.notEqual(saved.ledger[0].id,first.ledger[0].id);same(saved.dashboardBaseline.excludedLedgerIds,[saved.ledger[0].id]);assert.equal(saved.dashboardBaseline.bank,saved.bank);assert.equal(saved.dashboardBaseline.dateLabel,'003-1106');assert.equal(dashboardData(saved).operatingResult,'0');assert.equal(dashboardData(saved).otherInflows,'0');assert.equal(dashboardData(saved).adjustment,'0');assert.equal(saved.undo.length,1);assert.equal(h.counters.writes,3);
});
test('completed location reload and Undo restore economics and route without resetting consumed mulligan dice',async()=>{
 const h=setup(),before=h.persisted();assert.equal(before.jumpAttempts[0].mulliganUsed,true);assert.equal(before.jumpAttempts[0].rolls.length,2);await open(h);await h.submit();const saved=h.persisted();assert.equal(saved.jumpAttempts[0].closed,true);const fresh=setup('location',h.store.read());assert.equal(fresh.bytes(),h.bytes());await fresh.runAction('undo');const restored=fresh.persisted();for(const key of ['bank','ledger','lots','contracts','policies','ship','actual','route','routeIndex','hours','dateLabel','dashboardBaseline'])same(restored[key],before[key]);same(restored.jumpAttempts[0].rolls,before.jumpAttempts[0].rolls);assert.equal(restored.jumpAttempts[0].mulliganUsed,true);assert.equal(restored.jumpAttempts[0].closed,true);assert.equal(S.jumpUndoEligibility(restored).allowed,false);
});
for(const changedBy of ['newer dialog','navigation away and back','same-revision publication','editor loss and regain'])for(const outcome of ['resolve','reject'])test(`saved setup ancillary nearby ${outcome} after ${changedBy} stays inert`,async()=>{
 const h=setup('setup');await open(h);const nearby=h.map.hold('nearby');await h.submit();assert.equal(h.counters.writes,1);assert.equal(ui(h).modalOpen,false);const raw=h.bytes(),added={...target,id:'999,999',x:999,y:999,name:'Obsolete ancillary result'};
 if(changedBy==='newer dialog')h.api.modal('Newer review','Retained',null);
 else if(changedBy==='navigation away and back'){await h.runAction('world',fixtureMap.state.route[0]);await h.runAction('world',target.id);}
 else if(changedBy==='same-revision publication')h.external(structuredClone(h.persisted()));
 else{h.store.yield();h.store.editable=true;h.store.onRole(true,'Editing again');}
 const before=ui(h),session=h.api.modalSession;if(outcome==='resolve')nearby.resolve([added]);else nearby.reject(Error('Obsolete ancillary failure'));await flush();assert.equal(h.api.known[added.id],undefined);assert.equal(h.bytes(),raw);assert.equal(h.api.modalSession,session);assert.equal(ui(h).message,before.message);assert.equal(ui(h).modalError,before.modalError);assert.equal(h.counters.writes,1);
});
for(const changedBy of ['Cancel','Close','Escape','new dialog','same-revision publication','editor loss and regain','newer browse intent'])for(const outcome of ['resolve','reject'])test(`Find World mutable picker handoff ${outcome} after ${changedBy} cannot open location confirmation`,async()=>{
 const h=setup(),raw=h.bytes();h.api.findWorld();const lookup=h.map.hold('resolve'),gate=serviceSaveGate(h.store),operation=h.dom.ids.get('choose-starting-world').onclick();await flush();
 if(['Cancel','Close','Escape'].includes(changedBy)){if(changedBy==='Escape')h.dom.ids.get('modal').dispatch('cancel',{preventDefault(){}});else h.dom.ids.get(changedBy==='Cancel'?'modal-cancel':'modal-close').onclick();}
 else if(changedBy==='new dialog')h.api.modal('Newer unrelated review','Must remain here',null);
 else if(changedBy==='same-revision publication')h.external(structuredClone(h.persisted()));
 else if(changedBy==='editor loss and regain'){h.store.yield();h.store.editable=true;h.store.onRole(true,'Editing again');}
 else await h.submit();
 const before=ui(h),session=h.api.modalSession;if(outcome==='resolve')lookup.resolve();else lookup.reject(Error('Obsolete picker failure'));await operation;assert.equal(h.bytes(),raw);assert.equal(gate.entries.length,0);assert.equal(h.api.modalSession,session);assert.equal(ui(h).modalTitle,before.modalTitle);assert.equal(ui(h).modalOpen,before.modalOpen);assert.equal(ui(h).modalError,before.modalError);assert.equal(ui(h).message,before.message);assert.notEqual(ui(h).modalTitle,'Set ship location');gate.restore();
});
test('Find World retains browse in a read-only tab but never lets old mutable handoff acquire authority later',async()=>{
 const h=setup(),raw=h.bytes();h.store.yield();h.api.findWorld();assert.equal(h.dom.ids.get('choose-starting-world').disabled,true);h.store.editable=true;h.store.onRole(true,'Editing again');await h.dom.ids.get('choose-starting-world').onclick();assert.equal(h.map.calls.resolve,0);await h.submit();assert.equal(h.api.view,target.id);assert.equal(ui(h).modalOpen,false);assert.equal(h.bytes(),raw);assert.equal(h.counters.writes,0);
});
test('Find World current picker failure stays in its review and corrected handoff only opens explicit confirmation',async()=>{
 const h=setup(),raw=h.bytes();h.api.findWorld();h.map.fail('resolve','Synthetic picker 503');await h.dom.ids.get('choose-starting-world').onclick();assert.equal(ui(h).modalTitle,'Find a world');assert.match(ui(h).modalError,/503/);assert.equal(h.dom.ids.get('choose-starting-world').disabled,false);await h.dom.ids.get('choose-starting-world').onclick();assert.equal(ui(h).modalTitle,'Set ship location');assert.equal(h.bytes(),raw);assert.equal(h.counters.writes,0);h.api.closeModal();assert.equal(h.bytes(),raw);
});
for(const path of ['setup','location'])test(`${path} partial modal construction cannot let an unowned form perform native navigation`,async()=>{
 const h=setup(path),raw=h.bytes(),title=h.dom.ids.get('modal-title'),form=h.dom.ids.get('modal-form');form.id='modal-form';let faults=0;Object.defineProperty(title,'textContent',{get:()=>'',set(){faults++;throw Error('Synthetic partial world modal title fault');}});
 if(path==='setup')await assert.rejects(h.api.setup(),/partial world modal/);else assert.throws(()=>h.api.setLocation(target),/partial world modal/);assert.equal(faults,1);assert.equal(typeof form.onsubmit,'undefined');let prevented=0;h.dom.dispatch('submit',form,{preventDefault(){prevented++;}});await flush();assert.equal(prevented,1);assert.equal(h.bytes(),raw);assert.equal(h.counters.writes,0);
});
for(const path of ['setup','location'])for(const committed of [false,true])test(`${path} terminal no-handler modal submission is prevented, committed=${committed}`,async t=>{
 const {h,gate,operation}=await pending(t,path);if(committed)gate.entries[0].write();gate.entries[0].reject();await operation;terminal(h);const raw=h.bytes(),form=h.dom.ids.get('modal-form');form.id='modal-form';form.onsubmit=null;let prevented=0;h.dom.dispatch('submit',form,{preventDefault(){prevented++;}});await flush();assert.equal(prevented,1);assert.equal(h.bytes(),raw);assert.equal(gate.entries.length,1);
});

for(const changedBy of ['newer dialog','navigation away and back','same-revision publication','editor loss and regain'])for(const outcome of ['resolve','reject'])test(`same-world read-only refresh ${outcome} after ${changedBy} cannot revive old enrichment`,async()=>{
 const h=setup(),raw=h.bytes(),actual=h.api.state.actual,lookup=h.map.hold('nearby'),operation=h.api.setLocation(actual),added={...target,id:'998,998',x:998,y:998,name:'Obsolete same-world result'};
 if(changedBy==='newer dialog')h.api.modal('Newer review','Preserve this review',null);
 else if(changedBy==='navigation away and back'){await h.runAction('world',target.id);await h.runAction('world',actual);}
 else if(changedBy==='same-revision publication')h.external(structuredClone(h.persisted()));
 else{h.store.yield();h.store.editable=true;h.store.onRole(true,'Editing again');}
 const before=ui(h),session=h.api.modalSession;if(outcome==='resolve')lookup.resolve([added]);else lookup.reject(Error('Obsolete refresh failure'));await operation;assert.equal(h.api.known[added.id],undefined);assert.equal(h.bytes(),raw);assert.equal(h.api.modalSession,session);assert.equal(ui(h).message,before.message);assert.equal(ui(h).modalError,before.modalError);assert.equal(h.counters.writes,0);
});
test('same-world refresh remains available read-only and never acquires mutation authority',async()=>{const h=setup(),raw=h.bytes();h.store.yield();await h.api.setLocation(h.api.state.actual);assert.equal(h.map.calls.nearby,1);assert.equal(h.store.editable,false);assert.equal(h.bytes(),raw);assert.equal(h.counters.writes,0);assert.match(ui(h).message,/Live nearby worlds loaded/);});
for(const path of ['setup','same-world'])for(const fault of ['map failure reporting','enrichment render'])test(`${path} optional nearby ${fault} cannot reject unobserved or mark completed state retryable`,async()=>{
 const h=setup(path==='setup'?'setup':'location'),unhandled=[],observe=e=>unhandled.push(e);process.on('unhandledRejection',observe);try{
  let operation;const lookup=h.map.hold('nearby');if(path==='setup'){await open(h);await h.submit();operation=null;}else operation=h.api.setLocation(h.api.state.actual);const raw=h.bytes();let faults=0;
  if(fault==='map failure reporting'){const message=h.dom.ids.get('message');let value=message.textContent;Object.defineProperty(message,'textContent',{get:()=>value,set(next){faults++;throw Error('Synthetic optional nearby reporting fault');}});lookup.reject(Error('Synthetic optional nearby 503'));}
  else{const main=h.dom.ids.get('main');let html=main.innerHTML;Object.defineProperty(main,'innerHTML',{get:()=>html,set(next){faults++;throw Error('Synthetic ancillary render fault');}});lookup.resolve();}
  await operation;await flush();await flush();assert.ok(faults);assert.equal(h.bytes(),raw);assert.equal(h.store.reloadRequired??false,false);assert.equal(h.counters.writes,path==='setup'?1:0);assert.equal(ui(h).modalOpen,false);assert.deepEqual(unhandled,[]);
 }finally{process.removeListener('unhandledRejection',observe);}
});

for(const path of ['setup','location'])test(`${path} throwing prepared-form freeze is known prewrite and corrected retry keeps the same fields`,async()=>{
 const h=setup(path),raw=h.bytes();await open(h);const field=h.dom.fields().get(path==='setup'?'name':'reason');let disabled=field.disabled,faults=0;Object.defineProperty(field,'disabled',{configurable:true,get:()=>disabled,set(next){if(next&&!faults++){throw Error('Synthetic field freeze fault');}disabled=next;}});const gate=serviceSaveGate(h.store),first=h.submit(),retained=fields(h);await first;assert.equal(faults,1);assert.equal(gate.entries.length,0);assert.equal(h.bytes(),raw);assert.match(ui(h).modalError,/field freeze fault/);assert.equal(ui(h).submitDisabled,false);assert.equal(h.store.reloadRequired??false,false);same(fields(h),retained);const retry=h.submit();await flush();assert.equal(gate.entries.length,1);gate.entries[0].fulfill();await retry;assert.equal(h.counters.writes,1);assert.equal(ui(h).modalOpen,false);gate.restore();
});
for(const path of ['setup','location'])for(const committed of [false,true])test(`${path} detached unknown outcome ${committed?'after':'before'} write latches global reload without overwriting newer modal`,async t=>{
 const {h,gate,operation}=await pending(t,path);if(committed)gate.entries[0].write();const dialog=h.dom.ids.get('modal');dialog.close();dialog.dispatch('close');h.api.modal('Newer read-only review','Preserve newer review',null);const session=h.api.modalSession,body=h.dom.ids.get('modal-body').innerHTML;gate.entries[0].reject();await operation;assert.equal(h.store.reloadRequired,true);assert.equal(h.store.editable,false);assert.match(h.dom.ids.get('save-status').textContent,/Reload/);assert.equal(h.api.modalSession,session);assert.equal(ui(h).modalTitle,'Newer read-only review');assert.equal(ui(h).modalError,'');assert.equal(h.dom.ids.get('modal-body').innerHTML,body);assert.equal(ui(h).modalOpen,true);assert.equal(h.counters.writes,committed?1:0);assert.equal(gate.entries.length,1);
});
