// Exact-head Chromium evidence for the bounded Undo / Undo Jump migration.
// Synthetic campaigns only, intercepted map API, actual versioned Store body,
// deferred completion, real Web Locks, viewport JPEGs, and no traces.
// Run: node verification/undo-completion-browser.test.mjs [playwright-module]
// --fixtures-only verifies fixture accounting and source wiring without Chromium.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir,readFile,readdir,stat,writeFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {join} from 'node:path';
import * as S from '../js/state.mjs';
import {configureFuel} from '../js/fuel.mjs';
import {createDashboardBaseline} from '../js/dashboard-baseline.mjs';
import {dashboardData} from '../js/dashboard-data.mjs';
import {recordWorldOverride,revertWorldField,worldFieldRevertEligibility} from '../js/world-change-history.mjs';

const base=process.env.TRAVELLER_TEST_URL||'http://127.0.0.1:8765/';
const root=fileURLToPath(new URL('../../../',import.meta.url)),artifacts=fileURLToPath(new URL('../verification-artifacts/',import.meta.url));
const core=JSON.parse(await readFile(new URL('../rules/core-2022.json',import.meta.url)));
const KEY='traveller-trade-route-calculator:v1',LOCK=KEY+':writer',sizes=[{width:1440,height:1100},{width:390,height:844}];
const paired=['success','prewrite','unknown-before','unknown-after','notification-before','notification-after','cleanup','tokenless','takeover','late-role-loss'];
const scenarios=[...['history','jump'].flatMap(path=>paired.map(mode=>({id:path+'-'+mode,path,mode}))),...[
 ['synchronous-history','history','sync'],['synchronous-jump','jump','sync'],['history-jump-success','history','history-jump'],['idle-review-invalidated','jump','idle-invalidated'],['reentrant-history-publication','history','reentrant'],['pending-screen-before-write','history','pending-ui-before'],['pending-screen-after-write','history','pending-ui-after'],['world-field-correction','history','world-correction'],['baseline-crossing','history','baseline'],['protected-later-action','history','protected-later'],['protected-spent-mulligan','history','protected-spent'],['mail-preview-cleanup','history','mail'],['contract-preview-cleanup','history','contracts']
].map(([id,path,mode])=>({id,path,mode}))];
const report={suite:'Undo and Undo Jump save completion',startedAt:new Date().toISOString(),requestedCommit:process.env.TRAVELLER_COMMIT||null,node:process.version,declaredCases:scenarios.length*sizes.length,cases:[],errors:[],scope:'Actual app Undo gestures, exact versioned Store/controller, test-owned deferred completion, native Web Locks, exact economic/audit state, protected jumps, one mulligan, field corrections, Dashboard boundary, reload and desktop/mobile screenshots. Other asynchronous action families, arbitrary provider implementations, live map availability and real campaigns are outside this gate.'};
let browser;
function fixture(){
 const s=S.initial(),origin={id:'0,0',x:0,y:0,name:'Undo Origin',sector:'Synthetic',hex:'0101',uwp:'A788899-C',zone:'Safe'},destination={...origin,id:'1,0',x:1,name:'Undo Destination',hex:'0201'};
 Object.assign(s,{initialized:true,name:'Disposable Undo completion campaign',actual:origin.id,worlds:{[origin.id]:origin,[destination.id]:destination},route:[origin.id,destination.id],bank:'100000'});
 Object.assign(s.ship,{capacity:'100',armed:true,staterooms:2,fuel:configureFuel(200,40,60,40,2),lifeSupport:{capacityHours:672,stockUnits:{numerator:'56',denominator:'1'}},accommodation:{rooms:{low:0,middle:2,high:0},passengers:{low:0,middle:0,high:0},crew:{low:0,middle:2,high:0}}});
 s.lots=[{id:'undo-cargo',commodity:'11',description:'Saved cargo',quantity:'5',basis:'1000',goodsValue:'1000'}];
 s.contracts=[{id:'undo-mail',kind:'mail',status:'accepted',firstDeparture:null,origin:origin.id,destination:destination.id,quantity:'5',payment:'1000',dueHours:null}];
 s.policies=[{id:'undo-policy',lotId:'undo-cargo',claims:[],status:'active',initialQuantity:'5',remainingQuantity:'5',insuredValue:'1000',remainingValue:'1000',coverage:70,route:[origin.id,destination.id],routeProgress:0,destination:destination.id}];
 s.snapshots=[{id:'undo-supplier',kind:'supplier',worldId:origin.id,hours:0,startedHours:0,party:'Retained supplier',offers:[{id:'undo-stock',commodity:'11',description:'Saved offer',expired:false,remaining:'2',unitPrice:'100'}]}];
 s.dashboardBaseline=createDashboardBaseline(s);return S.validate(s);
}
function jump(s=fixture()){const p=S.prepareJump(s,()=>({dice:[3,3,3,3,3,3],total:18}));return S.transition(p.state,'Jump: Undo Origin → Undo Destination',next=>S.commitJump(next,{attemptId:p.attempt.id,elapsed:160}));}
function seed(scenario){
 let s=fixture();if(scenario.path==='jump'||['history-jump','protected-later','protected-spent'].includes(scenario.mode))s=jump(s);
 else if(scenario.mode==='world-correction'){
  s=S.transition(s,'World override',next=>recordWorldOverride(next,'0,0',{uwp:'A788899-D',zone:'Amber',fuelOverride:true,accessibleWater:true,reason:'Saved survey'},core));const source=s.events.findLast(e=>e.worldChangeAudit);s=jump(s);s=S.transition(s,'Manual deposit',next=>S.deposit(next,75,'Later receipt'));s=S.transition(s,'World field reverted',next=>revertWorldField(next,source.id,'techLevel',core));
 }else if(!['mail','contracts'].includes(scenario.mode))s=S.transition(s,'Manual deposit',next=>S.deposit(next,125,'Undo fixture'));
 if(scenario.mode==='protected-later'){s=S.transition(s,'Manual deposit',next=>S.deposit(next,1,'Later action'));s=S.undo(s);}
 if(scenario.mode==='protected-spent')s=jump(S.undoJump(s));
 if(scenario.mode==='baseline')s.dashboardBaseline=createDashboardBaseline(s);
 if(scenario.mode==='reentrant')s=S.transition(s,'Second deposit',next=>S.deposit(next,10,'Keep previous inverse'));
 return S.validate(s);
}
const raw=page=>page.evaluate(key=>localStorage.getItem(key),KEY),read=async page=>JSON.parse(await raw(page));
const material=s=>Object.fromEntries(Object.entries(s).filter(([key])=>!['revision','jumpAttempts','events','undo'].includes(key)));
const action=(page,name)=>page.locator('[data-action="'+name+'"]').filter({visible:true}).first();
const tab=(page,name)=>page.locator('#tabs [data-action="tab"][data-arg="'+name+'"]').click();
const frames=page=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
const closed=page=>page.locator('#modal').waitFor({state:'hidden'}),gate=page=>page.evaluate(()=>undoGate.snapshot());
const errorText=error=>error?.stack||String(error),successPattern=/Jump undone\.|Latest action undone\./;
function assertUndo(saved,before){const expected=S.undo(before);expected.events.at(-1).id=saved.events.at(-1).id;assert.deepEqual(saved,expected);assert.equal(saved.revision,before.revision+1);assert.equal(saved.undo.length,before.undo.length-1);assert.deepEqual(saved.events.slice(0,-1),before.events);assert.equal(saved.events.at(-1).label,'Undo: '+before.undo.at(-1).label);}
async function contextFor(result,scenario){
 const context=await browser.newContext({viewport:result.viewport,serviceWorkers:'block'});context.setDefaultTimeout(10000);context.setDefaultNavigationTimeout(15000);
 context.on('page',page=>{page.on('pageerror',error=>result.pageErrors.push(errorText(error)));page.on('console',entry=>{if(entry.type()==='error')result.consoleErrors.push(entry.text());});});
 await context.exposeBinding('__undoUnhandled',(_source,message)=>{result.unhandledRejections.push(message);});
 await context.addInitScript(({key,bytes,origin})=>{
  if(location.origin!==origin)return;addEventListener('unhandledrejection',event=>{void globalThis.__undoUnhandled(String(event.reason?.stack||event.reason));});if(!localStorage.getItem(key))localStorage.setItem(key,bytes);
  const native=Storage.prototype.setItem;globalThis.undoStorage={attempts:0,writes:0,failNext:false,observations:[]};Storage.prototype.setItem=function(name,value){if(this!==localStorage||name!==key)return Reflect.apply(native,this,[name,value]);undoStorage.attempts++;undoStorage.observations.push({message:document.querySelector('#message')?.textContent||'',open:!!document.querySelector('#modal')?.open});if(undoStorage.failNext){undoStorage.failNext=false;throw Error('Synthetic known prewrite Undo storage rejection');}const result=Reflect.apply(native,this,[name,value]);undoStorage.writes++;return result;};
  globalThis.undoDiceCalls=0;const random=crypto.getRandomValues.bind(crypto);crypto.getRandomValues=array=>{if(array instanceof Uint32Array&&array.length===1){undoDiceCalls++;array[0]=2;return array;}return random(array);};
 },{key:KEY,bytes:JSON.stringify(seed(scenario)),origin:new URL(base).origin});
 await context.route('**/*',async route=>{const url=new URL(route.request().url());if(url.href===new URL('verification/undo-peer.html',base).href)return route.fulfill({contentType:'text/html',body:'<!doctype html><title>Disposable Undo Store peer</title>'});if(url.origin===new URL(base).origin)return route.continue();if(url.origin==='https://travellermap.com'&&url.pathname.startsWith('/api/'))return route.fulfill({json:url.pathname.endsWith('/jumpworlds')?{Worlds:[]}:url.pathname.endsWith('/universe')?{Sectors:[]}:url.pathname.endsWith('/metadata')?{Subsectors:[]}:'' ,headers:{'Access-Control-Allow-Origin':'*'}});result.unexpectedRequests.push(url.href);return route.abort('blockedbyclient');});return context;
}
async function installGate(page,result){
 result.runtime=await page.evaluate(async()=>{
  const appURL=[...document.scripts].find(s=>s.type==='module'&&/\/app\.mjs(?:\?|$)/.test(s.src))?.src;if(!appURL)throw Error('Actual app module unavailable');const response=await fetch(appURL);if(!response.ok)throw Error('Cannot inspect runtime app import');const source=await response.text(),specifier=source.match(/import\s*\{[^}]*\bStore\b[^}]*\}\s*from\s*['"]([^'"]*persistence\.mjs[^'"]*)['"]/u)?.[1];if(!specifier)throw Error('Exact runtime Store import missing');const storeURL=new URL(specifier,appURL).href;if(!new URL(storeURL).search)throw Error('Expected versioned Store');
  const {Store,KEY}=await import(storeURL),nativeSave=Store.prototype.save,observation=point=>({point,message:document.querySelector('#message')?.textContent||'',open:!!document.querySelector('#modal')?.open,title:document.querySelector('#modal-title')?.textContent||'',revision:JSON.parse(localStorage.getItem(KEY)).revision});
  const g=globalThis.undoGate={armed:false,pending:null,store:null,args:null,calls:0,executions:0,notifyFault:null,roleFault:false,cleanupFault:false,cleanupThrows:0,pendingUI:null,pendingUIThrows:0,reentrant:false,reentrantCalls:0,roleThrows:0,candidates:[],forwarded:[],publications:[],observations:[],settlements:[]};
  const text=Object.getOwnPropertyDescriptor(Node.prototype,'textContent');Object.defineProperty(Node.prototype,'textContent',{...text,set(value){if(g.pendingUI&&this.id==='modal-title'&&/^Undoing latest action/.test(value)){g.pendingUI=null;g.pendingUIThrows++;throw Error('Synthetic pending Undo screen construction failure');}return Reflect.apply(text.set,this,[value]);}});
  const html=Object.getOwnPropertyDescriptor(Element.prototype,'innerHTML');Object.defineProperty(Element.prototype,'innerHTML',{...html,set(value){if(g.cleanupFault&&this.id==='main'&&g.settlements.at(-1)?.kind==='native-fulfilled'){g.cleanupFault=false;g.cleanupThrows++;throw Error('Synthetic post-Undo cleanup render failure');}return Reflect.apply(html.set,this,[value]);}});
  function observeStore(store){if(g.store===store)return;if(g.store)throw Error('Unexpected second application Store');g.store=store;const change=store.onChange,role=store.onRole;store.onChange=function(...args){const record={revision:args[0].revision,tokenPresent:args[1]?.saveToken!=null,tokenMatchesSave:args[1]?.saveToken!=null&&args[1]?.saveToken===g.args?.[2],actualCallback:false};g.publications.push(record);g.observations.push(observation('before-receiveCampaign'));if(g.notifyFault==='before'){g.notifyFault=null;throw Error('Synthetic notification failure before actual receiveCampaign');}const value=Reflect.apply(change,this,args);record.actualCallback=true;if(g.reentrant){g.reentrant=false;g.reentrantCalls++;document.querySelector('[data-action="undo"]')?.click();}g.observations.push(observation('after-receiveCampaign'));if(g.notifyFault==='after'){g.notifyFault=null;throw Error('Synthetic notification failure after actual receiveCampaign');}return value;};store.onRole=function(...args){const value=Reflect.apply(role,this,args);if(g.roleFault){g.roleFault=false;g.roleThrows++;throw Error('Synthetic role callback failure');}return value;};}
  Store.prototype.save=function(...args){observeStore(this);g.args=args;if(!g.armed)return Reflect.apply(nativeSave,this,args);if(g.pending)throw Error('Application invoked Store.save twice during pending Undo');g.calls++;g.candidates.push(JSON.stringify(args[0]));g.forwarded.push({argumentCount:args.length,tokenPresent:args[2]!=null,expectedRevision:args[1],candidateRevision:args[0].revision});const completion=new Promise((resolve,reject)=>{g.pending={store:this,args,resolve,reject,executed:false,result:undefined,error:null};});if(g.pendingUI==='after')g.write();return completion;};
  g.write=()=>{const p=g.pending;if(!p||p.executed)throw Error('Native write must execute exactly once');p.executed=true;g.executions++;try{p.result=Reflect.apply(nativeSave,p.store,p.args);}catch(error){p.error=error;}};
  g.release=kind=>{const p=g.pending;if(!p)throw Error('No pending Undo');if(kind==='unknown-before'){g.pending=null;g.settlements.push({kind,executed:false});p.reject(Error('Synthetic unknown Undo save outcome'));return;}if(!p.executed)g.write();g.pending=null;if(kind==='unknown-after'){g.settlements.push({kind,executed:true});p.reject(Error('Synthetic lost response after durable Undo'));}else if(p.error){g.settlements.push({kind:'native-rejected',code:p.error.code||null,committed:p.error.committed??null});p.reject(p.error);}else{g.settlements.push({kind:'native-fulfilled',executed:true});p.resolve(p.result);}};
  g.snapshot=()=>({calls:g.calls,executions:g.executions,pending:!!g.pending,editable:g.store?.editable??null,reloadRequired:!!g.store?.reloadRequired,storage:{...undoStorage},diceCalls:undoDiceCalls,forwarded:g.forwarded,candidates:g.candidates,publications:g.publications,observations:g.observations,settlements:g.settlements,pendingUIThrows:g.pendingUIThrows,reentrantCalls:g.reentrantCalls,cleanupThrows:g.cleanupThrows,roleThrows:g.roleThrows,durableHasSaveToken:/"saveToken"\s*:/.test(localStorage.getItem(KEY))});return {appURL,storeURL};
 });
}
async function capture(page,result,label){
 await frames(page);const name='undo-completion-'+result.id+'-'+label+'.jpg';await page.screenshot({path:join(artifacts,name),type:'jpeg',quality:80});result.screenshots.push(name);
 const geometry=await page.evaluate(()=>{const dialog=document.querySelector('#modal[open]'),r=dialog?.getBoundingClientRect();return {width:innerWidth,pageOverflow:document.documentElement.scrollWidth-innerWidth,dialog:r?{left:r.left,right:r.right,overflow:dialog.scrollWidth-dialog.clientWidth}:null};});result.layouts.push({label,...geometry});assert.ok(geometry.pageOverflow<=2,'No horizontal page overflow');if(geometry.dialog){assert.ok(geometry.dialog.left>=-1&&geometry.dialog.right<=geometry.width+1,'Undo dialog remains in viewport');assert.ok(geometry.dialog.overflow<=2,'No horizontal dialog clipping');}
}
const release=(page,kind='native')=>page.evaluate(kind=>undoGate.release(kind),kind);
async function pointer(page,id){const locator=page.locator('#'+id);if(!await locator.isVisible())return;await locator.scrollIntoViewIfNeeded();const box=await locator.boundingBox();assert.ok(box);await page.mouse.click(box.x+box.width/2,box.y+box.height/2,{clickCount:2,delay:20});}
async function openUndo(page,path){if(path==='jump'){await action(page,'jump-undo').click();await page.locator('#modal-title').filter({hasText:/Undo Jump/}).waitFor();}else await tab(page,'History');}
async function start(page,path){if(path==='jump')await page.locator('#modal-submit').click();else await action(page,'undo').click();}
async function arm(page,scenario){await page.evaluate(({mode})=>{Object.assign(undoGate,{armed:true,notifyFault:mode==='notification-before'?'before':mode==='notification-after'?'after':null,roleFault:mode==='notification-after'});undoStorage.failNext=mode==='prewrite';},scenario);}
async function pending(page,result,scenario,before){
 await start(page,scenario.path);await page.waitForFunction(()=>!!undoGate.pending);await frames(page);assert.equal(await raw(page),before);assert.doesNotMatch(await page.locator('#message').textContent(),successPattern);assert.match(await page.locator('#modal-title').textContent(),scenario.path==='jump'?/Undo Jump/:/Undoing latest action/);
 if(scenario.path==='history')assert.equal(await page.locator('#modal-submit').isHidden(),true,'Ordinary History Undo adds no confirmation');else assert.equal(await page.locator('#modal-submit').isDisabled(),true);
 for(const id of ['modal-cancel','modal-close'])assert.equal(await page.locator('#'+id).isDisabled(),true);await page.locator('#modal-form').evaluate(form=>{globalThis.detachedUndoSubmit=form.onsubmit;});
 await pointer(page,'modal-submit');await page.keyboard.press('Enter');await page.locator('#modal-form').evaluate(form=>form.requestSubmit());await page.evaluate(path=>{void detachedUndoSubmit({preventDefault(){},currentTarget:document.querySelector('#modal-form')});document.querySelector('[data-action="'+(path==='jump'?'jump-undo':'undo')+'"]')?.click();},scenario.path);await pointer(page,'modal-cancel');await pointer(page,'modal-close');await page.keyboard.press('Escape');await frames(page);
 assert.equal((await gate(page)).calls,1);assert.equal(await page.locator('#modal').evaluate(dialog=>dialog.open),true);assert.equal(await raw(page),before);await capture(page,result,'pending');result.checks.push('Real repeated pointer, Enter, detached submit, requestSubmit and Escape cannot duplicate or abandon pending Undo');
}
async function restore(page,result,before,{committed=true}={}){
 const bytes=await raw(page);await page.reload();await page.getByText('Editing in this tab',{exact:true}).waitFor();assert.equal(await raw(page),bytes,'Reload cannot repeat Undo');if(committed)assertUndo(await read(page),before);else assert.deepEqual(await read(page),before);assert.equal(await page.evaluate(()=>undoStorage.writes),0);await capture(page,result,'reloaded');result.checks.push('Real reload establishes authoritative bytes without another inverse, audit entry, or mulligan');
}
async function successful(page,result,before){
 await closed(page);assertUndo(await read(page),before);assert.match(await page.locator('#message').textContent(),successPattern);const snapshot=await gate(page);result.gate=snapshot;assert.equal(snapshot.storage.writes-(result.initialWrites||0),1);assert.equal(snapshot.durableHasSaveToken,false);
 for(const call of snapshot.forwarded){assert.ok(call.argumentCount>=3);assert.equal(call.tokenPresent,true);assert.equal(call.candidateRevision,call.expectedRevision+1);}for(const entry of [...snapshot.observations,...snapshot.storage.observations])assert.doesNotMatch(entry.message,successPattern,'Success cannot precede completion');assert.equal(await raw(page),snapshot.candidates.at(-1));
 const bytes=await raw(page),calls=snapshot.calls;await page.evaluate(()=>{void detachedUndoSubmit({preventDefault(){},currentTarget:document.querySelector('#modal-form')});});await frames(page);assert.equal(await raw(page),bytes);assert.equal((await gate(page)).calls,calls);await capture(page,result,'completed');await restore(page,result,before);result.checks.push('One exact durable inverse and audit; post-completion cleanup only; no detached replay');
}
async function terminal(page,result,before,{committed,unknown}){
 await page.waitForFunction(()=>/Reload/.test(document.querySelector('#save-status').textContent));await frames(page);const pattern=unknown?/outcome could not be confirmed[\s\S]*Reload/i:/saved[\s\S]*Reload/i;
 for(const id of ['message','save-status','modal-error'])assert.match(await page.locator('#'+id).textContent(),pattern);assert.equal((await gate(page)).editable,false);assert.equal((await gate(page)).reloadRequired,true);assert.equal(await page.locator('#takeover').isDisabled(),true);assert.doesNotMatch(await page.locator('#message').textContent(),successPattern);
 if(committed)assertUndo(await read(page),before);else assert.deepEqual(await read(page),before);const bytes=await raw(page);await page.locator('#modal-form').evaluate(form=>form.requestSubmit());await page.evaluate(()=>{void detachedUndoSubmit({preventDefault(){},currentTarget:document.querySelector('#modal-form')});document.querySelector('[data-action="undo"]')?.click();});await frames(page);assert.equal(await raw(page),bytes);assert.equal((await gate(page)).calls,1);
 await page.waitForFunction(async lock=>(await navigator.locks.query()).held.every(entry=>entry.name!==lock),LOCK);assert.equal(await page.evaluate(lock=>navigator.locks.request(lock,{ifAvailable:true},held=>!!held),LOCK),true);await page.evaluate(()=>{undoGate.store.yield();undoGate.store.onChange(undoGate.store.read());});for(const id of ['message','save-status','modal-error'])assert.match(await page.locator('#'+id).textContent(),/Reload/i);
 result.gate=await gate(page);if(result.mode==='cleanup'){assert.equal(result.gate.cleanupThrows,1);assert.equal(result.gate.settlements.at(-1).kind,'native-fulfilled');}if(result.mode==='notification-after')assert.equal(result.gate.roleThrows,1);assert.equal(result.gate.storage.writes-(result.initialWrites||0),committed?1:0);await capture(page,result,'reload-only');await page.locator('#modal-cancel').click();await closed(page);assert.equal(await page.locator('[data-mutate]:enabled').count(),0);result.checks.push('Terminal failure releases native writer lock, observes rejection, and blocks duplicate inverse until reload');await restore(page,result,before,{committed});
}
async function takeover(page,result,scenario,before,context){
 const peer=await context.newPage();await peer.goto(new URL('verification/undo-peer.html',base).href);await peer.evaluate(async({storeURL})=>{const {Store}=await import(storeURL);globalThis.undoPeer={state:null,editable:false};undoPeer.store=new Store(next=>{undoPeer.state=next;},editable=>{undoPeer.editable=editable;});await undoPeer.store.acquire(true);},result.runtime);await peer.waitForFunction(()=>undoPeer.editable);await page.waitForFunction(()=>undoGate.store.editable===false);
 const revision=await peer.evaluate(async({storeURL})=>{const url=new URL('state.mjs',storeURL);url.search=new URL(storeURL).search;const S=await import(url.href),next=S.transition(undoPeer.state,'Peer deposit during Undo',s=>S.deposit(s,7,'Synthetic native lock owner'));undoPeer.store.save(next,undoPeer.state.revision);return undoPeer.state.revision;},result.runtime);await page.waitForFunction(({key,revision})=>JSON.parse(localStorage.getItem(key)).revision===revision,{key:KEY,revision});const bytes=await raw(page);assert.equal((await read(page)).bank,String(BigInt(before.bank)+7n));await release(page);await frames(page);assert.equal(await raw(page),bytes);assert.equal((await gate(page)).settlements.at(-1).code,'SAVE_NOT_COMMITTED');assert.match(await page.locator('#modal-error').textContent(),/editing|changed|read-only|stale/i);assert.doesNotMatch(await page.locator('#message').textContent(),successPattern);await page.locator('#modal-form').evaluate(form=>form.requestSubmit());assert.equal((await gate(page)).calls,1);await capture(page,result,'ownership-lost');result.gate=await gate(page);
 await peer.evaluate(()=>{undoPeer.store.yield();undoPeer.store.channel?.close();});await peer.close();await page.reload();await page.getByText('Editing in this tab',{exact:true}).waitFor();assert.equal(await raw(page),bytes);await capture(page,result,'authoritative-reload');result.checks.push('Second actual Store takes native writer lock; old Undo cannot overwrite peer revision or revive its UI');
}
async function syncCase(page,result,scenario){
 const before=await read(page);await openUndo(page,scenario.path);if(scenario.path==='jump'){assert.equal(await raw(page),JSON.stringify(before));await page.locator('#modal-cancel').click();await closed(page);await openUndo(page,'jump');}await start(page,scenario.path);await closed(page);assertUndo(await read(page),before);assert.match(await page.locator('#message').textContent(),successPattern);assert.equal(await page.evaluate(()=>undoStorage.writes),1);await capture(page,result,'synchronous');
 if(scenario.path==='jump'){
  assert.deepEqual(material(await read(page)),material(fixture()));assert.equal((await read(page)).jumpAttempts[0].mulliganUsed,true);await action(page,'jump').click();await page.locator('#modal [name="hours"]').fill('160');const prepared=await read(page);assert.equal(prepared.jumpAttempts[0].rolls.length,2);assert.equal(await page.evaluate(()=>undoDiceCalls),6);await page.locator('#modal-cancel').click();await closed(page);await action(page,'jump').click();assert.equal(await raw(page),JSON.stringify(prepared));await page.locator('#modal [name="hours"]').fill('160');await page.locator('#modal-submit').click();await closed(page);assert.equal(S.jumpUndoEligibility(await read(page)).allowed,false);assert.equal(await action(page,'jump-undo').isDisabled(),true);const bytes=await raw(page);await tab(page,'History');await action(page,'undo').click();assert.equal(await raw(page),bytes);assert.match(await page.locator('#message').textContent(),/Cannot undo this protected jump/);await capture(page,result,'one-mulligan-final');
 }else await restore(page,result,before);
 result.checks.push('Existing synchronous contract and dedicated confirmation remain unchanged; one inverse per deliberate action');
}
async function prepareTransport(page,mode){
 await tab(page,'Contracts');await action(page,mode==='mail'?'mail-check':'contracts-search').click();const form=page.locator('#modal');await form.getByText('Manual mail rolls (optional)',{exact:true}).click();for(const [name,value]of Object.entries({dice:'8',skill:'0',characteristic:'0',mailAvailability:'12',mailContainers:'3'})){const field=form.locator('[name="'+name+'"]');if(await field.count())await field.fill(value);}await page.locator('#modal-submit').click();await closed(page);assert.ok(await page.locator('[data-action="contract-accept"]').count()>0,'Real current-session offers exist before Undo');
}
async function runCaseBody(page,result,scenario,context){
 await page.goto(base);await page.getByText('Editing in this tab',{exact:true}).waitFor();if(scenario.mode==='sync'){await syncCase(page,result,scenario);return;}
 if(scenario.mode.startsWith('protected-')){await tab(page,'History');const bytes=await raw(page);await action(page,'undo').click();assert.equal(await raw(page),bytes);assert.equal(await page.evaluate(()=>undoStorage.writes),0);assert.match(await page.locator('#message').textContent(),/Cannot undo this protected jump.*Nothing was changed/);assert.equal(await page.locator('#modal').isVisible(),false);await capture(page,result,'protected-jump');result.checks.push('Protected jump barrier keeps history, bank, travel and mulligan unchanged');return;}
 if(['mail','contracts'].includes(scenario.mode))await prepareTransport(page,scenario.mode);
 await installGate(page,result);await openUndo(page,scenario.path);const before=await read(page),bytes=await raw(page);result.initialWrites=await page.evaluate(()=>undoStorage.writes);
 if(scenario.mode==='idle-invalidated'){
  // The actual Store storage listener receives a foreign same-revision update.
  await page.evaluate(key=>dispatchEvent(new StorageEvent('storage',{key,newValue:localStorage.getItem(key)})),KEY);await frames(page);assert.match(await page.locator('#modal-error').textContent(),/changed|reopen/i);assert.equal(await page.locator('#modal-submit').isDisabled(),true);await page.locator('#modal-form').evaluate(form=>form.requestSubmit());assert.equal(await raw(page),bytes);await capture(page,result,'stale-review');await page.locator('#modal-cancel').click();await closed(page);await openUndo(page,'jump');await start(page,'jump');await closed(page);assertUndo(await read(page),before);result.checks.push('Idle same-revision foreign publication invalidates Undo Jump until a fresh review');await capture(page,result,'fresh-review');return;
 }
 if(scenario.mode==='reentrant'){await page.evaluate(()=>{undoGate.reentrant=true;});await start(page,'history');assertUndo(await read(page),before);assert.equal((await gate(page)).reentrantCalls,1);assert.equal((await gate(page)).storage.writes,1);assert.equal((await read(page)).undo.length,1);await capture(page,result,'one-inverse');result.gate=await gate(page);result.checks.push('Synchronous actual publication reenters History Undo without a second inverse');return;}
 if(scenario.mode.startsWith('pending-ui-')){
  const after=scenario.mode==='pending-ui-after';await page.evaluate(after=>{undoGate.armed=true;undoGate.pendingUI=after?'after':'before';},after);await start(page,'history');await page.waitForFunction(()=>undoGate.pendingUIThrows===1&&undoGate.store?.reloadRequired===true&&!!undoGate.pending);const durable=await raw(page);if(after)assertUndo(await read(page),before);else assert.equal(durable,bytes);await release(page);await frames(page);assert.equal(await raw(page),durable);assert.equal((await gate(page)).reloadRequired,true);assert.equal((await gate(page)).storage.writes,after?1:0);assert.doesNotMatch(await page.locator('#message').textContent(),successPattern);await capture(page,result,'pending-screen-fault');result.gate=await gate(page);await restore(page,result,before,{committed:after});result.checks.push('Pending-screen failure never abandons original completion or permits an unsafe retry');return;
 }
 await arm(page,scenario);await pending(page,result,scenario,bytes);
 if(scenario.mode==='takeover'){await takeover(page,result,scenario,before,context);return;}
 if(scenario.mode==='prewrite'){
  await release(page);await page.locator('#modal-error').filter({hasText:'Synthetic known prewrite'}).waitFor();assert.equal(await raw(page),bytes);assert.equal((await gate(page)).reloadRequired,false);await capture(page,result,'retryable');if(scenario.path==='history'){assert.equal(await page.locator('#modal-submit').isHidden(),true);assert.match(await page.locator('#modal-body').textContent(),/close.*undo|close.*try/i);await page.locator('#modal-cancel').click();await closed(page);await action(page,'undo').click();}else{assert.equal(await page.locator('#modal-submit').isEnabled(),true);await page.locator('#modal-submit').click();}await page.waitForFunction(()=>!!undoGate.pending);assert.equal((await gate(page)).calls,2);await page.locator('#modal-form').evaluate(form=>{globalThis.detachedUndoSubmit=form.onsubmit;form.requestSubmit();});assert.equal((await gate(page)).calls,2);await release(page);await successful(page,result,before);return;
 }
 if(scenario.mode==='tokenless'||scenario.mode==='late-role-loss'){
  if(scenario.mode==='late-role-loss')await page.evaluate(()=>{undoGate.write();undoGate.store.yield();});else await page.evaluate(()=>undoGate.store.onChange(undoGate.store.read()));await release(page);await frames(page);assertUndo(await read(page),before);const durable=await raw(page);assert.doesNotMatch(await page.locator('#message').textContent(),successPattern);await page.locator('#modal-form').evaluate(form=>form.requestSubmit());assert.equal((await gate(page)).calls,1);assert.equal(await raw(page),durable);if(scenario.path==='jump')assert.match(await page.locator('.world-info').textContent(),/Undo Destination/,'Old completion cannot reset browsing location');await capture(page,result,'retired-session');result.gate=await gate(page);await restore(page,result,before);result.checks.push('Same-revision replacement or late ownership loss retires old cleanup without replaying Undo');return;
 }
 if(['success','history-jump','world-correction','baseline','mail','contracts'].includes(scenario.mode)){
  await page.evaluate(()=>undoGate.write());await frames(page);assertUndo(await read(page),before);assert.equal(await page.locator('#modal').evaluate(dialog=>dialog.open),true);assert.doesNotMatch(await page.locator('#message').textContent(),successPattern);for(const id of ['modal-cancel','modal-close'])assert.equal(await page.locator('#'+id).isDisabled(),true);if(scenario.path==='jump')assert.match(await page.locator('.world-info').textContent(),/Undo Destination/);await capture(page,result,'durable-awaiting-completion');await release(page);await closed(page);
  const saved=await read(page);if(scenario.mode==='world-correction'){assert.equal(saved.worlds['0,0'].overrideUWP,'A788899-D');assert.equal(saved.worlds['0,0'].zone,'Amber');for(const key of ['bank','ship','contracts','policies','lots','snapshots','ledger','actual','hours','jumpAttempts','dashboardBaseline'])assert.deepEqual(saved[key],before[key]);const source=saved.events.find(e=>e.worldChangeAudit?.kind==='edit');assert.equal(worldFieldRevertEligibility(saved,source.id,'techLevel',core).allowed,true);result.checks.push('Undo restores only the individual world-field correction and keeps economic/jump/audit history');}
  if(scenario.mode==='baseline'){assert.deepEqual(saved.dashboardBaseline,before.dashboardBaseline);assert.equal(dashboardData(saved).adjustment,'-125');assert.equal(dashboardData(saved).operatingResult,'0');await tab(page,'Dashboard');assert.match(await page.locator('.dashboard').textContent(),/Earlier-history adjustment: Cr -125/);await capture(page,result,'baseline-adjustment');result.checks.push('Crossing baseline retains its metadata and reports balance correction outside profit');}
  if(scenario.mode==='history-jump'){assert.deepEqual(material(saved),material(fixture()));assert.equal(saved.jumpAttempts[0].mulliganUsed,true);result.checks.push('Immediate History Undo of eligible jump consumes exactly one mulligan and restores all travel economics');}
  if(['mail','contracts'].includes(scenario.mode)){await tab(page,'Contracts');assert.equal(await page.locator('[data-action="contract-accept"]').count(),0);assert.deepEqual(saved.contracts,before.contracts);assert.deepEqual(saved.ledger,before.ledger);result.checks.push('Real generated transport previews clear after Undo without resurrecting offers or changing accepted contracts');}
  await successful(page,result,before);return;
 }
 if(scenario.mode==='cleanup')await page.evaluate(()=>{undoGate.cleanupFault=true;});const unknown=scenario.mode.startsWith('unknown-'),committed=scenario.mode!=='unknown-before';await release(page,unknown?scenario.mode:'native');await terminal(page,result,before,{committed,unknown});
}
async function writeReport(){await writeFile(join(artifacts,'undo-completion-report.json'),JSON.stringify(report,null,2)+'\n');}
async function runCase(scenario,viewport){
 const result={id:scenario.id+'-'+viewport.width,path:scenario.path,mode:scenario.mode,viewport,status:'running',checks:[],screenshots:[],layouts:[],pageErrors:[],unhandledRejections:[],consoleErrors:[],unexpectedRequests:[],errors:[]};report.cases.push(result);let context;
 try{context=await contextFor(result,scenario);const page=await context.newPage();await runCaseBody(page,result,scenario,context);await frames(page);assert.deepEqual(result.pageErrors,[]);assert.deepEqual(result.unhandledRejections,[]);assert.deepEqual(result.consoleErrors,[]);assert.deepEqual(result.unexpectedRequests,[]);result.status='passed';}
 catch(error){result.status='failed';result.errors.push(errorText(error));const page=context?.pages()[0];if(page){await capture(page,result,'failure').catch(()=>{});result.failedGate=await gate(page).catch(()=>null);}}
 finally{await context?.close();await writeReport();}console.log(result.status.toUpperCase()+': '+result.id);for(const error of result.errors)console.error(error);
}
if(process.argv.includes('--fixtures-only')){
 for(const scenario of scenarios){const before=seed(scenario);if(scenario.mode.startsWith('protected-')){assert.throws(()=>S.undo(before),/later campaign change|Mulligan used/);continue;}if(['mail','contracts'].includes(scenario.mode))continue;assertUndo(S.undo(before),before);}
 assert.deepEqual(material(S.undoJump(jump())),material(fixture()));const crossing=seed({path:'history',mode:'baseline'});assert.equal(dashboardData(S.undo(crossing)).adjustment,'-125');
 const html=await readFile(new URL('../index.html',import.meta.url),'utf8'),app=await readFile(new URL('../js/app.mjs',import.meta.url),'utf8');assert.match(html,/<script type="module" src="js\/app\.mjs\?[^\"]+"/);assert.match(app,/import\s*\{[^}]*\bStore\b[^}]*\}\s*from\s*['"]\.\/persistence\.mjs\?[^'"]+['"]/);assert.equal(new Set(scenarios.map(s=>s.id)).size,scenarios.length);console.log(`PASS: exact synthetic Undo economic/audit/mulligan, world correction and Dashboard fixtures; actual versioned Store discovery; ${scenarios.length} scenarios x ${sizes.length} widths = ${report.declaredCases} browser cases declared. Chromium was not launched.`);
}else{
 await mkdir(artifacts,{recursive:true});try{report.testedCommit=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim();if(report.requestedCommit)assert.equal(report.testedCommit,report.requestedCommit);const {chromium}=createRequire(import.meta.url)(process.argv[2]||'playwright');browser=await chromium.launch({headless:true,...(process.env.TRAVELLER_BROWSER_CHANNEL?{channel:process.env.TRAVELLER_BROWSER_CHANNEL}:{})});report.browser={name:'Chromium',version:browser.version()};for(const viewport of sizes)for(const scenario of scenarios)await runCase(scenario,viewport);const files=(await readdir(artifacts)).filter(name=>name.startsWith('undo-completion-'));report.screenshotCount=files.filter(name=>name.endsWith('.jpg')).length;report.artifactBytes=(await Promise.all(files.map(async name=>(await stat(join(artifacts,name))).size))).reduce((a,b)=>a+b,0);assert.ok(report.artifactBytes<24*1024*1024-65536,'Undo evidence must remain below the bounded 24 MiB download size');}
 catch(error){report.errors.push(errorText(error));}finally{await browser?.close();report.finishedAt=new Date().toISOString();report.passed=report.errors.length===0&&report.cases.length===report.declaredCases&&report.cases.every(result=>result.status==='passed');await writeReport();}if(!report.passed)throw Error('Undo completion Chromium checks failed; see verification-artifacts/undo-completion-report.json');console.log(`PASS: ${report.declaredCases} actual Undo/Undo Jump browser cases, exact economics/audit, native locking, one mulligan, desktop/mobile JPEG evidence; no uncaught errors or unhandled rejections.`);
}
