import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const {chromium}=createRequire(import.meta.url)(process.argv[2]||'playwright');
const browser=await chromium.launch({headless:true,...(process.env.TRAVELLER_BROWSER_CHANNEL?{channel:process.env.TRAVELLER_BROWSER_CHANNEL}:{})});
const ctx=await browser.newContext();
const sample=[{Name:'Regina',Hex:'1910',UWP:'A788899-C',PBG:'703',Zone:'',WorldX:-110,WorldY:-70,Sector:'Spinward Marches'},{Name:'Jenghe',Hex:'1810',UWP:'C799663-9',PBG:'323',Zone:'',WorldX:-111,WorldY:-70,Sector:'Spinward Marches'},{Name:'Ruie',Hex:'1809',UWP:'C776977-7',PBG:'701',Zone:'A',WorldX:-111,WorldY:-71,Sector:'Spinward Marches'}];
await ctx.route('https://travellermap.com/api/universe?*',route=>route.fulfill({json:{Sectors:[{Names:[{Text:'Spinward Marches'}],Abbreviation:'Spin'},{Names:[{Text:'Empty Sector'}]},{Names:[{Text:'Broken Sector'}]},{Names:[{Text:'Trojan Reach'}],Milieu:'M1105'},{Names:[{Text:'Trojan Reach'}],Milieu:'M1120'},{Names:[{Text:'Trojan Reach'}],Milieu:'M1201'},{Names:[{Text:'Trojan Reach'}],Milieu:'M1248'},{Names:[{Text:'Trojan Reach'}],Milieu:'M1105'}]}}));
let broken=true;
await ctx.route('https://travellermap.com/api/metadata?*',async route=>{const name=new URL(route.request().url()).searchParams.get('sector');if(name==='Broken Sector'&&broken){broken=false;return route.fulfill({status:503,body:'unavailable'});}if(name==='Empty Sector')await new Promise(r=>setTimeout(r,300));await route.fulfill({json:{Subsectors:[{Index:'C',Name:'Regina'},{Index:'A',Name:'Cronor'}]}});});
await ctx.route('https://travellermap.com/api/sec?*',route=>route.fulfill({json:'Hex\tName\r\n'+(new URL(route.request().url()).searchParams.get('sector')==='Empty Sector'?'':sample.map(w=>w.Hex+'\t'+w.Name).join('\r\n'))}));
await ctx.route('https://travellermap.com/api/jumpworlds?*',route=>{const u=new URL(route.request().url());return route.fulfill({json:{Worlds:u.searchParams.get('jump')==='0'?sample.filter(w=>w.Hex===u.searchParams.get('hex')):sample}});});
const page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
const base=process.env.TRAVELLER_TEST_URL||'http://127.0.0.1:8765/';
const click=name=>page.getByRole('button',{name,exact:true}).click();
const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('traveller-trade-route-calculator:v1')));
const choose=async(host,hex)=>{await host.getByLabel('Subsector',{exact:true}).selectOption('C');await host.getByLabel('World',{exact:true}).selectOption(hex);};
try{
 await page.goto(base);await page.getByText('Editing in this tab',{exact:true}).waitFor();await click('Set up campaign');
 await page.locator('#setup-world .picker-selection').getByText(/Hex 1910/).waitFor();await click('Start campaign');await page.locator('#modal').waitFor({state:'hidden'});
 const before=await read();
 assert.ok(await page.locator('.hex-grid polygon').count()>0);assert.ok(await page.locator('.hex-grid polygon').count()<=61);
 const aligned=await page.evaluate(()=>{const polygon=document.querySelector('.hex-grid [data-hex="1910"]');const points=Array.from(polygon.points);const x=points.reduce((n,p)=>n+p.x,0)/6,y=points.reduce((n,p)=>n+p.y,0)/6;const circle=document.querySelector('svg [data-arg="-110,-70"] circle');return Math.abs(x-Number(circle.getAttribute('cx')))<0.01&&Math.abs(y-Number(circle.getAttribute('cy')))<0.01;});assert.ok(aligned);
 await page.getByLabel('Show hexes',{exact:true}).uncheck();assert.equal(await page.locator('.hex-grid').count(),0);await page.getByLabel('Show hexes',{exact:true}).check();
 await page.locator('svg [data-arg="-111,-70"]').click();assert.deepEqual(await read(),before);await click('Current ship');
 const map=page.locator('.world-map');
 const separation=()=>page.evaluate(()=>{const a=document.querySelector('svg [data-arg="-110,-70"] circle'),b=document.querySelector('svg [data-arg="-111,-70"] circle');return Math.abs(Number(a.getAttribute('cx'))-Number(b.getAttribute('cx')));});
 const initialSpacing=await separation();await map.hover();const scrollBefore=await page.evaluate(()=>scrollY);await page.mouse.wheel(0,-150);await page.waitForFunction(()=>document.querySelector('.map-zoom-controls span').textContent!=='100%');assert.ok(await separation()>initialSpacing);assert.equal(await page.evaluate(()=>scrollY),scrollBefore);
 await page.mouse.wheel(0,150);await page.waitForFunction(()=>document.querySelector('.map-zoom-controls span').textContent==='100%');
 await click('+');await page.waitForFunction(()=>document.querySelector('.map-zoom-controls span').textContent==='120%');
 await click('Reset view');await page.waitForFunction(()=>document.querySelector('.map-zoom-controls span').textContent==='100%');assert.deepEqual(await read(),before);
 await click('Find world');const picker=page.locator('#find-world');await picker.locator('.picker-selection').getByText(/Hex 1910/).waitFor();
 assert.equal(await picker.getByLabel('Sector',{exact:true}).locator('option').filter({hasText:'Trojan Reach'}).count(),1);
 await picker.getByLabel('Search worlds',{exact:true}).fill('jeng');await picker.getByLabel('World',{exact:true}).selectOption('1810');assert.match(await picker.locator('.picker-selection').textContent(),/Hex 1810/);
 await click('Browse world');await page.locator('#modal').waitFor({state:'hidden'});assert.deepEqual(await read(),before);
 await click('Find world');await picker.locator('.picker-selection').getByText(/Hex 1810/).waitFor();
 assert.equal(await picker.getByLabel('Recent worlds',{exact:true}).locator('option').count(),3);
 await picker.getByLabel('Recent worlds',{exact:true}).selectOption('1');await picker.locator('.picker-selection').getByText(/Hex 1910/).waitFor();
 await picker.getByLabel('Recent worlds',{exact:true}).selectOption('0');await picker.locator('.picker-selection').getByText(/Hex 1810/).waitFor();
 // Filtering away a parent selection clears all its descendants and prevents stale submission.
 await picker.getByLabel('Search sectors',{exact:true}).fill('Empty');assert.equal(await picker.getByLabel('World',{exact:true}).inputValue(),'');await click('Browse world');await page.locator('#modal-error').getByText('Choose a sector, subsector and world.',{exact:true}).waitFor();
 await picker.getByLabel('Search sectors',{exact:true}).fill('');await picker.getByLabel('Sector',{exact:true}).selectOption('Empty Sector');await picker.getByLabel('Sector',{exact:true}).selectOption('Spinward Marches');await choose(picker,'1809');await page.waitForTimeout(400);assert.equal(await picker.getByLabel('World',{exact:true}).inputValue(),'1809');
 await picker.getByLabel('Sector',{exact:true}).selectOption('Broken Sector');await picker.getByRole('button',{name:'Retry loading'}).waitFor();await picker.getByRole('button',{name:'Retry loading'}).click();await choose(picker,'1810');
 await picker.getByLabel('Sector',{exact:true}).selectOption('Empty Sector');await picker.getByLabel('Subsector',{exact:true}).selectOption('C');assert.match(await picker.getByLabel('World',{exact:true}).textContent(),/No worlds/);
 await page.locator('#modal-cancel').click();await click('Plot route');assert.match(await page.locator('.route-origin').textContent(),/Regina/);
 const dest=page.locator('#route-destination');await choose(dest,'1809');await click('Add stop');await choose(page.locator('.route-stop').nth(0),'1810');await click('Add stop');await choose(page.locator('.route-stop').nth(1),'1910');
 await page.locator('.route-stop').nth(1).getByRole('button',{name:'Move up'}).click();assert.match(await page.locator('.route-stop').nth(0).locator('.picker-selection').textContent(),/Regina/);
 await page.locator('.route-stop').nth(0).getByRole('button',{name:'Remove stop'}).click();await click('Calculate route');await page.getByRole('heading',{name:'Review route',exact:true}).waitFor();await click('Save route');await page.locator('#modal').waitFor({state:'hidden'});
 const after=await read();assert.equal(after.actual,before.actual);assert.equal(after.hours,before.hours);assert.equal(after.bank,before.bank);assert.deepEqual(after.mandatoryStops,['-111,-70','-111,-71']);
 await click('Plot route');await dest.locator('.picker-selection').getByText(/Hex 1809/).waitFor();assert.match(await page.locator('.route-stop .picker-selection').textContent(),/Hex 1810/);
 await page.setViewportSize({width:390,height:844});assert.ok(await page.locator('#modal').evaluate(e=>e.scrollWidth<=e.clientWidth+2));
 await page.locator('#modal-cancel').click();await page.reload();await page.getByText('Editing in this tab',{exact:true}).waitFor();await click('Find world');
 assert.ok(await page.locator('#find-world').getByLabel('Recent worlds',{exact:true}).locator('option').count()>=3);
 await page.evaluate(async()=>{const {rememberWorld}=await import('./js/world-picker.mjs');for(let i=1;i<=12;i++)rememberWorld({name:'Recent '+i,sector:'Spinward Marches',hex:String(i).padStart(2,'0')+'01'});rememberWorld({name:'Recent 12',sector:'Spinward Marches',hex:'1201'});});
 const recent=await page.evaluate(()=>JSON.parse(localStorage.getItem('traveller-trade-route-calculator:recent-worlds:v1')));
 assert.equal(recent.length,10);assert.equal(recent[0].hex,'1201');assert.equal(new Set(recent.map(w=>w.hex)).size,10);
 await page.locator('#modal-cancel').click();await click('Find world');await page.locator('#find-world').getByLabel('Subsector',{exact:true}).selectOption('C');await page.locator('#find-world').getByLabel('World',{exact:true}).selectOption('1810');
 const beforeLocation=await read();await page.locator('#choose-starting-world').click();await page.getByRole('heading',{name:'Set ship location',exact:true}).waitFor();await page.locator('#modal-cancel').click();assert.deepEqual(await read(),beforeLocation);
 await click('Find world');await page.locator('#find-world').getByLabel('Subsector',{exact:true}).selectOption('C');await page.locator('#find-world').getByLabel('World',{exact:true}).selectOption('1810');await page.locator('#choose-starting-world').click();await page.getByRole('heading',{name:'Set ship location',exact:true}).waitFor();await click('Confirm starting world');await page.locator('#modal').waitFor({state:'hidden'});
 const moved=await read();assert.equal(moved.actual,'-111,-70');assert.deepEqual(moved.route,['-111,-70']);assert.equal(moved.routeIndex,0);assert.equal(moved.bank,beforeLocation.bank);assert.equal(moved.hours,beforeLocation.hours);assert.deepEqual(moved.lots,beforeLocation.lots);assert.deepEqual(moved.contracts,beforeLocation.contracts);
 await click('History');await click('Undo latest change');const undone=await read();assert.equal(undone.actual,beforeLocation.actual);assert.deepEqual(undone.route,beforeLocation.route);
 assert.deepEqual(errors,[]);console.log('PASS: cascading search, derived hex, browsing invariants, parent reset, loading race, retry, empty sector, actual origin, stop reorder/removal, route persistence, recent-world persistence/deduplication, hex alignment/toggle/clicking and mobile width.');
}finally{await browser.close();}
