import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir,readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {join} from 'node:path';
const artifacts=fileURLToPath(new URL('../verification-artifacts/',import.meta.url));
await mkdir(artifacts,{recursive:true});
const {chromium}=createRequire(import.meta.url)(process.argv[2]||'playwright');
const base=process.env.TRAVELLER_TEST_URL||'http://127.0.0.1:8765/';
const browser=await chromium.launch({headless:true,...(process.env.TRAVELLER_BROWSER_CHANNEL?{channel:process.env.TRAVELLER_BROWSER_CHANNEL}:{})});
const ctx=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});
const sample=[{Name:'Regina',Hex:'1910',UWP:'A788899-C',PBG:'703',Zone:'',WorldX:-110,WorldY:-70,Sector:'Spinward Marches'},{Name:'Jenghe',Hex:'1810',UWP:'C799663-9',PBG:'323',Zone:'',WorldX:-111,WorldY:-70,Sector:'Spinward Marches'},{Name:'Ruie',Hex:'1809',UWP:'C776977-7',PBG:'701',Zone:'A',WorldX:-112,WorldY:-70,Sector:'Spinward Marches'}];
await ctx.route('https://travellermap.com/api/jumpworlds?*',async route=>{const u=new URL(route.request().url());const rows=u.searchParams.get('jump')==='0'?sample.filter(w=>w.Hex===(u.searchParams.get('hex')||'1910')):sample;await route.fulfill({json:{Worlds:rows},headers:{'Access-Control-Allow-Origin':'*'}});});
await ctx.route('https://travellermap.com/api/universe?*',route=>route.fulfill({json:{Sectors:[{Names:[{Text:'Spinward Marches'}],Abbreviation:'Spin'},{Names:[{Text:'Empty Sector'}]}]}}));
await ctx.route('https://travellermap.com/api/metadata?*',route=>route.fulfill({json:{Subsectors:[{Index:'C',Name:'Regina'},{Index:'A',Name:'Cronor'}]}}));
await ctx.route('https://travellermap.com/api/sec?*',route=>route.fulfill({json:'Hex\tName\r\n'+sample.map(w=>w.Hex+'\t'+w.Name).join('\r\n')}));
const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const click=async label=>{const modal=page.locator('#modal[open]');const target=modal.getByRole('button',{name:label,exact:true});if(await target.count())return target.click();return page.getByRole('button',{name:label,exact:true}).click();};
const fill=(name,value)=>page.locator('[name="'+name+'"]').fill(String(value));
const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('traveller-trade-route-calculator:v1')));
const closed=()=>page.locator('#modal').waitFor({state:'hidden'});
const choose=id=>page.locator('svg [data-action="map-world"][data-arg="'+id+'"]').click();
const ready=()=>page.getByRole('button',{name:'Save planned route',exact:true}).waitFor({state:'visible'}).then(()=>page.waitForFunction(()=>!document.querySelector('[data-action="route-save"]').disabled));
try{
 await page.goto(base);await page.getByText('Editing in this tab',{exact:true}).waitFor();await click('Set up campaign');await page.locator('#setup-world .picker-selection').getByText(/Hex 1910/).waitFor();await fill('shipTons',200);await fill('fuelCapacity',40);await fill('fuelAboard',40);await click('Start campaign');await closed();const before=await read();
 await click('Refuel');assert.equal(await page.locator('[name="fuelTons"]').inputValue(),'0');assert.match(await page.locator('#service-quote').textContent(),/No fuel to acquire/);assert.equal(await page.locator('[data-action="service-confirm"]').isDisabled(),true);for(const kind of ['berthing','salary','staterooms','passengerSupport'])assert.equal(await page.locator('[name="include-'+kind+'"]').count(),0);assert.equal(await page.getByRole('button',{name:'Select all expenses',exact:true}).count(),0);await click('Cancel');
 await click('Accounts');await page.locator('#main').getByRole('button',{name:'Ship expenses',exact:true}).click();await page.locator('[name="include-berthing"]').uncheck();await page.locator('[name="include-fuel"]').check();
 await page.locator('[name="include-salary"]').check();await fill('salary',20000);await fill('salaryMonths',1);assert.equal(await page.getByRole('button',{name:'Preview expenses',exact:true}).isEnabled(),true);assert.match(await page.locator('#expense-estimate').textContent(),/No fuel to purchase/);
 await fill('fuelTons',1);assert.equal(await page.getByRole('button',{name:'Preview expenses',exact:true}).isDisabled(),true);await fill('fuelTons',0);await click('Preview expenses');await click('Pay Cr 20,000');await closed();const paid=await read();assert.equal(paid.bank,'80000');assert.equal(paid.ship.fuel.aboardTons,40);assert.equal(paid.ledger.length,before.ledger.length+1);assert.equal(paid.ledger.at(-1).expense.kind,'salary');
 await click('History');await click('Undo latest change');assert.equal((await read()).bank,before.bank);assert.equal((await read()).ship.fuel.aboardTons,40);await click('Accounts');await click('Record deposit');await fill('amount',25000);await fill('reason','Passenger payment');await click('Preview deposit');assert.equal((await read()).bank,before.bank);await click('Cancel');assert.equal((await read()).bank,before.bank);
 await click('Record deposit');await fill('amount',25000);await fill('reason','Passenger payment');await click('Preview deposit');await click('Deposit Cr 25,000');await closed();const deposited=await read();assert.equal(deposited.bank,'125000');assert.equal(deposited.ledger.at(-1).type,'Manual deposit');assert.equal(deposited.ledger.at(-1).reason,'Passenger payment');await page.reload();await page.getByText('Editing in this tab',{exact:true}).waitFor();assert.equal((await read()).bank,'125000');await click('History');await click('Undo latest change');assert.equal((await read()).bank,before.bank);assert.deepEqual(errors,[]);console.log('PASS: fuel-only form, zero-fuel expense batches, deposits, cancellation, persistence and undo.');
}finally{await browser.close();}
