import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
const {chromium}=createRequire(import.meta.url)(process.argv[2]||'playwright');
const browser=await chromium.launch({headless:true,...(process.env.NAV_BROWSER_CHANNEL?{channel:process.env.NAV_BROWSER_CHANNEL}:{})});
let checks=0;
const check=(actual,expected)=>{assert.deepEqual(actual,expected);checks++;};
try {
 const page=await browser.newPage();
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 if(process.env.NAV_TEST_URL) await page.goto(process.env.NAV_TEST_URL);
 else await page.setContent(await readFile(new URL('../index.html',import.meta.url),'utf8'));
 await page.waitForFunction(()=>typeof solve==='function');
 const fill=async(id,value)=>page.locator('#'+id).fill(String(value));
 const select=async(id,value)=>page.locator('#'+id).selectOption(String(value));
 const text=async id=>page.locator('#'+id).textContent();
 const solveRoute=()=>page.getByRole('button',{name:'Solve Route',exact:true}).click();
 const clear=()=>page.getByRole('button',{name:'Clear',exact:true}).click();
 await fill('thrust',1);await fill('distanceKm',100000);await solveRoute();
 check(await text('mainTime'),'0d 1h 46m');
 await select('profile','const');check(await text('mainTime'),'0d 1h 15m');
 await clear();await fill('thrust',1);await select('distMode','map');await fill('au1',1);await fill('au2',1);await select('separation','2');await solveRoute();
 check(await page.evaluate(()=>Math.abs(computeDistanceInfo().rawKm/150000000-Math.sqrt(2))<1e-12),true);
 check((await text('mainTime'))!=='0d 0h 0m',true);
 await select('separation','same');await solveRoute();check((await text('errorBox')).includes('zero separation'),true);
 await select('separation','1');await fill('au2',5);await solveRoute();
 check(await page.evaluate(()=>computeDistanceInfo().rawKm/150000000>4),true);
 await select('separation','opp');await select('routeType','trans');await solveRoute();
 check(await text('commOut'),'0d 0h 50m');check(await page.evaluate(()=>computeDistanceInfo().routedKm/150000000),12);
 await clear();await fill('thrust',1);await fill('distanceKm',100000);await page.locator('#useAstro').check();await fill('manualPct',150);await solveRoute();
 check((await text('errorBox')).includes('below 100%'),true);check(await text('mainTime'),'—');
 await fill('manualPct',100);await solveRoute();check((await text('errorBox')).includes('below 100%'),true);
 await fill('manualPct',20);await solveRoute();check(await text('mainTime'),'0d 1h 25m');
 await fill('manualPct','');await fill('effect',50);await page.locator('#autoDice').uncheck();await solveRoute();
 check((await text('errorBox')).includes('positive, finite'),true);
 await fill('effect',1.5);await solveRoute();check((await text('errorBox')).includes('whole-number'),true);
 await fill('effect',1000000000);await solveRoute();check((await text('errorBox')).includes('supported range'),true);
 await clear();await fill('thrust',1);await page.getByRole('button',{name:'Compute 100D Only',exact:true}).click();
 check((await text('jumpOut')).includes('6h 21m'),true);
 await select('profile','const');check((await text('jumpOut')).includes('4h 29m'),true);
 await clear();await select('distMode','map');await select('aMode','orbit');await select('bMode','orbit');await select('aOrbitWhole','12');await select('bOrbitWhole','15');await fill('aOrbitFrac',0.5);await fill('bOrbitFrac',0.25);await clear();await select('distMode','map');
 check(await page.evaluate(()=>['aMode','bMode','aOrbitWhole','bOrbitWhole','aOrbitFrac','bOrbitFrac'].map(id=>document.getElementById(id).value)),['au','au','3','6','0','0']);
 await clear();await fill('thrust',1);await fill('distanceKm',100000);await solveRoute();await fill('distanceKm',-1);
 check(await page.evaluate(()=>lastBrief),'');check(await text('mainTime'),'—');
 await solveRoute();check(await page.evaluate(()=>lastBrief),'');check((await text('errorBox')).includes('positive distance'),true);
 await fill('distanceKm',100000);await solveRoute();await page.getByRole('button',{name:'Compute 100D Only',exact:true}).click();check(await page.evaluate(()=>lastBrief),'');check(await text('mainTime'),'—');
 check(errors,[]);
 console.log('PASS: '+checks+' nav regression checks (geometry, timing, validation, clearance profile, reset, stale outputs).');
}finally{await browser.close();}
